<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="HMI" Id="{60dc6bb9-8218-49aa-8772-c76a0aa4b773}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM HMI

VAR_IN_OUT CONSTANT
	{ attribute 'TcHmiSymbol.Hide' }
	monitor								: ST_System_Monitor;
	{ attribute 'TcHmiSymbol.Hide' }
	PNcontrolvars						: ST_ExtController_get;
	{ attribute 'TcHmiSymbol.Hide' }
	Iotcontrolvars						: ST_ExtController_get;	
	{ attribute 'TcHmiSymbol.Hide' }
	PLCpersistvars						: ST_PLCPersistentvars;
END_VAR

VAR
	{ attribute 'TcHmiSymbol.ShowRecursively' }
	Monitoringvars		: ST_HMI_Monitor;
	{ attribute 'TcHmiSymbol.ShowRecursively' }
	Controlvars			: ST_HMI_Control;
	{ attribute 'TcHmiSymbol.ShowRecursively' }
	Historizevars		: ST_HMI_Historize;
	{ attribute 'TcHmiSymbol.Show' }
	b_refreshHMIdata			: BOOL;
	{ attribute 'TcHmiSymbol.Show' }
	b_settingschanged			: BOOL;
	{ attribute 'TcHmiSymbol.Show' }
	b_ControlAccess				: BOOL;		
END_VAR

VAR
	t_refreshtime				: TIME:= T#1S;
	ton_refreshtimer			: TON;	
	b_initCycle					: BOOL := TRUE;
	buttons						: FB_HMIButtons;
	rTrigResetPowerSetpoints	: R_TRIG;
	
	//HMI Start/Quit vars
	fbHMIstart : NT_StartProcess;
	b_hmistart	: BOOL := TRUE;
	ton_HmiStart: TON;
	fbTaskKill	: NT_StartProcess;
	b_taskKill	: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//hard settings PLC to HMI at init
CopyActSettingsFromPLC(b_initCycle);
b_settingschanged := (MEMCMP(ADR(controlvars.HardSettings), ADR(PLCpersistvars.Hardsettings), SIZEOF(PLCpersistvars.Hardsettings)) <> 0);


//HMI REFRESH SIGNAL
ton_refreshtimer(IN:= NOT ton_refreshtimer.Q, PT:=t_refreshtime);
IF ton_refreshtimer.Q THEN
	 b_refreshHMIdata := NOT b_refreshHMIdata;
END_IF

//Read variables mapping
MapPLCVarsToHMIVars();
//ResetHMIVars when event happens.
ResetHMIvarsOnEvent();
ResetControlvarsOnVariant();

//Set array data AND LINK HMI VARIABLES
SetArraydata(arrays := monitoringvars.Arraydata, b_sync := ton_refreshtimer.Q, init := b_initCycle);


//CALL METHODS AND NESTED FUNCTIONBLOCK
buttons(controlvars := controlvars, monitoringvars := monitoringvars, b_controlaccess := b_controlaccess);
//PSB scheduler function functionaly
GetActiveTimeSlotScheduler(enable:= controlvars.SoftSettings.System.b_EnableSchedule,
	timeslot1 := controlvars.SoftSettings.system.ScheduleTimeSlot1,
	timeslot2 := controlvars.SoftSettings.system.ScheduleTimeSlot2);

b_InitCycle := FALSE;
]]></ST>
    </Implementation>
    <Folder Name="ArrayDataMethods" Id="{4ca66fc5-9f33-4dca-94c9-22713e87623e}" />
    <Folder Name="ControlsHandlingMethods" Id="{9743a59c-d1d0-4ad7-887d-018a332e942f}" />
    <Folder Name="MonitorHandlingMethods" Id="{f7a6b299-03d7-4dfc-855c-1ddf6bc9d2c5}" />
    <Folder Name="SchedulerMethods" Id="{60f9e2bb-db1c-4499-af8b-7b0818bd2dca}" />
    <Method Name="ConditionalFormatting" Id="{d5e65d05-5d3d-4e50-b7f2-4282fc4c1310}" FolderPath="MonitorHandlingMethods\">
      <Declaration><![CDATA[METHOD ConditionalFormatting 
VAR_IN_OUT
	data : ST_HMI_ConditionalFormatting;
	controls : ST_HMI_control;
END_VAR

VAR
	b_GridTakeover	: BOOL;
	b_inputgenset	: BOOL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[b_GridTakeover := monitor.controlfb.Operation.system.b_GridTakeOverEnable AND monitor.system.GenGridController.e_BreakerMode = eBreakerOperationMode.GridFeedthrough;

IF monitor.controlfb.HardSettings.setup.e_ControlSource = 0 AND
	 NOT Monitor.powerstack.b_InverterGridFormingMode AND Monitor.powerstack.b_StartedState OR b_GridTakeover THEN
		data.b_ShowPset := (NOT monitor.peakshavebox.b_active AND NOT monitor.system.GenGridController.b_active) OR b_GridTakeover;
		data.b_ShowQset := NOT Monitor.controlfb.operation.system.b_PFsetEnable;
		data.b_showPFset := Monitor.controlfb.operation.system.b_PFsetEnable AND monitor.controlfb.HardSettings.setup.e_ControlSource = 0 AND Monitor.controlfb.SoftSettings.setup.e_AcInputType <> eACInputType.Genset;
ELSE
	data.b_ShowPset := FALSE;
	data.b_ShowQset := FALSE;
	data.b_ShowPFset := FALSE;
END_IF

data.b_showPSBData := monitor.system.GenGridController.e_PowerControlMode = ePowercontrolmode.PeakshaveExt;
data.b_ShowInputDisconnect := monitor.system.GenGridController.e_BreakerMode <> eBreakerOperationMode.None;
data.b_ShowModeTransButton := monitor.system.GenGridController.b_ShowModeTrans;

(*monitor.system.GenGridController.b_ModeTransActive OR NOT monitor.system.GenGridController.b_ModeTransInhibit AND 
	monitor.system.GenGridController.e_BreakerMode <> eBreakerOperationMode.GenFeedthrough AND monitor.system.GenGridController.e_BreakerMode <> eBreakerOperationMode.none AND monitor.system.GenGridController.e_BreakerMode <> eBreakerOperationMode.GenIso;

*)
b_inputgenset := monitor.system.GenGridController.e_BreakerMode = eBreakerOperationMode.GenDroop OR
							monitor.system.GenGridController.e_BreakerMode = eBreakerOperationMode.GenFix OR
							monitor.system.GenGridController.e_BreakerMode = eBreakerOperationMode.GenIso;
data.b_ShowShowGensetInfo := b_inputgenset OR monitor.system.GenGridController.b_extGensetMode;
data.b_ShowGenManStartStop := NOT Monitor.controlfb.SoftSettings.inputgenset.b_AutoStartStop AND data.b_ShowShowGensetInfo OR monitor.system.GenGridController.e_GensetStartStop = eGensetstartstop.Start;
data.b_ShowExtgenset := NOT b_inputgenset AND monitor.controlfb.SoftSettings.setup.e_AcInputType <> eAcInputType.Genset;
data.b_ShowGensetHybridMode := monitor.system.GenGridController.e_BreakerMode = eBreakerOperationMode.GenIso AND NOT monitor.system.GenGridController.b_extGensetMode; ]]></ST>
      </Implementation>
    </Method>
    <Method Name="CopyActSettingsFromPLC" Id="{326a3b2c-f369-49e3-87db-495557214cc2}" FolderPath="ControlsHandlingMethods\">
      <Declaration><![CDATA[METHOD CopyActSettingsFromPLC : BOOL

VAR_IN_OUT
	init	: BOOL;
END_VAR

VAR
	udi_pointer		: POINTER TO ST_Softsettings;
	b_Onchange 		: BOOL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF init THEN
	controlvars.HardSettings := PLCpersistvars.Hardsettings;
	controlvars.SoftSettings := PLCpersistvars.Softsettings;
END_IF
]]></ST>
      </Implementation>
    </Method>
    <Method Name="DataToHMIArrayFormat" Id="{a405edf0-461d-4789-82bf-da80802179a8}" FolderPath="ArrayDataMethods\">
      <Declaration><![CDATA[METHOD PRIVATE DataToHMIArrayFormat
VAR_INPUT
	data								: ST_HMI_Monitor_ArrayDataFormat;
	init								: BOOL;
END_VAR

VAR_IN_OUT
	st_DataOut							: ST_HMIData;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[// first cycle only
IF init THEN
	st_DataOut.s_Type := data.s_Type;
	st_DataOut.s_Name := data.s_Name;
	IF data.i_precision <> -1 THEN
		st_DataOut.s_unit := data.s_unit;
	END_IF
	
END_IF


IF data.i_precision = -1 THEN
	st_DataOut.s_Data := data.s_unit;
ELSE
	st_DataOut.s_Data := LREAL_TO_FMTSTR(in:=data.r_Data, iprecision := data.i_precision, bRound := TRUE);
END_IF

IF data.b_warning <> st_DataOut.b_warning THEN
	st_DataOut.b_warning := data.b_warning;
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="GetAcInputArrayData" Id="{fb71ac2a-7058-4dff-8f7d-bb974837d144}" FolderPath="ArrayDataMethods\">
      <Declaration><![CDATA[METHOD GetAcInputArrayData : ST_HMI_Monitor_ArrayDataFormat
VAR_IN_OUT CONSTANT
	data : ST_Powermonitor_Inputfield;
END_VAR

VAR_INPUT
	id: INT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[CASE ID OF 
	1: 		GetAcInputArrayData.s_Name:= 'MCCB State';
			GetAcInputArrayData.s_Type:= 'Status';
			GetAcInputArrayData.s_unit:= TO_STRING(monitor.ACswitchgear.b_inputMCCBfb);
	2: 		GetAcInputArrayData.s_Name:= 'MCCB Shunt State';
			GetAcInputArrayData.s_Type:= 'Status';
			GetAcInputArrayData.s_unit:= TO_STRING(monitor.ACswitchgear.b_InputMCCBshuntOK);
	3:		GetAcInputArrayData.s_Name:= 'Apparent Power';
			GetAcInputArrayData.s_Type:= 'AC';
			GetAcInputArrayData.s_Unit:= 'kVA';
			GetAcInputArrayData.i_precision:= 0;
			GetAcInputArrayData.r_Data:= data.ar_ApparentPower[0];
	4:		GetAcInputArrayData.s_Name:= 'Active Power';
			GetAcInputArrayData.s_Type:= 'AC';
			GetAcInputArrayData.s_Unit:= 'kW';
			GetAcInputArrayData.i_precision:= 1;
			GetAcInputArrayData.r_Data:= data.ar_ActivePower[0];
	5:		GetAcInputArrayData.s_Name:= 'Reactive Power';
			GetAcInputArrayData.s_Type:= 'AC';
			GetAcInputArrayData.s_Unit:= 'kvar';
			GetAcInputArrayData.i_precision:= 1;
			GetAcInputArrayData.r_Data:= data.ar_ReactivePower[0];
	6:		GetAcInputArrayData.s_Name:= 'Current';
			GetAcInputArrayData.s_Type:= 'AC';
			GetAcInputArrayData.s_Unit:= 'A';
			GetAcInputArrayData.i_precision:= 1;
			GetAcInputArrayData.r_Data:= data.ar_Current[Phases.AVG];
	7:		GetAcInputArrayData.s_Name:= 'Line Voltage';
			GetAcInputArrayData.s_Type:= 'AC';
			GetAcInputArrayData.s_Unit:= 'VAC';
			GetAcInputArrayData.i_precision:= 1;
			GetAcInputArrayData.r_Data:= data.ar_LineVoltage[phases.AVG];
	8:		GetAcInputArrayData.s_Name:= 'Frequency';
			GetAcInputArrayData.s_Type:= 'AC';
			GetAcInputArrayData.s_Unit:= 'Hz';
			GetAcInputArrayData.i_precision:= 2;
			GetAcInputArrayData.r_Data:= data.ar_Frequency[0];
	9: 		GetAcInputArrayData.s_Name:= 'Power factor';
			GetAcInputArrayData.s_Type:= 'AC';
			GetAcInputArrayData.s_Unit:= '-';
			GetAcInputArrayData.i_precision:= 2;
			GetAcInputArrayData.r_Data:= data.ar_PowerFactor[phases.AVG];
	10:		GetAcInputArrayData.s_Name:= 'Voltage Unbalance';
			GetAcInputArrayData.s_Type:= 'AC';
			GetAcInputArrayData.s_Unit:= '%';
			GetAcInputArrayData.i_precision:= 1;
			GetAcInputArrayData.r_Data:= data.r_VoltageUnbalance;
	11:		GetAcInputArrayData.s_Name:= 'THD';
			GetAcInputArrayData.s_Type:= 'AC';
			GetAcInputArrayData.s_Unit:= '%';
			GetAcInputArrayData.i_precision:= 1;
			GetAcInputArrayData.r_Data:= data.ar_THD[phases.AVG];
	12:		GetAcInputArrayData.s_Name:= 'L1';
			GetAcInputArrayData.s_Type:= 'AC Current';
			GetAcInputArrayData.s_Unit:= 'A';
			GetAcInputArrayData.i_precision:= 1;
			GetAcInputArrayData.r_Data:= data.ar_Current[phases.L1];
	13:		GetAcInputArrayData.s_Name:= 'L2';
			GetAcInputArrayData.s_Type:= 'AC Current';
			GetAcInputArrayData.s_Unit:= 'A';
			GetAcInputArrayData.i_precision:= 1;
			GetAcInputArrayData.r_Data:= data.ar_Current[phases.L2];
	14:		GetAcInputArrayData.s_Name:= 'L3';
			GetAcInputArrayData.s_Type:= 'AC Current';
			GetAcInputArrayData.s_Unit:= 'A';
			GetAcInputArrayData.i_precision:= 1;
			GetAcInputArrayData.r_Data:= data.ar_Current[phases.L3];
	15:		GetAcInputArrayData.s_Name:= 'N';
			GetAcInputArrayData.s_Type:= 'AC Current';
			GetAcInputArrayData.s_Unit:= 'A';
			GetAcInputArrayData.i_precision:= 1;
			GetAcInputArrayData.r_Data:= data.ar_Current[phases.N];	
	16:		GetAcInputArrayData.s_Name:= 'L1-L2';
			GetAcInputArrayData.s_Type:= 'AC Linevoltage';
			GetAcInputArrayData.s_Unit:= 'VAC';
			GetAcInputArrayData.i_precision:= 1;
			GetAcInputArrayData.r_Data:= data.ar_LineVoltage[phases.L1];
	17:		GetAcInputArrayData.s_Name:= 'L2-L3';
			GetAcInputArrayData.s_Type:= 'AC Linevoltage';
			GetAcInputArrayData.s_Unit:= 'VAC';
			GetAcInputArrayData.i_precision:= 1;
			GetAcInputArrayData.r_Data:= data.ar_LineVoltage[phases.L2];
	18:		GetAcInputArrayData.s_Name:= 'L3-L1';
			GetAcInputArrayData.s_Type:= 'AC Linevoltage';
			GetAcInputArrayData.s_Unit:= 'VAC';
			GetAcInputArrayData.i_precision:= 1;
			GetAcInputArrayData.r_Data:= data.ar_LineVoltage[phases.L3];
	19:		GetAcInputArrayData.s_Name:= 'L1-N';
			GetAcInputArrayData.s_Type:= 'AC Phasevoltage';
			GetAcInputArrayData.s_Unit:= 'VAC';
			GetAcInputArrayData.i_precision:= 1;
			GetAcInputArrayData.r_Data:= data.ar_PhaseVoltage[phases.L1];	
	20:		GetAcInputArrayData.s_Name:= 'L2-N';
			GetAcInputArrayData.s_Type:= 'AC Phasevoltage';
			GetAcInputArrayData.s_Unit:= 'VAC';
			GetAcInputArrayData.i_precision:= 1;
			GetAcInputArrayData.r_Data:= data.ar_PhaseVoltage[phases.L2];
	21:		GetAcInputArrayData.s_Name:= 'L3-N';
			GetAcInputArrayData.s_Type:= 'AC Phasevoltage';
			GetAcInputArrayData.s_Unit:= 'VAC';
			GetAcInputArrayData.i_precision:= 1;
			GetAcInputArrayData.r_Data:= data.ar_PhaseVoltage[phases.L3];
	22: 	GetAcInputArrayData.s_Name:= 'Contactor state';
			GetAcInputArrayData.s_Type:= 'Status';
			GetAcInputArrayData.s_Unit:= TO_STRING(monitor.ACswitchgear.b_InputContactorfb);
	23: 	GetAcInputArrayData.s_Name:= 'Sync state';
			GetAcInputArrayData.s_Type:= 'Status';
			GetAcInputArrayData.s_Unit:= TO_STRING(monitor.ACswitchgear.b_InputSynchronizerfb);
	24: 	GetAcInputArrayData.s_Name:= 'L1';
			GetAcInputArrayData.s_Type:= 'AC Current 1';
			GetAcInputArrayData.s_Unit:= 'A';
			GetAcInputArrayData.i_precision:= 1;
			GetAcInputArrayData.b_warning := monitor.protections.OvercurrentProtection.Events.Input[1][phases.L1].b_warning;
			GetAcInputArrayData.r_Data:= data.powerlock[1].ar_Current[phases.L1];
	25: 	GetAcInputArrayData.s_Name:= 'L2';
			GetAcInputArrayData.s_Type:= 'AC Current 1';
			GetAcInputArrayData.s_Unit:= 'A';
			GetAcInputArrayData.i_precision:= 1;
			GetAcInputArrayData.b_warning := monitor.protections.OvercurrentProtection.Events.Input[1][phases.L2].b_warning;
			GetAcInputArrayData.r_Data:= data.powerlock[1].ar_Current[phases.L2];
	26: 	GetAcInputArrayData.s_Name:= 'L3';
			GetAcInputArrayData.s_Type:= 'AC Current 1';
			GetAcInputArrayData.s_Unit:= 'A';
			GetAcInputArrayData.i_precision:= 1;
			GetAcInputArrayData.b_warning := monitor.protections.OvercurrentProtection.Events.Input[1][phases.L3].b_warning;
			GetAcInputArrayData.r_Data:= data.powerlock[1].ar_Current[phases.L3];
	27: 	GetAcInputArrayData.s_Name:= 'N';
			GetAcInputArrayData.s_Type:= 'AC Current 1';
			GetAcInputArrayData.s_Unit:= 'A';
			GetAcInputArrayData.i_precision:= 1;
			GetAcInputArrayData.b_warning := monitor.protections.OvercurrentProtection.Events.Input[1][phases.N].b_warning;
			GetAcInputArrayData.r_Data:= data.powerlock[1].ar_Current[phases.N];
	28: 	GetAcInputArrayData.s_Name:= 'L1';
			GetAcInputArrayData.s_Type:= 'AC Current 2';
			GetAcInputArrayData.s_Unit:= 'A';
			GetAcInputArrayData.i_precision:= 1;
			GetAcInputArrayData.b_warning := monitor.protections.OvercurrentProtection.Events.Input[2][phases.L1].b_warning;
			GetAcInputArrayData.r_Data:= data.powerlock[2].ar_Current[phases.L1];
	29: 	GetAcInputArrayData.s_Name:= 'L2';
			GetAcInputArrayData.s_Type:= 'AC Current 2';
			GetAcInputArrayData.s_Unit:= 'A';
			GetAcInputArrayData.i_precision:= 1;
			GetAcInputArrayData.b_warning := monitor.protections.OvercurrentProtection.Events.Input[2][phases.L2].b_warning;
			GetAcInputArrayData.r_Data:= data.powerlock[2].ar_Current[phases.L2];
	30: 	GetAcInputArrayData.s_Name:= 'L3';
			GetAcInputArrayData.s_Type:= 'AC Current 2';
			GetAcInputArrayData.s_Unit:= 'A';
			GetAcInputArrayData.i_precision:= 1;
			GetAcInputArrayData.b_warning := monitor.protections.OvercurrentProtection.Events.Input[2][phases.L3].b_warning;
			GetAcInputArrayData.r_Data:= data.powerlock[2].ar_Current[phases.L3];
	31: 	GetAcInputArrayData.s_Name:= 'N';
			GetAcInputArrayData.s_Type:= 'AC Current 2';
			GetAcInputArrayData.s_Unit:= 'A';
			GetAcInputArrayData.i_precision:= 1;
			GetAcInputArrayData.b_warning := monitor.protections.OvercurrentProtection.Events.Input[2][phases.N].b_warning;
			GetAcInputArrayData.r_Data:= data.powerlock[2].ar_Current[phases.N];
	32: 	GetAcInputArrayData.s_Name:= 'Energy in';                 
			GetAcInputArrayData.s_Type:= 'Energy'; 
			GetAcInputArrayData.s_Unit:= 'kWh';                 
			GetAcInputArrayData.i_precision:= 1;
			GetAcInputArrayData.b_warning := data.r_EnergyConsumed < 0;              
			GetAcInputArrayData.r_Data:= data.r_EnergyConsumed;
	33: 	GetAcInputArrayData.s_Name:= 'Energy out';                 
			GetAcInputArrayData.s_Type:= 'Energy'; 
			GetAcInputArrayData.s_Unit:= 'kWh';                 
			GetAcInputArrayData.i_precision:= 1;
			GetAcInputArrayData.b_warning := data.r_EnergySupplied < 0;              
			GetAcInputArrayData.r_Data:= data.r_EnergySupplied;
	ELSE	
		RETURN;			
END_CASE
]]></ST>
      </Implementation>
    </Method>
    <Method Name="GetAcOutputArrayData" Id="{c030486a-4ccb-4aa0-a2f3-74a767b1f472}" FolderPath="ArrayDataMethods\">
      <Declaration><![CDATA[METHOD	GetAcOutputArrayData : ST_HMI_Monitor_ArrayDataFormat
VAR_IN_OUT CONSTANT
	data : ST_Powermonitor_Outputfield;
END_VAR

VAR_INPUT
	id: INT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[CASE ID OF 
	1: 		GetAcOutputArrayData.s_Name:= 'MCCB State';
			GetAcOutputArrayData.s_Type:= 'Status';
			GetAcOutputArrayData.s_Unit:= TO_STRING(monitor.ACswitchgear.b_outputMCCBfb);
	2: 		GetAcOutputArrayData.s_Name:= 'MCCB Shunt State';
			GetAcOutputArrayData.s_Type:= 'Status';
			GetAcOutputArrayData.s_Unit:= TO_STRING(monitor.ACswitchgear.b_outputMCCBshuntOK);
	3:		GetAcOutputArrayData.s_Name:= 'Apparent Power';
			GetAcOutputArrayData.s_Type:= 'AC';
			GetAcOutputArrayData.s_Unit:= 'kVA';
			GetAcOutputArrayData.i_precision:= 0;
			GetAcOutputArrayData.r_Data:= data.ar_ApparentPower[0];
	4:		GetAcOutputArrayData.s_Name:= 'Active Power';
			GetAcOutputArrayData.s_Type:= 'AC';
			GetAcOutputArrayData.s_Unit:= 'kW';
			GetAcOutputArrayData.i_precision:= 1;
			GetAcOutputArrayData.r_Data:= data.ar_ActivePower[0];
	5:		GetAcOutputArrayData.s_Name:= 'Reactive Power';
			GetAcOutputArrayData.s_Type:= 'AC';
			GetAcOutputArrayData.s_Unit:= 'kvar';
			GetAcOutputArrayData.i_precision:= 1;
			GetAcOutputArrayData.r_Data:= data.ar_ReactivePower[0];
	6:		GetAcOutputArrayData.s_Name:= 'Current';
			GetAcOutputArrayData.s_Type:= 'AC';
			GetAcOutputArrayData.s_Unit:= 'A';
			GetAcOutputArrayData.i_precision:= 1;
			GetAcOutputArrayData.r_Data:= data.ar_Current[Phases.AVG];
	7:		GetAcOutputArrayData.s_Name:= 'Line Voltage';
			GetAcOutputArrayData.s_Type:= 'AC';
			GetAcOutputArrayData.s_Unit:= 'VAC';
			GetAcOutputArrayData.i_precision:= 1;
			GetAcOutputArrayData.r_Data:= data.ar_LineVoltage[phases.AVG];
	8:		GetAcOutputArrayData.s_Name:= 'Frequency';
			GetAcOutputArrayData.s_Type:= 'AC';
			GetAcOutputArrayData.s_Unit:= 'Hz';
			GetAcOutputArrayData.i_precision:= 2;
			GetAcOutputArrayData.r_Data:= data.ar_Frequency[0];
	9: 		GetAcOutputArrayData.s_Name:= 'Power factor';
			GetAcOutputArrayData.s_Type:= 'AC';
			GetAcOutputArrayData.s_Unit:= '-';
			GetAcOutputArrayData.i_precision:= 2;
			GetAcOutputArrayData.r_Data:= data.ar_PowerFactor[phases.AVG];
	10:		GetAcOutputArrayData.s_Name:= 'Voltage Unbalance';
			GetAcOutputArrayData.s_Type:= 'AC';
			GetAcOutputArrayData.s_Unit:= '%';
			GetAcOutputArrayData.i_precision:= 1;
			GetAcOutputArrayData.r_Data:= data.r_VoltageUnbalance;
	11:		GetAcOutputArrayData.s_Name:= 'THD';
			GetAcOutputArrayData.s_Type:= 'AC';
			GetAcOutputArrayData.s_Unit:= '%';
			GetAcOutputArrayData.i_precision:= 1;
			GetAcOutputArrayData.r_Data:= data.ar_THD[phases.AVG];
	12:		GetAcOutputArrayData.s_Name:= 'L1';
			GetAcOutputArrayData.s_Type:= 'AC Current';
			GetAcOutputArrayData.s_Unit:= 'A';
			GetAcOutputArrayData.i_precision:= 1;
			GetAcOutputArrayData.r_Data:= monitor.powermonitor.outputfield.ar_Current[phases.L1];
	13:		GetAcOutputArrayData.s_Name:= 'L2';                            
			GetAcOutputArrayData.s_Type:= 'AC Current';                    
			GetAcOutputArrayData.s_Unit:= 'A';                            
			GetAcOutputArrayData.i_precision:= 1;                          
			GetAcOutputArrayData.r_Data:= monitor.powermonitor.outputfield.ar_Current[phases.L2];
	14:		GetAcOutputArrayData.s_Name:= 'L3';                            
			GetAcOutputArrayData.s_Type:= 'AC Current';                    
			GetAcOutputArrayData.s_Unit:= 'A';                             
			GetAcOutputArrayData.i_precision:= 1;                          
			GetAcOutputArrayData.r_Data:= monitor.powermonitor.outputfield.ar_Current[phases.L3];
	15:		GetAcOutputArrayData.s_Name:= 'N';                             
			GetAcOutputArrayData.s_Type:= 'AC Current';                    
			GetAcOutputArrayData.s_Unit:= 'A';                            
			GetAcOutputArrayData.i_precision:= 1;                          
			GetAcOutputArrayData.r_Data:= data.ar_Current[phases.N];	
	16:		GetAcOutputArrayData.s_Name:= 'L1-L2';
			GetAcOutputArrayData.s_Type:= 'AC Linevoltage';
			GetAcOutputArrayData.s_Unit:= 'VAC';
			GetAcOutputArrayData.i_precision:= 1;
			GetAcOutputArrayData.r_Data:= data.ar_LineVoltage[phases.L1];
	17:		GetAcOutputArrayData.s_Name:= 'L2-L3';
			GetAcOutputArrayData.s_Type:= 'AC Linevoltage';
			GetAcOutputArrayData.s_Unit:= 'VAC';
			GetAcOutputArrayData.i_precision:= 1;
			GetAcOutputArrayData.r_Data:= data.ar_LineVoltage[phases.L2];
	18:		GetAcOutputArrayData.s_Name:= 'L3-L1';
			GetAcOutputArrayData.s_Type:= 'AC Linevoltage';
			GetAcOutputArrayData.s_Unit:= 'VAC';
			GetAcOutputArrayData.i_precision:= 1;
			GetAcOutputArrayData.r_Data:= data.ar_LineVoltage[phases.L3];
	19:		GetAcOutputArrayData.s_Name:= 'L1-N';
			GetAcOutputArrayData.s_Type:= 'AC Phasevoltage';
			GetAcOutputArrayData.s_Unit:= 'VAC';
			GetAcOutputArrayData.i_precision:= 1;
			GetAcOutputArrayData.r_Data:= data.ar_PhaseVoltage[phases.L1];	
	20:		GetAcOutputArrayData.s_Name:= 'L2-N';
			GetAcOutputArrayData.s_Type:= 'AC Phasevoltage';
			GetAcOutputArrayData.s_Unit:= 'VAC';
			GetAcOutputArrayData.i_precision:= 1;
			GetAcOutputArrayData.r_Data:= data.ar_PhaseVoltage[phases.L2];
	21:		GetAcOutputArrayData.s_Name:= 'L3-N';
			GetAcOutputArrayData.s_Type:= 'AC Phasevoltage';
			GetAcOutputArrayData.s_Unit:= 'VAC';
			GetAcOutputArrayData.i_precision:= 1;
			GetAcOutputArrayData.r_Data:= data.ar_PhaseVoltage[phases.L3];					
	22: 	GetAcOutputArrayData.s_Name:= 'L1';
			GetAcOutputArrayData.s_Type:= 'AC Current 1';
			GetAcOutputArrayData.s_Unit:= 'A';
			GetAcOutputArrayData.i_precision:= 1;
			GetAcOutputArrayData.b_warning := monitor.protections.OvercurrentProtection.Events.Output[1][phases.L1].b_warning;
			GetAcOutputArrayData.r_Data:=  data.powerlock[1].ar_Current[phases.L1];
	23: 	GetAcOutputArrayData.s_Name:= 'L2';                
			GetAcOutputArrayData.s_Type:= 'AC Current 1'; 
			GetAcOutputArrayData.s_Unit:= 'A';                 
			GetAcOutputArrayData.i_precision:= 1;
			GetAcOutputArrayData.b_warning := monitor.protections.OvercurrentProtection.Events.Output[1][phases.L2].b_warning;              
			GetAcOutputArrayData.r_Data:= data.powerlock[1].ar_Current[phases.L2];
	24: 	GetAcOutputArrayData.s_Name:= 'L3';                
			GetAcOutputArrayData.s_Type:= 'AC Current 1'; 
			GetAcOutputArrayData.s_Unit:= 'A';                 
			GetAcOutputArrayData.i_precision:= 1;
			GetAcOutputArrayData.b_warning := monitor.protections.OvercurrentProtection.Events.Output[1][phases.L3].b_warning;              
			GetAcOutputArrayData.r_Data:=  data.powerlock[1].ar_Current[phases.L3];
	25: 	GetAcOutputArrayData.s_Name:= 'N';                 
			GetAcOutputArrayData.s_Type:= 'AC Current 1'; 
			GetAcOutputArrayData.s_Unit:= 'A';                 
			GetAcOutputArrayData.i_precision:= 1;
			GetAcOutputArrayData.b_warning := monitor.protections.OvercurrentProtection.Events.Output[1][phases.N].b_warning;              
			GetAcOutputArrayData.r_Data:= data.powerlock[1].ar_Current[phases.N];
	26: 	GetAcOutputArrayData.s_Name:= 'L1';
			GetAcOutputArrayData.s_Type:= 'AC Current 2';
			GetAcOutputArrayData.s_Unit:= 'A';
			GetAcOutputArrayData.i_precision:= 1;
			GetAcOutputArrayData.b_warning := monitor.protections.OvercurrentProtection.Events.Output[2][phases.L1].b_warning;
			GetAcOutputArrayData.r_Data:=  data.powerlock[2].ar_Current[phases.L1];
	27: 	GetAcOutputArrayData.s_Name:= 'L2';                
			GetAcOutputArrayData.s_Type:= 'AC Current 2'; 
			GetAcOutputArrayData.s_Unit:= 'A';                 
			GetAcOutputArrayData.i_precision:= 1; 
			GetAcOutputArrayData.b_warning := monitor.protections.OvercurrentProtection.Events.Output[2][phases.L2].b_warning;             
			GetAcOutputArrayData.r_Data:=  data.powerlock[2].ar_Current[phases.L2];
	28: 	GetAcOutputArrayData.s_Name:= 'L3';                
			GetAcOutputArrayData.s_Type:= 'AC Current 2'; 
			GetAcOutputArrayData.s_Unit:= 'A';                 
			GetAcOutputArrayData.i_precision:= 1;
			GetAcOutputArrayData.b_warning := monitor.protections.OvercurrentProtection.Events.Output[2][phases.L3].b_warning;              
			GetAcOutputArrayData.r_Data:=  data.powerlock[2].ar_Current[phases.L3];
	29: 	GetAcOutputArrayData.s_Name:= 'N';                 
			GetAcOutputArrayData.s_Type:= 'AC Current 2'; 
			GetAcOutputArrayData.s_Unit:= 'A';                 
			GetAcOutputArrayData.i_precision:= 1;
			GetAcOutputArrayData.b_warning := monitor.protections.OvercurrentProtection.Events.Output[2][phases.N].b_warning;              
			GetAcOutputArrayData.r_Data:=  data.powerlock[2].ar_Current[phases.N];
	30: 	GetAcOutputArrayData.s_Name:= 'L1';
			GetAcOutputArrayData.s_Type:= 'AC Current 3';
			GetAcOutputArrayData.s_Unit:= 'A';
			GetAcOutputArrayData.i_precision:= 1;
			GetAcOutputArrayData.b_warning := monitor.protections.OvercurrentProtection.Events.Output[3][phases.L1].b_warning;
			GetAcOutputArrayData.r_Data:=   data.powerlock[3].ar_Current[phases.L1];
	31: 	GetAcOutputArrayData.s_Name:= 'L2';                
			GetAcOutputArrayData.s_Type:= 'AC Current 3'; 
			GetAcOutputArrayData.s_Unit:= 'A';                 
			GetAcOutputArrayData.i_precision:= 1;     
			GetAcOutputArrayData.b_warning := monitor.protections.OvercurrentProtection.Events.Output[3][phases.L2].b_warning;         
			GetAcOutputArrayData.r_Data:=  data.powerlock[3].ar_Current[phases.L2];
	32: 	GetAcOutputArrayData.s_Name:= 'L3';                
			GetAcOutputArrayData.s_Type:= 'AC Current 3'; 
			GetAcOutputArrayData.s_Unit:= 'A';                 
			GetAcOutputArrayData.i_precision:= 1;    
			GetAcOutputArrayData.b_warning := monitor.protections.OvercurrentProtection.Events.Output[3][phases.L3].b_warning;          
			GetAcOutputArrayData.r_Data:=  data.powerlock[3].ar_Current[phases.L3];
	33: 	GetAcOutputArrayData.s_Name:= 'N';                 
			GetAcOutputArrayData.s_Type:= 'AC Current 3'; 
			GetAcOutputArrayData.s_Unit:= 'A';                 
			GetAcOutputArrayData.i_precision:= 1;
			GetAcOutputArrayData.b_warning := monitor.protections.OvercurrentProtection.Events.Output[3][phases.N].b_warning;              
			GetAcOutputArrayData.r_Data:= data.powerlock[3].ar_Current[phases.N];
	34:		GetAcOutputArrayData.s_Name:= 'Rotation field';
			GetAcOutputArrayData.s_Type:= 'AC';
			GetAcOutputArrayData.s_Unit:= TO_STRING(data.e_ACrotationStatus);
	35: 	GetAcOutputArrayData.s_Name:= 'Energy in';                 
			GetAcOutputArrayData.s_Type:= 'Energy'; 
			GetAcOutputArrayData.s_Unit:= 'kWh';                 
			GetAcOutputArrayData.i_precision:= 1;
			GetAcOutputArrayData.b_warning := data.r_EnergyConsumed < 0;              
			GetAcOutputArrayData.r_Data:= data.r_EnergyConsumed;
	36: 	GetAcOutputArrayData.s_Name:= 'Energy out';                 
			GetAcOutputArrayData.s_Type:= 'Energy'; 
			GetAcOutputArrayData.s_Unit:= 'kWh';                 
			GetAcOutputArrayData.i_precision:= 1;
			GetAcOutputArrayData.b_warning := data.r_EnergySupplied < 0;              
			GetAcOutputArrayData.r_Data:= data.r_EnergySupplied;
ELSE	
		RETURN;
END_CASE
]]></ST>
      </Implementation>
    </Method>
    <Method Name="GetActiveTimeSlotScheduler" Id="{c40a78b0-a172-4c0a-8e39-5cb8d688ec4d}" FolderPath="SchedulerMethods\">
      <Declaration><![CDATA[METHOD GetActiveTimeSlotScheduler
VAR_INPUT
	enable			: BOOL;
END_VAR

VAR_IN_OUT
	timeslot1 : ST_scheduleTimeslot;
	timeslot2 : ST_scheduleTimeslot;
END_VAR

VAR
	w_targetToW1 : WORD; //time of week
	w_targetToW2 : WORD;
	w_CurrentToW : WORD;
	w_CurrentDoW : WORD; 
	w_CurrentToD : WORD; // in minutes\
END_VAR

VAR
	w_MillisInMinute: WORD := 60000;
	w_MinutesInHour	: WORD := 60;
	w_MinutesInDay	: WORD := w_MinutesInHour * 24;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF enable THEN
	//enable weekly evaluation
	IF timeslot1.usi_DayOfWeek = 0 THEN
		w_CurrentDoW := 0;
		timeslot2.usi_DayOfWeek := 0;
	ELSE
		w_CurrentDoW := F_GetDayOfWeek(IN:=GVL.dt_SystemDateTime);
	END_IF

	w_CurrentToD := TO_WORD(TO_DWORD(TO_TOD(GVL.dt_SystemDateTime))/w_MillisInMinute);
	w_CurrentToW := w_CurrentToD + w_CurrentDoW * w_MinutesInDay;
	w_targetToW1 := Hour_Minute_To_TOW(timeslot1.usi_DayOfWeek,timeslot1.usi_HourOfDay, timeslot1.usi_MinuteOfHour);
	w_targetToW2 := Hour_Minute_To_TOW(timeslot2.usi_DayOfWeek,timeslot2.usi_HourOfDay, timeslot2.usi_MinuteOfHour);
	
	IF w_targetToW1 < w_targetToW2 THEN
		Timeslot1.b_active := w_CurrentToW >= w_targetToW1 AND w_CurrentToW < w_targetToW2;
		Timeslot2.b_active := NOT timeslot1.b_active;
	ELSE
		Timeslot2.b_active := w_CurrentToW >= w_targetToW2 AND w_CurrentToW < w_targetToW1;
		Timeslot1.b_active := NOT timeslot2.b_active;
	END_IF	
ELSE
	Timeslot2.b_active := FALSE;
	Timeslot1.b_active := TRUE;
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="GetCoolingData" Id="{2d57157c-057a-44c2-b8b2-465df3409131}" FolderPath="ArrayDataMethods\">
      <Declaration><![CDATA[METHOD GetCoolingData : ST_HMI_Monitor_ArrayDataFormat
VAR_IN_OUT CONSTANT
	data			: ST_CoolingSystem_get;
END_VAR

VAR_INPUT
	id: INT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[CASE ID OF 
	1: 		GetCoolingData.s_Name:= 'Mode';
			GetCoolingData.s_Type:= 'status';
			GetCoolingData.s_unit:= TO_STRING(data.CoolingSystemMode);
	2: 		GetCoolingData.s_Name:= 'Heatpump status';
			GetCoolingData.s_Type:= 'status';
			GetCoolingData.s_unit:= TO_STRING(data.HeatPumpStatus);
	3: 		GetCoolingData.s_Name:= 'Coolant pressure';
			GetCoolingData.s_Type:= 'measure';
			GetCoolingData.s_Unit:= 'bar';
			GetCoolingData.i_precision:= 2;
			GetCoolingData.r_data:= data.r_CoolantPressure;
	4: 		GetCoolingData.s_Name:= 'Coolant temperature';
			GetCoolingData.s_Type:= 'measure';
			GetCoolingData.s_Unit:= '°C';
			GetCoolingData.i_precision:= 1;
			GetCoolingData.r_data:= data.r_CoolantTemperature;
	5:		GetCoolingData.s_Name:= 'Enclosure Dewpoint';
			GetCoolingData.s_Type:= 'measure';
			GetCoolingData.s_Unit:= '°C';
			GetCoolingData.i_precision:= 1;
			GetCoolingData.r_Data:= data.r_EnclosureDewpoint;
	ELSE	
		RETURN;			
END_CASE]]></ST>
      </Implementation>
    </Method>
    <Method Name="GetDcChargerData" Id="{351512b6-361a-43ad-b595-ecec3b612c82}" FolderPath="ArrayDataMethods\">
      <Declaration><![CDATA[METHOD GetDcChargerData : ST_HMI_Monitor_ArrayDataFormat
VAR_IN_OUT CONSTANT
	data : ST_AcDcCharger_get;
END_VAR

VAR_INPUT
	id: INT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[CASE ID OF 
	1: 		GetDcChargerData.s_Name:= 'State';
			GetDcChargerData.s_Type:= 'Status';
			GetDcChargerData.s_unit:= TO_STRING(data.e_SystemStatus);
	2:		GetDcChargerData.s_Name:= 'Line Voltage';
			GetDcChargerData.s_Type:= 'AC';
			GetDcChargerData.s_Unit:= 'Vac';
			GetDcChargerData.i_precision:= 1;
			GetDcChargerData.r_Data:= data.ar_ACvoltage[0];
	3:		GetDcChargerData.s_Name:= 'Active Power';
			GetDcChargerData.s_Type:= 'AC';
			GetDcChargerData.s_Unit:= 'kW';
			GetDcChargerData.i_precision:= 1;
			GetDcChargerData.r_Data:= data.ACmeasurements.ar_ActivePower[0];
	4:		GetDcChargerData.s_Name:= 'Current';
			GetDcChargerData.s_Type:= 'AC';
			GetDcChargerData.s_Unit:= 'A';
			GetDcChargerData.i_precision:= 1;
			GetDcChargerData.r_Data:= data.ACmeasurements.ar_Current[0];
	5:		GetDcChargerData.s_Name:= 'Power';
			GetDcChargerData.s_Type:= 'DC';
			GetDcChargerData.s_Unit:= 'kW';
			GetDcChargerData.i_precision:= 1;
			GetDcChargerData.r_Data:= data.r_DcPower;
	6:		GetDcChargerData.s_Name:= 'Voltage';
			GetDcChargerData.s_Type:= 'DC';
			GetDcChargerData.s_Unit:= 'Vdc';
			GetDcChargerData.i_precision:= 1;
			GetDcChargerData.r_Data:= data.r_DcVoltage;
	7:		GetDcChargerData.s_Name:= 'Current';
			GetDcChargerData.s_Type:= 'DC';
			GetDcChargerData.s_Unit:= 'A';
			GetDcChargerData.i_precision:= 1;
			GetDcChargerData.r_Data:= data.r_DcCurrent;
	8:		GetDcChargerData.s_Name:= 'L1';
			GetDcChargerData.s_Type:= 'P';
			GetDcChargerData.s_Unit:= 'kW';
			GetDcChargerData.i_precision:= 1;
			GetDcChargerData.r_Data:= data.ACmeasurements.ar_ActivePower[phases.L1];
	9:		GetDcChargerData.s_Name:= 'L2';
			GetDcChargerData.s_Type:= 'P';
			GetDcChargerData.s_Unit:= 'kW';
			GetDcChargerData.i_precision:= 1;
			GetDcChargerData.r_Data:= data.ACmeasurements.ar_ActivePower[phases.L2];
	10:		GetDcChargerData.s_Name:= 'L3';
			GetDcChargerData.s_Type:= 'P';
			GetDcChargerData.s_Unit:= 'kW';
			GetDcChargerData.i_precision:= 1;
			GetDcChargerData.r_Data:= data.ACmeasurements.ar_ActivePower[phases.L3];
	11:		GetDcChargerData.s_Name:= 'L1';
			GetDcChargerData.s_Type:= 'Linevoltage';
			GetDcChargerData.s_Unit:= 'Vac';
			GetDcChargerData.i_precision:= 1;
			GetDcChargerData.r_Data:= data.ar_ACvoltage[phases.L1];
	12: 	GetDcChargerData.s_Name:= 'L2';                        
			GetDcChargerData.s_Type:= 'Linevoltage';              
			GetDcChargerData.s_Unit:= 'Vac';                       
			GetDcChargerData.i_precision:= 1;                      
			GetDcChargerData.r_Data:= data.ar_ACvoltage[phases.L2];
	13:		GetDcChargerData.s_Name:= 'L3';                        
			GetDcChargerData.s_Type:= 'Linevoltage';              
			GetDcChargerData.s_Unit:= 'Vac';                       
			GetDcChargerData.i_precision:= 1;                      
			GetDcChargerData.r_Data:= data.ar_ACvoltage[phases.L3];
	ELSE	
		RETURN;			
END_CASE
]]></ST>
      </Implementation>
    </Method>
    <Method Name="GetDcExtData" Id="{d1a8d8de-221f-45ea-a409-c9e3e6332361}" FolderPath="ArrayDataMethods\">
      <Declaration><![CDATA[METHOD GetDcExtData : ST_HMI_Monitor_ArrayDataFormat
VAR_IN_OUT CONSTANT
	data : ST_DCswitchgear_get;
END_VAR

VAR_INPUT
	id: INT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[CASE ID OF 
	1: 		GetDcExtData.s_Name:= 'State';
			GetDcExtData.s_Type:= 'Status';
			GetDcExtData.s_unit:= SEL(data.b_CouplingState, 'Disconnected', 'Connected');
	2:		GetDcExtData.s_Name:= 'Power';
			GetDcExtData.s_Type:= 'DC';
			GetDcExtData.s_Unit:= 'kW';
			GetDcExtData.i_precision:= 1;
			GetDcExtData.r_Data:= data.r_Power;
	3:		GetDcExtData.s_Name:= 'Voltage';
			GetDcExtData.s_Type:= 'DC';
			GetDcExtData.s_Unit:= 'Vdc';
			GetDcExtData.i_precision:= 1;
			GetDcExtData.r_Data:= data.r_Voltage;
	4:		GetDcExtData.s_Name:= 'Current';
			GetDcExtData.s_Type:= 'DC';
			GetDcExtData.s_Unit:= 'A';
			GetDcExtData.i_precision:= 1;
			GetDcExtData.r_Data:= data.r_Current;
	ELSE	
		RETURN;			
END_CASE
]]></ST>
      </Implementation>
    </Method>
    <Method Name="GetextcontrolData" Id="{edbeba57-aa21-4dbb-962f-3598133f7234}" FolderPath="ArrayDataMethods\">
      <Declaration><![CDATA[METHOD GetextcontrolData : ST_HMI_Monitor_ArrayDataFormat
VAR_IN_OUT CONSTANT
	data : ST_ExtController_get;
END_VAR


VAR_INPUT
	id: INT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[CASE ID OF 
	1: 		GetextcontrolData.s_Name:= 'Start';
			GetextcontrolData.s_Type:= 'general';
			GetextcontrolData.s_unit:= TO_STRING(data.control.b_start);
	2: 		GetextcontrolData.s_Name:= 'Shutdown';
			GetextcontrolData.s_Type:= 'general';
			GetextcontrolData.s_unit:= TO_STRING(data.control.b_shutdown);		
	3: 		GetextcontrolData.s_Name:= 'Emstop';
			GetextcontrolData.s_Type:= 'general';
			GetextcontrolData.s_unit:= TO_STRING(data.control.b_EMstop);
	4: 		GetextcontrolData.s_Name:= 'Reset';
			GetextcontrolData.s_Type:= 'general';
			GetextcontrolData.s_unit:= TO_STRING(data.control.b_reset);
	5: 		GetextcontrolData.s_Name:= 'Activate settings';
			GetextcontrolData.s_Type:= 'general';
			GetextcontrolData.s_unit:= TO_STRING(data.control.b_ActivateSettings);
	6: 		GetextcontrolData.s_Name:= 'Automatic switching';
			GetextcontrolData.s_Type:= 'general';
			GetextcontrolData.s_unit:= TO_STRING(data.SoftSettings.system.b_AutomaticSwitching);
	7:		GetextcontrolData.s_Name:= 'Condition mode';
			GetextcontrolData.s_Type:= 'general';
			GetextcontrolData.s_Unit:= TO_STRING(data.SoftSettings.system.b_EnableTransportMode);
	8:		GetextcontrolData.s_Name:= 'Start Dehumid';
			GetextcontrolData.s_Type:= 'general';
			GetextcontrolData.s_Unit:= TO_STRING(data.control.b_startDeHum);
	9:		GetextcontrolData.s_Name:= 'SOC min';
			GetextcontrolData.s_Type:= 'battery';
			GetextcontrolData.s_Unit:= '%';
			GetextcontrolData.i_precision:= 0;
			GetextcontrolData.r_Data:= data.SoftSettings.system.r_SocMin;
			GetextcontrolData.b_warning:= data.events.b_SoCLowLimitOutOfRange;
	10:		GetextcontrolData.s_Name:= 'SOC max';
			GetextcontrolData.s_Type:= 'battery';
			GetextcontrolData.s_Unit:= '%';
			GetextcontrolData.i_precision:= 0;
			GetextcontrolData.r_Data:= data.SoftSettings.system.r_SocMax;
			GetextcontrolData.b_warning:= data.events.b_SoCHighLimitOutOfRange;
	11: 	GetextcontrolData.s_Name:= 'PFset enable';
			GetextcontrolData.s_Type:= 'powerstack';
			GetextcontrolData.s_Unit:= TO_STRING(data.operation.system.b_PFsetEnable);
	13: 	GetextcontrolData.s_Name:= 'Reserved';
			GetextcontrolData.s_Type:= 'powerstack';
			GetextcontrolData.s_Unit:= '-';
	14: 	GetextcontrolData.s_Name:= 'Gridmode';
			GetextcontrolData.s_Type:= 'general';
			GetextcontrolData.b_warning := data.events.b_GridModeValueOutOfRange;
			GetextcontrolData.s_Unit:= TO_STRING(data.SoftSettings.setup.e_Gridmode);
	15: 	GetextcontrolData.s_Name:= 'Powermode';
			GetextcontrolData.s_Type:= 'general';
			GetextcontrolData.b_warning := data.events.b_PowerModeValueOutOfRange;
			GetextcontrolData.s_Unit:= TO_STRING(data.SoftSettings.system.e_UgridPowerMode);
	16:		GetextcontrolData.s_Name:= 'Pset';
			GetextcontrolData.s_Type:= 'powerstack';
			GetextcontrolData.s_Unit:= 'kW';
			GetextcontrolData.i_precision:= 1;
			GetextcontrolData.b_warning := data.events.b_PsetOutOfRange;
			GetextcontrolData.r_Data:= data.Operation.system.r_Pset;
	17:		GetextcontrolData.s_Name:= 'Qset';
			GetextcontrolData.s_Type:= 'powerstack';
			GetextcontrolData.s_Unit:= 'kvar';
			GetextcontrolData.i_precision:= 1;
			GetextcontrolData.b_warning := data.events.b_QsetOutOfRange;
			GetextcontrolData.r_Data:= data.Operation.system.r_Qset;
	18:		GetextcontrolData.s_Name:= 'PFset';
			GetextcontrolData.s_Type:= 'powerstack';
			GetextcontrolData.s_Unit:= '-';
			GetextcontrolData.i_precision:= 2;
			GetextcontrolData.b_warning := data.events.b_PFsetOutOfRange;
			GetextcontrolData.r_Data:= data.Operation.system.r_PFset;
	19:		GetextcontrolData.s_Name:= 'Nom voltage';
			GetextcontrolData.s_Type:= 'powerstack';
			GetextcontrolData.s_Unit:= 'VAC';
			GetextcontrolData.i_precision:= 0;
			GetextcontrolData.b_warning := data.events.b_NominalVoltageOutOfRange;
			GetextcontrolData.r_Data:= data.Operation.system.r_NominalVoltage;
	20:		GetextcontrolData.s_Name:= 'Nom frequency';
			GetextcontrolData.s_Type:= 'powerstack';
			GetextcontrolData.s_Unit:= 'Hz';
			GetextcontrolData.i_precision:= 2;
			GetextcontrolData.b_warning := data.events.b_NominalFreqOutOfRange;
			GetextcontrolData.r_Data:= data.Operation.system.r_NominalFrequency;
	21:		GetextcontrolData.s_Name:= 'Voltage droop';
			GetextcontrolData.s_Type:= 'powerstack';
			GetextcontrolData.s_Unit:= '%';
			GetextcontrolData.i_precision:= 1;
			GetextcontrolData.b_warning := data.events.b_VoltageDroopOutOfRange;
			GetextcontrolData.r_Data:= data.Softsettings.system.r_VoltageDroop;
	22:		GetextcontrolData.s_Name:= 'Frequency droop';
			GetextcontrolData.s_Type:= 'powerstack';
			GetextcontrolData.s_Unit:= '%';
			GetextcontrolData.i_precision:= 1;
			GetextcontrolData.b_warning := data.events.b_FreqDroopOutOfRange;
			GetextcontrolData.r_Data:= data.Softsettings.system.r_FrequencyDroop;
	23:		GetextcontrolData.s_Name:= 'P max';
			GetextcontrolData.s_Type:= 'powerstack';
			GetextcontrolData.s_Unit:= 'kW';
			GetextcontrolData.i_precision:= 1;
			GetextcontrolData.b_warning := data.events.b_PmaxOutOfRange;
			GetextcontrolData.r_Data:= data.Softsettings.system.r_PDischargeLimit;
	24:		GetextcontrolData.s_Name:= 'P min';
			GetextcontrolData.s_Type:= 'powerstack';
			GetextcontrolData.s_Unit:= 'kW';
			GetextcontrolData.i_precision:= 1;
			GetextcontrolData.b_warning := data.events.b_PminOutOfRange;
			GetextcontrolData.r_Data:= data.Softsettings.system.r_PChargeLimit;
	26:		GetextcontrolData.s_Name:= 'AC current limit';
			GetextcontrolData.s_Type:= 'powerstack';
			GetextcontrolData.s_Unit:= 'kvar';
			GetextcontrolData.i_precision:= 1;
			GetextcontrolData.b_warning := data.events.b_AmaxOutOfRange;
			GetextcontrolData.r_Data:= data.Softsettings.system.r_Amax;
	28:		GetextcontrolData.s_Name:= 'Feedin current limit';
			GetextcontrolData.s_Type:= 'PSB';
			GetextcontrolData.s_Unit:= 'A';
			GetextcontrolData.i_precision:= 0;
			GetextcontrolData.b_warning := data.events.b_PSBFeedInLimitOutOfRange;
			GetextcontrolData.r_Data:= data.Softsettings.PSB.setpointTimeslot1.r_FeedInCurrentLimitSoft;
	29:		GetextcontrolData.s_Name:= 'Supply current limit';
			GetextcontrolData.s_Type:= 'PSB';
			GetextcontrolData.s_Unit:= 'A';
			GetextcontrolData.i_precision:= 0;
			GetextcontrolData.b_warning := data.events.b_PSBSupplyLimitOutOfRange;
			GetextcontrolData.r_Data:= data.Softsettings.PSB.setpointTimeslot1.r_SupplyCurrentLimitSoft;
	30:		GetextcontrolData.s_Name:= 'Idle charge power';
			GetextcontrolData.s_Type:= 'PSB';
			GetextcontrolData.s_Unit:= 'kW';
			GetextcontrolData.i_precision:= 1;
			GetextcontrolData.b_warning := data.events.b_PSBIdleChargePowerOutOfRange;
			GetextcontrolData.r_Data:= data.Softsettings.PSB.setpointTimeslot1.r_IdleChargePower;
	31:		GetextcontrolData.s_Name:= 'SOC target';
			GetextcontrolData.s_Type:= 'PSB';
			GetextcontrolData.s_Unit:= '%';
			GetextcontrolData.i_precision:= 0;
			GetextcontrolData.b_warning := data.events.b_PSBSocTargetOutOfRange;
			GetextcontrolData.r_Data:= data.Softsettings.PSB.setpointTimeslot1.r_SocTarget;
	32:		GetextcontrolData.s_Name:= 'Feedin current limit';
			GetextcontrolData.s_Type:= 'input';
			GetextcontrolData.s_Unit:= 'A';
			GetextcontrolData.i_precision:= 0;
			GetextcontrolData.b_warning := data.events.b_FeedInLimitOutOfRange;
			GetextcontrolData.r_Data:= data.Softsettings.inputgrid.setpointTimeslot1.r_FeedInCurrentLimitSoft;
	33:		GetextcontrolData.s_Name:= 'Supply current limit';
			GetextcontrolData.s_Type:= 'input';
			GetextcontrolData.s_Unit:= 'A';
			GetextcontrolData.i_precision:= 0;
			GetextcontrolData.b_warning := data.events.b_SupplyLimitOutOfRange;
			GetextcontrolData.r_Data:= data.Softsettings.inputgrid.setpointTimeslot1.r_SupplyCurrentLimitSoft;
	34:		GetextcontrolData.s_Name:= 'Idle charge power';
			GetextcontrolData.s_Type:= 'input';
			GetextcontrolData.s_Unit:= 'kW';
			GetextcontrolData.i_precision:= 1;
			GetextcontrolData.b_warning := data.events.b_IdleChargePowerOutOfRange;
			GetextcontrolData.r_Data:= data.Softsettings.inputgrid.setpointTimeslot1.r_IdleChargePower;
	35:		GetextcontrolData.s_Name:= 'SOC target';
			GetextcontrolData.s_Type:= 'input';
			GetextcontrolData.s_Unit:= '%';
			GetextcontrolData.i_precision:= 0;
			GetextcontrolData.b_warning := data.events.b_SocTargetOutOfRange;
			GetextcontrolData.r_Data:= data.Softsettings.inputgrid.setpointTimeslot1.r_SocTarget;
	36:		GetextcontrolData.s_Name:= 'AMF';
			GetextcontrolData.s_Type:= 'general';
			GetextcontrolData.s_Unit:= TO_STRING(data.SoftSettings.system.b_AMF);
	37:		GetextcontrolData.s_Name:= 'Contactor Syncclose';
			GetextcontrolData.s_Type:= 'input';
			GetextcontrolData.s_Unit:= TO_STRING(data.Operation.inputgrid.b_SyncClose);
	39:		GetextcontrolData.s_Name:= 'SOC start';
			GetextcontrolData.s_Type:= 'input';
			GetextcontrolData.s_Unit:= '%';
			GetextcontrolData.i_precision:= 0;
			GetextcontrolData.b_warning := data.events.b_SocStartOutOfRange;
			GetextcontrolData.r_Data:= data.Softsettings.inputgenset.setpointTimeslot1.r_SoCStart;
	40:		GetextcontrolData.s_Name:= 'SOC stop';
			GetextcontrolData.s_Type:= 'input';
			GetextcontrolData.s_Unit:= '%';
			GetextcontrolData.i_precision:= 0;
			GetextcontrolData.b_warning := data.events.b_SocStopOutOfRange;
			GetextcontrolData.r_Data:= data.Softsettings.inputgenset.setpointTimeslot1.r_SoCStop;
	41:		GetextcontrolData.s_Name:= 'Overload start';
			GetextcontrolData.s_Type:= 'input';
			GetextcontrolData.s_Unit:= '%';
			GetextcontrolData.i_precision:= 0;
			GetextcontrolData.b_warning := data.events.b_BatOloadStartOutOfRange;
			GetextcontrolData.r_Data:= data.Softsettings.inputgenset.setpointTimeslot1.r_BatteryloadStart;
	42:		GetextcontrolData.s_Name:= 'Overload stop';
			GetextcontrolData.s_Type:= 'input';
			GetextcontrolData.s_Unit:= '%';
			GetextcontrolData.i_precision:= 0;
			GetextcontrolData.b_warning := data.events.b_BatOloadStopOutOfRange;
			GetextcontrolData.r_Data:= data.Softsettings.inputgenset.setpointTimeslot1.r_BatteryloadStop;
	43:		GetextcontrolData.s_Name:= 'Manual start';
			GetextcontrolData.s_Type:= 'input';
			GetextcontrolData.s_Unit:= TO_STRING(data.Operation.genset.b_ManualStart);
	44: 	GetextcontrolData.s_Name:= 'Heartbeat';
			GetextcontrolData.s_Type:= 'general';
			GetextcontrolData.s_unit:= TO_STRING(data.ui_Heartbeat);
			GetextControldata.b_warning := data.events.b_HeartbeatFault;
	ELSE	
		RETURN;			
END_CASE
]]></ST>
      </Implementation>
    </Method>
    <Method Name="GetGensetData" Id="{af790907-67b8-4856-92d6-1efbb0af637e}" FolderPath="ArrayDataMethods\">
      <Declaration><![CDATA[METHOD	GetGensetData : ST_HMI_Monitor_ArrayDataFormat
VAR_IN_OUT CONSTANT
	data : ST_Genset_get;
END_VAR

VAR_INPUT
	id: INT;
END_VAR

VAR
	modestring : STRING;
	RunningString : STRING;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[CASE ID OF 
	1: 		GetGensetData.s_Name:= 'Breaker state';
			GetGensetData.s_Type:= 'Status';
			GetGensetData.s_Unit:= SEL(data.bGenBreakerClosed, 'OPEN', 'CLOSED');
	2: 		GetGensetData.s_Name:= 'Sync state';
			GetGensetData.s_Type:= 'Status';
			GetGensetData.s_Unit:= TO_STRING(data.bMainBreakerClosed);
	3:		GetGensetData.s_Name:= 'Apparent Power';
			GetGensetData.s_Type:= 'AC';
			GetGensetData.s_Unit:= 'kVA';
			GetGensetData.i_precision:= 0;
			GetGensetData.r_Data:= data.ar_ApparentPower[0];
	4:		GetGensetData.s_Name:= 'Active Power';
			GetGensetData.s_Type:= 'AC';
			GetGensetData.s_Unit:= 'kW';
			GetGensetData.i_precision:= 1;
			GetGensetData.r_Data:= data.ar_ActivePower[0];
	5:		GetGensetData.s_Name:= 'Reactive Power';
			GetGensetData.s_Type:= 'AC';
			GetGensetData.s_Unit:= 'kvar';
			GetGensetData.i_precision:= 1;
			GetGensetData.r_Data:= data.ar_ReactivePower[0];
	6:		GetGensetData.s_Name:= 'Current';
			GetGensetData.s_Type:= 'AC';
			GetGensetData.s_Unit:= 'A';
			GetGensetData.i_precision:= 1;
			GetGensetData.r_Data:= data.ar_Current[0];
	7:		GetGensetData.s_Name:= 'Line Voltage';
			GetGensetData.s_Type:= 'AC';
			GetGensetData.s_Unit:= 'VAC';
			GetGensetData.i_precision:= 1;
			GetGensetData.r_Data:= data.ar_LineVoltage[0];
	8:		GetGensetData.s_Name:= 'Phase Voltage';
			GetGensetData.s_Type:= 'AC';
			GetGensetData.s_Unit:= 'VAC';
			GetGensetData.i_precision:= 1;
			GetGensetData.r_Data:= data.ar_PhaseVoltage[0];
	9:		GetGensetData.s_Name:= 'Frequency';
			GetGensetData.s_Type:= 'AC';
			GetGensetData.s_Unit:= 'Hz';
			GetGensetData.i_precision:= 2;
			GetGensetData.r_Data:=  data.ar_Frequency[0];
	10: 	GetGensetData.s_Name:= 'Power factor';
			GetGensetData.s_Type:= 'AC';
			GetGensetData.s_Unit:= '-';
			GetGensetData.i_precision:= 2;
			GetGensetData.r_Data:=  data.ar_Powerfactor[0];
	11:		GetGensetData.s_Name:= 'L1';
			GetGensetData.s_Type:= 'AC Current';
			GetGensetData.s_Unit:= 'A';
			GetGensetData.i_precision:= 1;
			GetGensetData.r_Data:= data.ar_Current[1];
	12:		GetGensetData.s_Name:= 'L2';
			GetGensetData.s_Type:= 'AC Current';
			GetGensetData.s_Unit:= 'A';
			GetGensetData.i_precision:= 1;
			GetGensetData.r_Data:= data.ar_Current[2];
	13:		GetGensetData.s_Name:= 'L3';
			GetGensetData.s_Type:= 'AC Current';
			GetGensetData.s_Unit:= 'A';
			GetGensetData.i_precision:= 1;
			GetGensetData.r_Data:= data.ar_Current[3];
	14:		IF data.bFixedPowerActive THEN
				modestring := 'Fixed Power ';
			ELSIF data.bIslandModeActive THEN
				modestring := 'Island ';
			ELSIF data.bMainsFailure THEN
				modestring := 'Mains Failure ';
			END_IF
			RunningString := SEL(data.bGenRunning, 'Off','Running');
			GetGensetData.s_Name:= 'Mode';
			GetGensetData.s_Type:= 'Status';
			GetGensetData.s_Unit:= CONCAT(ModeString, RunningString);
ELSE	
		RETURN;
END_CASE
]]></ST>
      </Implementation>
    </Method>
    <Method Name="GetHeatpumpData" Id="{ca9d6ad2-f446-421c-b5ea-66fe0797deb9}" FolderPath="ArrayDataMethods\">
      <Declaration><![CDATA[METHOD GetHeatpumpData :  ST_HMI_Monitor_ArrayDataFormat
VAR_IN_OUT CONSTANT
	data			: ST_Heatpump_get;
END_VAR

VAR_INPUT
	id: INT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[CASE ID OF 
	1: 		GetHeatpumpData.s_Name:= 'State';
			GetHeatpumpData.s_Type:= 'status';
			GetHeatpumpData.s_unit:= TO_STRING(data.HeatPumpState);
	2: 		GetHeatpumpData.s_Name:= 'Operating hours';
			GetHeatpumpData.s_Type:= 'status';
			GetHeatpumpData.s_unit:= TO_STRING(data.HeatpumpData.i_OperatingHours);
	3: 		GetHeatpumpData.s_Name:= 'Setpoint';
			GetHeatpumpData.s_Type:= 'data';
			GetHeatpumpData.s_Unit:= '°C';
			GetHeatpumpData.i_precision:= 1;
			GetHeatpumpData.r_data:= data.Setpoint;
	4: 		GetHeatpumpData.s_Name:= 'Inlet water temp';
			GetHeatpumpData.s_Type:= 'data';
			GetHeatpumpData.s_Unit:= '°C';
			GetHeatpumpData.i_precision:= 1;
			GetHeatpumpData.r_data:= data.HeatpumpData.r_InletWaterTemp;
	5: 		GetHeatpumpData.s_Name:= 'Outlet water temp';
			GetHeatpumpData.s_Type:= 'data';
			GetHeatpumpData.s_Unit:= '°C';
			GetHeatpumpData.i_precision:= 1;
			GetHeatpumpData.r_data:= data.HeatpumpData.r_OutletWaterTemp;
	6: 		GetHeatpumpData.s_Name:= 'Comp input temp';
			GetHeatpumpData.s_Type:= 'data';
			GetHeatpumpData.s_Unit:= '°C';
			GetHeatpumpData.i_precision:= 1;
			GetHeatpumpData.r_data:= data.HeatpumpData.r_CompInputTemp;
	7: 		GetHeatpumpData.s_Name:= 'Comp output temp';
			GetHeatpumpData.s_Type:= 'data';
			GetHeatpumpData.s_Unit:= '°C';
			GetHeatpumpData.i_precision:= 1;
			GetHeatpumpData.r_data:= data.HeatpumpData.r_CompOutputTemp;
	8: 		GetHeatpumpData.s_Name:= 'Outdoor temp';
			GetHeatpumpData.s_Type:= 'data';
			GetHeatpumpData.s_Unit:= '°C';
			GetHeatpumpData.i_precision:= 1;
			GetHeatpumpData.r_data:= data.HeatpumpData.r_OutdoorTemp;
	9: 		GetHeatpumpData.s_Name:= 'Low pressure';
			GetHeatpumpData.s_Type:= 'data';
			GetHeatpumpData.s_Unit:= 'bar';
			GetHeatpumpData.i_precision:= 1;
			GetHeatpumpData.r_data:= data.HeatpumpData.r_LowPressure;
	10: 	GetHeatpumpData.s_Name:= 'High pressure';
			GetHeatpumpData.s_Type:= 'data';
			GetHeatpumpData.s_Unit:= 'bar';
			GetHeatpumpData.i_precision:= 1;
			GetHeatpumpData.r_data:= data.HeatpumpData.r_HighPressure;
	11: 	GetHeatpumpData.s_Name:= 'Water flowrate';
			GetHeatpumpData.s_Type:= 'data';
			GetHeatpumpData.s_Unit:= 'L/s';
			GetHeatpumpData.i_precision:= 1;
			GetHeatpumpData.r_data:= data.HeatpumpData.ui_WaterFlowRate;
	12: 	GetHeatpumpData.s_Name:= 'Defrosting';
			GetHeatpumpData.s_Type:= 'status';
			GetHeatpumpData.s_Unit:= SEL(data.HeatpumpData.b_DefrostingActive, 'Active', 'Inactive');
	14: 	GetHeatpumpData.s_Name:= 'Pump speed';
			GetHeatpumpData.s_Type:= 'data';
			GetHeatpumpData.s_Unit:= '%';
			GetHeatpumpData.i_precision:= 1;
			GetHeatpumpData.r_data:= data.HeatpumpData.r_PumpSpeedPCT;
	15: 	GetHeatpumpData.s_Name:= 'Fan speed';
			GetHeatpumpData.s_Type:= 'data';
			GetHeatpumpData.s_Unit:= '%';
			GetHeatpumpData.i_precision:= 1;
			GetHeatpumpData.r_data:= data.HeatpumpData.r_FanSpeedPCT;
ELSE	
		RETURN;			
END_CASE]]></ST>
      </Implementation>
    </Method>
    <Method Name="GetMBMUData" Id="{39578673-79de-4963-a904-8a295803820d}" FolderPath="ArrayDataMethods\">
      <Declaration><![CDATA[METHOD GetMBMUData : ST_HMI_Monitor_ArrayDataFormat
VAR_IN_OUT CONSTANT
	data 			: st_BMS_BatterySummary;
END_VAR

VAR_INPUT
	id: INT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[CASE ID OF 
	1: 		GetMBMUData.s_Name:= 'Status';
			GetMBMUData.s_Type:= 'status';
			GetMBMUData.s_unit:= TO_STRING(data.e_BMS_Status);
	2: 		GetMBMUData.s_Name:= 'Power-on status';
			GetMBMUData.s_Type:= 'status';
			GetMBMUData.s_unit:= TO_STRING(data.e_BMS_PowerOnStatus);
	3:		GetMBMUData.s_Name:= 'Voltage';
			GetMBMUData.s_Type:= 'power';
			GetMBMUData.s_Unit:= 'VDC';
			GetMBMUData.i_precision:= 1;
			GetMBMUData.r_Data:= data.r_SystemVoltage;
	4:		GetMBMUData.s_Name:= 'Current';
			GetMBMUData.s_Type:= 'power';
			GetMBMUData.s_Unit:= 'A';
			GetMBMUData.i_precision:= 1;
			GetMBMUData.r_Data:= data.r_SystemCurrent;
	5:		GetMBMUData.s_Name:= 'Power';
			GetMBMUData.s_Type:= 'power';
			GetMBMUData.s_Unit:= 'kW';
			GetMBMUData.i_precision:= 1;
			GetMBMUData.r_Data:= data.r_SystemPower;
	6:		GetMBMUData.s_Name:= 'Max charge current';
			GetMBMUData.s_Type:= 'limit';
			GetMBMUData.s_Unit:= 'A';
			GetMBMUData.i_precision:= 1;
			GetMBMUData.r_Data:= data.r_MaxChargeCurrentAllowed;
	7:		GetMBMUData.s_Name:= 'Max discharge current';
			GetMBMUData.s_Type:= 'limit';
			GetMBMUData.s_Unit:= 'A';
			GetMBMUData.i_precision:= 1;
			GetMBMUData.r_Data:= data.r_MaxDischargeCurrentAllowed;
	8:		GetMBMUData.s_Name:= 'Max charge power';
			GetMBMUData.s_Type:= 'limit';
			GetMBMUData.s_Unit:= 'kW';
			GetMBMUData.i_precision:= 1;
			GetMBMUData.r_Data:= data.r_MaxChargePowerAllowed;
	9: 		GetMBMUData.s_Name:= 'Max discharge power';
			GetMBMUData.s_Type:= 'limit';
			GetMBMUData.s_Unit:= 'kW';
			GetMBMUData.i_precision:= 1;
			GetMBMUData.r_Data:= data.r_MaxDischargePowerAllowed;
	10:		GetMBMUData.s_Name:= 'Charge SOE';
			GetMBMUData.s_Type:= 'energy';
			GetMBMUData.s_Unit:= '%';
			GetMBMUData.i_precision:= 0;
			GetMBMUData.r_Data:= data.r_ChargeSOE;
	11:		GetMBMUData.s_Name:= 'Discharge SOE';                       
			GetMBMUData.s_Type:= 'energy';                       
			GetMBMUData.s_Unit:= '%';                               
			GetMBMUData.i_precision:= 0;                              
			GetMBMUData.r_Data:= data.r_DischargeSOE;
//	12:		GetMBMUData.s_Name:= 'Total charge energy';                       
//			GetMBMUData.s_Type:= 'energy';                       
//			GetMBMUData.s_Unit:= 'kWh';                               
//			GetMBMUData.i_precision:= 0;                              
//			GetMBMUData.r_Data:= data.r_HistAccChargeEnergy;
//	13:		GetMBMUData.s_Name:= 'Total discharge energy';                         
//			GetMBMUData.s_Type:= 'energy';                                 
//			GetMBMUData.s_Unit:= 'kWh';                                         
//			GetMBMUData.i_precision:= 0;                                        
//			GetMBMUData.r_Data:= data.r_HistAccDischargeEnergy;
			
	14:		GetMBMUData.s_Name:= 'Remaining charge energy';                         
			GetMBMUData.s_Type:= 'energy';                                 
			GetMBMUData.s_Unit:= 'kWh';                                         
			GetMBMUData.i_precision:= 0;                                        
			GetMBMUData.r_Data:= data.r_RemainingChargeEnergy;
	15:		GetMBMUData.s_Name:= 'Remaining discharge energy';                         
			GetMBMUData.s_Type:= 'energy';                                 
			GetMBMUData.s_Unit:= 'kWh';                                         
			GetMBMUData.i_precision:= 0;                                        
			GetMBMUData.r_Data:= data.r_RemainingDischargeEnergy;	
	16:		GetMBMUData.s_Name:= 'Max allowed voltage';                         
			GetMBMUData.s_Type:= 'limit';                                 
			GetMBMUData.s_Unit:= 'VDC';                                         
			GetMBMUData.i_precision:= 1;                                        
			GetMBMUData.r_Data:= data.r_MaxSystemVoltageAllowed;	
	17:		GetMBMUData.s_Name:= 'Min allowed voltage';                                     
			GetMBMUData.s_Type:= 'limit';                                     
			GetMBMUData.s_Unit:= 'VDC';                                             
			GetMBMUData.i_precision:= 1;                                            
			GetMBMUData.r_Data:= data.r_MinSystemVoltageAllowed;
			GetMBMUData.s_Type:= 'cell';                                        
			GetMBMUData.s_Unit:= 'VDC';                                                
			GetMBMUData.i_precision:= 2;                                               
			GetMBMUData.r_Data:= data.ar_CellVoltage[2];
	18:		GetMBMUData.s_Name:= 'SOH';
			GetMBMUData.s_Type:= 'status';
			GetMBMUData.s_Unit:= '%';
			GetMBMUData.i_precision:= 1;
			GetMBMUData.r_Data:= data.r_SOH;	
	19:		GetMBMUData.s_Name:= 'SOC actual';                          
			GetMBMUData.s_Type:= 'status';                  
			GetMBMUData.s_Unit:= '%';                            
			GetMBMUData.i_precision:= 1;                         
			GetMBMUData.r_Data:= data.r_SOC;
	20:		GetMBMUData.s_Name:= 'Cycle count';                          
			GetMBMUData.s_Type:= 'status';                                          
			GetMBMUData.s_unit:= TO_STRING(data.ui_CycleCount);
	ELSE	
		RETURN;			
END_CASE
]]></ST>
      </Implementation>
    </Method>
    <Method Name="GetPowerModuleArrayData" Id="{58fb203a-814b-4bbe-ad61-b4af9090ca86}" FolderPath="ArrayDataMethods\">
      <Declaration><![CDATA[METHOD GetPowerModuleArrayData : ST_HMI_Monitor_ArrayDataFormat
VAR_IN_OUT CONSTANT
	data		: ST_Powermodule_get;
END_VAR

VAR_INPUT
	id: INT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[CASE ID OF 
	1: 		GetPowerModuleArrayData.s_Name:= 'Status';                                                
			GetPowerModuleArrayData.s_Type:= 'Status';                                                
			GetPowerModuleArrayData.s_Unit:= TO_STRING(data.e_Status);				                            
	2: 		GetPowerModuleArrayData.s_Name:= 'Inverter Mode';                                         
			GetPowerModuleArrayData.s_Type:= 'Status';                                                
			GetPowerModuleArrayData.s_Unit:= TO_STRING(data.e_InverterMode);					                     
	3:		GetPowerModuleArrayData.s_Name:= 'Power Mode';                                            
			GetPowerModuleArrayData.s_Type:= 'Status';                                                
			GetPowerModuleArrayData.s_Unit:= TO_STRING(data.e_PowerMode);						                       
	4:		GetPowerModuleArrayData.s_Name:= 'Fan state';                                             
			GetPowerModuleArrayData.s_Type:= 'Status';                                                
			GetPowerModuleArrayData.s_Unit:= SEL(data.b_FanFb,'OFF', 'RUNNING');						                
	5:		GetPowerModuleArrayData.s_Name:= 'MCCB state';                                            
			GetPowerModuleArrayData.s_Type:= 'Status';                                                
			GetPowerModuleArrayData.s_Unit:= SEL(data.b_MccbFb,'OPEN', 'CLOSED');						               
	6:		GetPowerModuleArrayData.s_Name:= 'MCCB tripstate';                                        
			GetPowerModuleArrayData.s_Type:= 'Status';                                                
			GetPowerModuleArrayData.s_Unit:= SEL(data.b_MccbTripOK,'TRIPPED', 'OK');						              
	7:		GetPowerModuleArrayData.s_Name:= 'D7 measurements OK';                                    
			GetPowerModuleArrayData.s_Type:= 'Ugrid statusword';                                      
			GetPowerModuleArrayData.s_Unit:= TO_STRING(data.UgridStatusWord.b_D7MeasurementsOK);						
	8:		GetPowerModuleArrayData.s_Name:= 'Synchronized to D7';                                    
			GetPowerModuleArrayData.s_Type:= 'Ugrid statusword';                                      
			GetPowerModuleArrayData.s_Unit:= TO_STRING(data.UgridStatusWord.b_SynchronizedToD7);      
	9: 		GetPowerModuleArrayData.s_Name:= 'Ready to DCcharge';                                     
			GetPowerModuleArrayData.s_Type:= 'statusword';                                            
			GetPowerModuleArrayData.s_Unit:= TO_STRING(data.StatusWord.b_ReadyToDCCharge);            
	10:		GetPowerModuleArrayData.s_Name:= 'Ready to operate';                                      
			GetPowerModuleArrayData.s_Type:= 'statusword';                                            
			GetPowerModuleArrayData.s_Unit:= TO_STRING(data.StatusWord.b_ReadyToOperate);
	11:		GetPowerModuleArrayData.s_Name:= 'Run enabled';                                           
			GetPowerModuleArrayData.s_Type:= 'statusword';                                            
			GetPowerModuleArrayData.s_Unit:= TO_STRING(data.StatusWord.b_RunEnabled);                 
	12:		GetPowerModuleArrayData.s_Name:= 'Running';                                               
			GetPowerModuleArrayData.s_Type:= 'statusword';                                            
			GetPowerModuleArrayData.s_Unit:= TO_STRING(data.StatusWord.b_Running);                    
	13:		GetPowerModuleArrayData.s_Name:= 'DC at reference';                                       
			GetPowerModuleArrayData.s_Type:= 'statusword';                                            
			GetPowerModuleArrayData.s_Unit:= TO_STRING(data.StatusWord.b_DCAtReference);              
	14:		GetPowerModuleArrayData.s_Name:= 'DC above limit';                                        
			GetPowerModuleArrayData.s_Type:= 'statusword';                                            
			GetPowerModuleArrayData.s_Unit:= TO_STRING(data.StatusWord.b_DCAboveLimit);               
	15:		GetPowerModuleArrayData.s_Name:= 'Quickstop active';                                      
			GetPowerModuleArrayData.s_Type:= 'statusword';                                            
			GetPowerModuleArrayData.s_Unit:= TO_STRING(NOT(data.StatusWord.b_QuickstopNotActive));    
	16:		GetPowerModuleArrayData.s_Name:= 'Warning';                                               
			GetPowerModuleArrayData.s_Type:= 'statusword';                                            
			GetPowerModuleArrayData.s_Unit:= TO_STRING(data.StatusWord.b_Warning);                    
	17:		GetPowerModuleArrayData.s_Name:= 'Fault';                                                 
			GetPowerModuleArrayData.s_Type:= 'statusword';                                            
			GetPowerModuleArrayData.s_Unit:= TO_STRING(data.StatusWord.b_Fault);                      
	18:		GetPowerModuleArrayData.s_Name:= 'MCCB control OK';                                       
			GetPowerModuleArrayData.s_Type:= 'statusword';                                            
			GetPowerModuleArrayData.s_Unit:= TO_STRING(NOT(data.StatusWord.b_MCCBControlNotOK));						
	19:		GetPowerModuleArrayData.s_Name:= 'Load';                                                   
			GetPowerModuleArrayData.s_Type:= 'AC';                                                    
			GetPowerModuleArrayData.s_Unit:= '%';                                                     
			GetPowerModuleArrayData.r_Data:= data.r_LoadPercent;                                      
			GetPowerModuleArrayData.i_precision := 1;	                                                
	20:		GetPowerModuleArrayData.s_Name:= 'Apparent Power';                                        
			GetPowerModuleArrayData.s_Type:= 'AC';                                                    
			GetPowerModuleArrayData.s_Unit:= 'kVA';                                                   
			GetPowerModuleArrayData.r_Data:= data.r_ApparentPower;                                    
			GetPowerModuleArrayData.i_precision := 0;                                                 
	21:		GetPowerModuleArrayData.s_Name:= 'Active Power';                                          
			GetPowerModuleArrayData.s_Type:= 'AC';                                                    
			GetPowerModuleArrayData.s_Unit:= 'kW';                                                    
			GetPowerModuleArrayData.r_Data:= data.r_ActivePower;                                      
			GetPowerModuleArrayData.i_precision := 1;                                                 
	22:		GetPowerModuleArrayData.s_Name:= 'Reactive Power';                                        
			GetPowerModuleArrayData.s_Type:= 'AC';                                                    
			GetPowerModuleArrayData.s_Unit:= 'kvar';                                                  
			GetPowerModuleArrayData.r_Data:= data.r_ReactivePower;                                    
			GetPowerModuleArrayData.i_precision := 1;                                                 
	23:		GetPowerModuleArrayData.s_Name:= 'Current';                                               
			GetPowerModuleArrayData.s_Type:= 'AC';                                                    
			GetPowerModuleArrayData.s_Unit:= 'A';                                                     
			GetPowerModuleArrayData.r_Data:= data.r_ACCurrent;                                        
			GetPowerModuleArrayData.i_precision := 1;                                                 
	24:		GetPowerModuleArrayData.s_Name:= 'Reactive Current';                                      
			GetPowerModuleArrayData.s_Type:= 'AC';                                                    
			GetPowerModuleArrayData.s_Unit:= 'A';                                                     
			GetPowerModuleArrayData.r_Data:= data.r_ReactiveCurrent;                                  
			GetPowerModuleArrayData.i_precision := 1;                                                 
	25:		GetPowerModuleArrayData.s_Name:= 'Active Current';                                        
			GetPowerModuleArrayData.s_Type:= 'AC';                                                    
			GetPowerModuleArrayData.s_Unit:= 'A';                                                     
			GetPowerModuleArrayData.r_Data:= data.r_ActiveCurrent;                                    
			GetPowerModuleArrayData.i_precision := 1;                                                 
	26:		GetPowerModuleArrayData.s_Name:= 'Supply Voltage';                                        
			GetPowerModuleArrayData.s_Type:= 'AC';                                                    
			GetPowerModuleArrayData.s_Unit:= 'VAC';                                                   
			GetPowerModuleArrayData.r_Data:= data.r_ACVoltageSupply;                                  
			GetPowerModuleArrayData.i_precision := 1;                                                 
	27:		GetPowerModuleArrayData.s_Name:= 'Supply Frequency';                                      
			GetPowerModuleArrayData.s_Type:= 'AC';                                                    
			GetPowerModuleArrayData.s_Unit:= 'Hz';                                                    
			GetPowerModuleArrayData.r_Data:= data.r_FrequencySupply;                                  
			GetPowerModuleArrayData.i_precision := 2;                                                 
	28:		GetPowerModuleArrayData.s_Name:= 'Current';                                               
			GetPowerModuleArrayData.s_Type:= 'DC';                                                    
			GetPowerModuleArrayData.s_Unit:= 'A';                                                     
			GetPowerModuleArrayData.r_Data:= data.r_DCCurrent;                                        
			GetPowerModuleArrayData.i_precision := 1;                                                 
	29:		GetPowerModuleArrayData.s_Name:= 'Voltage';                                               
			GetPowerModuleArrayData.s_Type:= 'DC';                                                    
			GetPowerModuleArrayData.s_Unit:= 'VDC';                                                   
			GetPowerModuleArrayData.r_Data:= data.r_DCVoltage;                                        
			GetPowerModuleArrayData.i_precision := 1;                                                 
	30:		GetPowerModuleArrayData.s_Name:= 'Power';                                                 
			GetPowerModuleArrayData.s_Type:= 'DC';                                                    
			GetPowerModuleArrayData.s_Unit:= 'kW';                                                    
			GetPowerModuleArrayData.r_Data:= data.r_DCPower;                                          
			GetPowerModuleArrayData.i_precision := 1;                                                 
	31:		GetPowerModuleArrayData.s_Name:= 'CMchoke L1';                                            
			GetPowerModuleArrayData.s_Type:= 'Temperatures';                                          
			GetPowerModuleArrayData.s_Unit:= '°C';                                                    
			GetPowerModuleArrayData.r_Data:= data.r_TemperatureCMChoke[1];                            
			GetPowerModuleArrayData.i_precision := 1;                                                 
	32:		GetPowerModuleArrayData.s_Name:= 'CMchoke L2';                                            
			GetPowerModuleArrayData.s_Type:= 'Temperatures';                                          
			GetPowerModuleArrayData.s_Unit:= '°C';                                                    
			GetPowerModuleArrayData.r_Data:= data.r_TemperatureCMChoke[2];                            
			GetPowerModuleArrayData.i_precision := 1;                                                 
	33:		GetPowerModuleArrayData.s_Name:= 'CMchoke L3';                                            
			GetPowerModuleArrayData.s_Type:= 'Temperatures';                                          
			GetPowerModuleArrayData.s_Unit:= '°C';                                                    
			GetPowerModuleArrayData.r_Data:= data.r_TemperatureCMChoke[3];                            
			GetPowerModuleArrayData.i_precision := 1;                                                 
	34:		GetPowerModuleArrayData.s_Name:= 'CMchoke DC';                                            
			GetPowerModuleArrayData.s_Type:= 'Temperatures';                                          
			GetPowerModuleArrayData.s_Unit:= '°C';                                                    
			GetPowerModuleArrayData.r_Data:= data.r_TemperatureCMChoke[4];                            
			GetPowerModuleArrayData.i_precision := 1;                                                 
	35:		GetPowerModuleArrayData.s_Name:= 'Gridchoke L1';                                          
			GetPowerModuleArrayData.s_Type:= 'Temperatures';                                          
			GetPowerModuleArrayData.s_Unit:= '°C';                                                    
			GetPowerModuleArrayData.r_Data:= data.r_Temperaturegridchoke[1];                          
			GetPowerModuleArrayData.i_precision := 1;                                                 
	36:		GetPowerModuleArrayData.s_Name:= 'Gridchoke L2';                                          
			GetPowerModuleArrayData.s_Type:= 'Temperatures';                                          
			GetPowerModuleArrayData.s_Unit:= '°C';                                                    
			GetPowerModuleArrayData.r_Data:= data.r_Temperaturegridchoke[2];                          
			GetPowerModuleArrayData.i_precision := 1;                                                 
	37:		GetPowerModuleArrayData.s_Name:= 'Gridchoke L3';                                          
			GetPowerModuleArrayData.s_Type:= 'Temperatures';                                          
			GetPowerModuleArrayData.s_Unit:= '°C';                                                    
			GetPowerModuleArrayData.r_Data:= data.r_Temperaturegridchoke[3];                          
			GetPowerModuleArrayData.i_precision := 1;                                                 
	38:		GetPowerModuleArrayData.s_Name:= 'Inverter';                                              
			GetPowerModuleArrayData.s_Type:= 'Temperatures';                                          
			GetPowerModuleArrayData.s_Unit:= '°C';                                                    
			GetPowerModuleArrayData.r_Data:= data.r_TemperatureInverter;                              
			GetPowerModuleArrayData.i_precision := 1;                                                 
	39:		GetPowerModuleArrayData.s_Name:= 'Powermodule max';                                   
			GetPowerModuleArrayData.s_Type:= 'Temperatures';                                          
			GetPowerModuleArrayData.s_Unit:= '°C';                                                    
			GetPowerModuleArrayData.r_Data:= data.r_TemperatureMax;                                   
			GetPowerModuleArrayData.i_precision := 1;                                                 
	40:		GetPowerModuleArrayData.s_Name:= 'Active power min(charge)';                              
			GetPowerModuleArrayData.s_Type:= 'Limits';                                                
			GetPowerModuleArrayData.s_Unit:= 'kW';                                                    
			GetPowerModuleArrayData.r_Data:= data.r_Pmin;                                             
			GetPowerModuleArrayData.i_precision := 0;                                                 
	41:		GetPowerModuleArrayData.s_Name:= 'Active power max (discharge)';                          
			GetPowerModuleArrayData.s_Type:= 'Limits';                                                
			GetPowerModuleArrayData.s_Unit:= 'kW';                                                    
			GetPowerModuleArrayData.r_Data:= data.r_Pmax;                                             
			GetPowerModuleArrayData.i_precision := 0;                                                 
	42:		GetPowerModuleArrayData.s_Name:= 'Reactive power min';                                    
			GetPowerModuleArrayData.s_Type:= 'Limits';                                                
			GetPowerModuleArrayData.s_Unit:= 'kvar';                                                  
			GetPowerModuleArrayData.r_Data:= data.r_QMin;                                             
			GetPowerModuleArrayData.i_precision := 0;                                                 
	43:		GetPowerModuleArrayData.s_Name:= 'Reactive power max';                                    
			GetPowerModuleArrayData.s_Type:= 'Limits';                                                
			GetPowerModuleArrayData.s_Unit:= 'kvar';                                                  
			GetPowerModuleArrayData.r_Data:= data.r_QMax;                                             
			GetPowerModuleArrayData.i_precision := 0;                                                 
	44:		GetPowerModuleArrayData.s_Name:= 'D7 Sync Error';                                         
			GetPowerModuleArrayData.s_Type:= 'AC';                                           
			GetPowerModuleArrayData.s_Unit:= '°';                                                     
			GetPowerModuleArrayData.r_Data:= data.r_D7SyncError;                                      
			GetPowerModuleArrayData.i_precision := 1;
	45:		GetPowerModuleArrayData.s_Name:= 'Active power';                                         
			GetPowerModuleArrayData.s_Type:= 'Setpoints';                                           
			GetPowerModuleArrayData.s_Unit:= 'kW';                                                     
			GetPowerModuleArrayData.r_Data:= data.r_Pset;                                      
			GetPowerModuleArrayData.i_precision := 0; 
	46:		GetPowerModuleArrayData.s_Name:= 'Reactive power';                                         
			GetPowerModuleArrayData.s_Type:= 'Setpoints';                                           
			GetPowerModuleArrayData.s_Unit:= 'kvar';                                                     
			GetPowerModuleArrayData.r_Data:= data.r_Qset;                                      
			GetPowerModuleArrayData.i_precision := 1;   
	47:		GetPowerModuleArrayData.s_Name:= 'Base current ref';                                         
			GetPowerModuleArrayData.s_Type:= 'Controls';                                           
			GetPowerModuleArrayData.s_Unit:= '0.1%';                                                     
			GetPowerModuleArrayData.r_Data:= data.ControlData.i_BaseCurrentRef;                                      
			GetPowerModuleArrayData.i_precision := 0; 
	48:		GetPowerModuleArrayData.s_Name:= 'Reactive current ref';                                         
			GetPowerModuleArrayData.s_Type:= 'Controls';                                           
			GetPowerModuleArrayData.s_Unit:= '0.1%';                                                     
			GetPowerModuleArrayData.r_Data:= data.ControlData.i_ReactiveCurrentRef;                                      
			GetPowerModuleArrayData.i_precision := 0;
	49:		GetPowerModuleArrayData.s_Name:= 'Frequency droop offset';                                         
			GetPowerModuleArrayData.s_Type:= 'Controls';                                           
			GetPowerModuleArrayData.s_Unit:= '0.1Hz';                                                     
			GetPowerModuleArrayData.r_Data:= data.ControlData.i_FrequencyDroopOffset;                                      
			GetPowerModuleArrayData.i_precision := 0;
	50:		GetPowerModuleArrayData.s_Name:= 'Voltage correction';                                         
			GetPowerModuleArrayData.s_Type:= 'Controls';                                           
			GetPowerModuleArrayData.s_Unit:= 'V';                                                     
			GetPowerModuleArrayData.r_Data:= data.ControlData.i_VoltageCorrection;
            GetPowerModuleArrayData.i_precision := 0;
	51:		GetPowerModuleArrayData.s_Name:= 'Frequency Droop';                                         
			GetPowerModuleArrayData.s_Type:= 'Controls';                                           
			GetPowerModuleArrayData.s_Unit:= '0.001Hz';                                                     
			GetPowerModuleArrayData.r_Data:= data.ControlData.i_FrequencyDroop;
            GetPowerModuleArrayData.i_precision := 0;  
	52:		GetPowerModuleArrayData.s_Name:= 'Voltage Droop';                                         
			GetPowerModuleArrayData.s_Type:= 'Controls';                                           
			GetPowerModuleArrayData.s_Unit:= '0.01%';                                                     
			GetPowerModuleArrayData.r_Data:= data.ControlData.i_VoltageDroop;
            GetPowerModuleArrayData.i_precision := 0;  
	53:		GetPowerModuleArrayData.s_Name:= 'Base ref ramprate';                                         
			GetPowerModuleArrayData.s_Type:= 'Controls';                                           
			GetPowerModuleArrayData.s_Unit:= '%';                                                     
			GetPowerModuleArrayData.r_Data:= data.ControlData.i_BaseRefRampRate;
            GetPowerModuleArrayData.i_precision := 0;  
    54:		GetPowerModuleArrayData.s_Name:= 'Start Powermode';                                         
			GetPowerModuleArrayData.s_Type:= 'Controls';                                           
			GetPowerModuleArrayData.s_Unit:= '-';                                                     
			GetPowerModuleArrayData.r_Data:= data.ControlData.i_StartPowerMode;
            GetPowerModuleArrayData.i_precision := 0;
    55:		GetPowerModuleArrayData.s_Name:= 'Start Voltagemode';                                         
			GetPowerModuleArrayData.s_Type:= 'Controls';                                           
			GetPowerModuleArrayData.s_Unit:= '%';                                                     
			GetPowerModuleArrayData.r_Data:= data.ControlData.i_StartVoltageMode;
            GetPowerModuleArrayData.i_precision := 0; 
	56:		GetPowerModuleArrayData.s_Name:= 'Output act. current limit';                                         
			GetPowerModuleArrayData.s_Type:= 'Controls';                                           
			GetPowerModuleArrayData.s_Unit:= '0.1%';                                                     
			GetPowerModuleArrayData.r_Data:= data.ControlData.i_OutActCurrentLimit;
            GetPowerModuleArrayData.i_precision := 0;
	57:		GetPowerModuleArrayData.s_Name:= 'Input act. current limit';                                         
			GetPowerModuleArrayData.s_Type:= 'Controls';                                           
			GetPowerModuleArrayData.s_Unit:= '0.1%';                                                     
			GetPowerModuleArrayData.r_Data:= data.ControlData.i_InActCurrentLimit;
            GetPowerModuleArrayData.i_precision := 0;                                                                                                            
	ELSE	
		RETURN;			
END_CASE



]]></ST>
      </Implementation>
    </Method>
    <Method Name="GetPowerstackArrayData" Id="{a057df20-bb99-4026-9777-a32c2b8b1466}" FolderPath="ArrayDataMethods\">
      <Declaration><![CDATA[METHOD	GetPowerstackArrayData : ST_HMI_Monitor_ArrayDataFormat

VAR_INPUT
	id: INT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[CASE ID OF 
	1: 		GetPowerstackArrayData.s_Name:= 'Status';                              
			GetPowerstackArrayData.s_Type:= 'Status';                              
			GetPowerstackArrayData.s_Unit:= TO_STRING(monitor.PowerStack.e_State);
	3:		GetPowerstackArrayData.s_Name:= 'Load';                              
			GetPowerstackArrayData.s_Type:= 'AC';                                
			GetPowerstackArrayData.s_Unit:= '%';                                 
			GetPowerstackArrayData.r_Data:= monitor.PowerStack.r_LoadPercent;    
			GetPowerstackArrayData.i_precision := 1;	                                             
	4:		GetPowerstackArrayData.s_Name:= 'Apparent Power';                    
			GetPowerstackArrayData.s_Type:= 'AC';                                
			GetPowerstackArrayData.s_Unit:= 'kVA';                               
			GetPowerstackArrayData.r_Data:= monitor.PowerStack.r_ApparentPower;  
			GetPowerstackArrayData. i_precision := 0;                                             
	5:		GetPowerstackArrayData.s_Name:= 'Active Power';                      
			GetPowerstackArrayData.s_Type:= 'AC';                                
			GetPowerstackArrayData.s_Unit:= 'kW';                                
			GetPowerstackArrayData.r_Data:= monitor.PowerStack.r_ActivePower;    
			GetPowerstackArrayData.i_precision := 1;                                             
	6:		GetPowerstackArrayData.s_Name:= 'Reactive Power';                    
			GetPowerstackArrayData.s_Type:= 'AC';                                
			GetPowerstackArrayData.s_Unit:= 'kvar';                              
			GetPowerstackArrayData.r_Data:= monitor.PowerStack.r_ReactivePower;  
			GetPowerstackArrayData.i_precision := 1;                                             
	7:		GetPowerstackArrayData.s_Name:= 'Current';                           
			GetPowerstackArrayData.s_Type:= 'AC';                                
			GetPowerstackArrayData.s_Unit:= 'A';                                 
			GetPowerstackArrayData.r_Data:= monitor.PowerStack.r_ACCurrent;      
			GetPowerstackArrayData.i_precision := 1;                                              
	8:		GetPowerstackArrayData.s_Name:= 'Supply Voltage';                    
			GetPowerstackArrayData.s_Type:= 'AC';                                
			GetPowerstackArrayData.s_Unit:= 'VAC';                               
			GetPowerstackArrayData.r_Data:= monitor.PowerStack.r_ACVoltageSupply;
			GetPowerstackArrayData.i_precision := 1;                                              
	9: 		GetPowerstackArrayData.s_Name:= 'Supply Frequency';                  
			GetPowerstackArrayData.s_Type:= 'AC';                                
			GetPowerstackArrayData.s_Unit:= 'Hz';                                
			GetPowerstackArrayData.r_Data:= monitor.PowerStack.r_FrequencySupply;
			GetPowerstackArrayData.i_precision := 2;
	10:		GetPowerstackArrayData.s_Name:= 'D7 Voltage';                    
			GetPowerstackArrayData.s_Type:= 'AC';                                
			GetPowerstackArrayData.s_Unit:= 'VAC';                               
			GetPowerstackArrayData.r_Data:= monitor.PowerStack.r_ACVoltageD7;
			GetPowerstackArrayData.i_precision := 0;                                              
	11: 	GetPowerstackArrayData.s_Name:= 'D7 Frequency';                  
			GetPowerstackArrayData.s_Type:= 'AC';                                
			GetPowerstackArrayData.s_Unit:= 'Hz';                                
			GetPowerstackArrayData.r_Data:= monitor.PowerStack.r_FrequencyD7;
			GetPowerstackArrayData.i_precision := 2;                                                                                    
	12:		GetPowerstackArrayData.s_Name:= 'Cos Phi';                           
			GetPowerstackArrayData.s_Type:= 'AC';                                
			GetPowerstackArrayData.s_Unit:= '-';                                 
			GetPowerstackArrayData.r_Data:= monitor.PowerStack.r_Cosphi;         
			GetPowerstackArrayData.i_precision := 2;
	13:		GetPowerstackArrayData.s_Name:= 'Current';                           
			GetPowerstackArrayData.s_Type:= 'DC';                                
			GetPowerstackArrayData.s_Unit:= 'A';                                 
			GetPowerstackArrayData.r_Data:= monitor.PowerStack.r_DCCurrent;      
			GetPowerstackArrayData.i_precision := 1;                                              
	14:		GetPowerstackArrayData.s_Name:= 'Voltage';                           
			GetPowerstackArrayData.s_Type:= 'DC';                                
			GetPowerstackArrayData.s_Unit:= 'VDC';                               
			GetPowerstackArrayData.r_Data:= monitor.PowerStack.r_DCVoltage;      
			GetPowerstackArrayData.i_precision := 1;                                              
	15:		GetPowerstackArrayData.s_Name:= 'Power';                             
			GetPowerstackArrayData.s_Type:= 'DC';                                
			GetPowerstackArrayData.s_Unit:= 'kW';                                
			GetPowerstackArrayData.r_Data:= monitor.PowerStack.r_DCPower; 
			GetPowerstackArrayData.i_precision := 1;        
	16:		GetPowerstackArrayData.s_Name:= 'Inverter Mode';                                         
			GetPowerstackArrayData.s_Type:= 'Status';                                                
			GetPowerstackArrayData.s_Unit:= TO_STRING(monitor.PowerStack.e_InverterMode);            
	17:		GetPowerstackArrayData.s_Name:= 'Power Mode';                                            
			GetPowerstackArrayData.s_Type:= 'Status';                                                
			GetPowerstackArrayData.s_Unit:= TO_STRING(monitor.PowerStack.e_PowerMode);               
	18:		GetPowerstackArrayData.s_Name:= 'Netcontactor';                                          
			GetPowerstackArrayData.s_Type:= 'Status';                                                
			GetPowerstackArrayData.s_Unit:= TO_STRING(monitor.PowerStack.NetContactor.e_NetConState);
	19: 	GetPowerstackArrayData.s_Name:= 'Energy out';      
			GetPowerstackArrayData.s_Type:= 'Energy';         
			GetPowerstackArrayData.s_Unit:= 'kWh';            
			GetPowerstackArrayData.i_precision:= 1;
			GetPowerstackArrayData.b_warning := monitor.powermonitor.BESS.r_EnergySupplied < 0;              
			GetPowerstackArrayData.r_Data:= monitor.powermonitor.BESS.r_EnergySupplied;
	20: 	GetPowerstackArrayData.s_Name:= 'Energy in';          
			GetPowerstackArrayData.s_Type:= 'Energy';         
			GetPowerstackArrayData.s_Unit:= 'kWh';                
			GetPowerstackArrayData.i_precision:= 1;
			GetPowerstackArrayData.b_warning := monitor.powermonitor.BESS.r_EnergyConsumed < 0;              
			GetPowerstackArrayData.r_Data:= monitor.powermonitor.BESS.r_EnergyConsumed;
	ELSE	
		RETURN;
END_CASE
]]></ST>
      </Implementation>
    </Method>
    <Method Name="GetPSBdata" Id="{f976bc01-11eb-4e2f-8e19-f77f419f9bed}" FolderPath="ArrayDataMethods\">
      <Declaration><![CDATA[METHOD	GetPSBdata : ST_HMI_Monitor_ArrayDataFormat
VAR_IN_OUT CONSTANT
	data : ST_Peakshavebox_get;
END_VAR

VAR_INPUT
	id: INT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[CASE ID OF 
	1: 		GetPSBData.s_Name:= 'Breaker state';
			GetPSBData.s_Type:= 'Status';
			GetPSBData.s_Unit:= SEL(data.b_ContactorFb, 'OPEN', 'CLOSED');
	2: 		GetPSBData.s_Name:= 'Sync state';
			GetPSBData.s_Type:= 'Status';
			GetPSBData.s_Unit:= TO_STRING(data.b_SyncFb);
	3:		GetPSBData.s_Name:= 'Apparent Power';
			GetPSBData.s_Type:= 'AC';
			GetPSBData.s_Unit:= 'kVA';
			GetPSBData.i_precision:= 0;
			GetPSBData.r_Data:= data.Powermonitor.ar_ApparentPower[0];
	4:		GetPSBData.s_Name:= 'Active Power';
			GetPSBData.s_Type:= 'AC';
			GetPSBData.s_Unit:= 'kW';
			GetPSBData.i_precision:= 1;
			GetPSBData.r_Data:= data.Powermonitor.ar_ActivePower[0];
	5:		GetPSBData.s_Name:= 'Reactive Power';
			GetPSBData.s_Type:= 'AC';
			GetPSBData.s_Unit:= 'kvar';
			GetPSBData.i_precision:= 1;
			GetPSBData.r_Data:= data.Powermonitor.ar_ReactivePower[0];
	6:		GetPSBData.s_Name:= 'Current';
			GetPSBData.s_Type:= 'AC';
			GetPSBData.s_Unit:= 'A';
			GetPSBData.i_precision:= 1;
			GetPSBData.r_Data:= data.Powermonitor.ar_Current[0];
	7:		GetPSBData.s_Name:= 'Line Voltage';
			GetPSBData.s_Type:= 'AC';
			GetPSBData.s_Unit:= 'VAC';
			GetPSBData.i_precision:= 1;
			GetPSBData.r_Data:= data.powermonitor.ar_LineVoltage[0];
	8:		GetPSBData.s_Name:= 'Phase Voltage';
			GetPSBData.s_Type:= 'AC';
			GetPSBData.s_Unit:= 'VAC';
			GetPSBData.i_precision:= 1;
			GetPSBData.r_Data:= data.powermonitor.ar_PhaseVoltage[0];
	9:		GetPSBData.s_Name:= 'Frequency';
			GetPSBData.s_Type:= 'AC';
			GetPSBData.s_Unit:= 'Hz';
			GetPSBData.i_precision:= 2;
			GetPSBData.r_Data:=  data.powermonitor.ar_Frequency[0];
	10: 	GetPSBData.s_Name:= 'Power factor';
			GetPSBData.s_Type:= 'AC';
			GetPSBData.s_Unit:= '-';
			GetPSBData.i_precision:= 2;
			GetPSBData.r_Data:=  data.powermonitor.ar_Powerfactor[0];
	11:		GetPSBData.s_Name:= 'L1';
			GetPSBData.s_Type:= 'AC Current';
			GetPSBData.s_Unit:= 'A';
			GetPSBData.i_precision:= 1;
			GetPSBData.r_Data:= data.Powermonitor.ar_Current[1];
	12:		GetPSBData.s_Name:= 'L2';
			GetPSBData.s_Type:= 'AC Current';
			GetPSBData.s_Unit:= 'A';
			GetPSBData.i_precision:= 1;
			GetPSBData.r_Data:= data.Powermonitor.ar_Current[2];
	13:		GetPSBData.s_Name:= 'L3';
			GetPSBData.s_Type:= 'AC Current';
			GetPSBData.s_Unit:= 'A';
			GetPSBData.i_precision:= 1;
			GetPSBData.r_Data:= data.Powermonitor.ar_Current[3];
	15:		GetPSBData.s_Name:= 'N';
			GetPSBData.s_Type:= 'AC Current';
			GetPSBData.s_Unit:= 'A';
			GetPSBData.i_precision:= 1;
			GetPSBData.r_Data:= data.Powermonitor.ar_Current[4];	
	16:		GetPSBData.s_Name:= 'L1-L2';
			GetPSBData.s_Type:= 'AC Linevoltage';
			GetPSBData.s_Unit:= 'VAC';
			GetPSBData.i_precision:= 1;
			GetPSBData.r_Data:= data.powermonitor.ar_LineVoltage[1];
	17:		GetPSBData.s_Name:= 'L2-L3';
			GetPSBData.s_Type:= 'AC Linevoltage';
			GetPSBData.s_Unit:= 'VAC';
			GetPSBData.i_precision:= 1;
			GetPSBData.r_Data:= data.powermonitor.ar_LineVoltage[2];
	18:		GetPSBData.s_Name:= 'L3-L1';
			GetPSBData.s_Type:= 'AC Linevoltage';
			GetPSBData.s_Unit:= 'VAC';
			GetPSBData.i_precision:= 1;
			GetPSBData.r_Data:= data.powermonitor.ar_LineVoltage[3];
	19:		GetPSBData.s_Name:= 'L1-N';
			GetPSBData.s_Type:= 'AC Phasevoltage';
			GetPSBData.s_Unit:= 'VAC';
			GetPSBData.i_precision:= 1;
			GetPSBData.r_Data:= data.powermonitor.ar_PhaseVoltage[1];
	20:		GetPSBData.s_Name:= 'L2-N';
			GetPSBData.s_Type:= 'AC Phasevoltage';
			GetPSBData.s_Unit:= 'VAC';
			GetPSBData.i_precision:= 1;
			GetPSBData.r_Data:= data.powermonitor.ar_PhaseVoltage[2];
	21:		GetPSBData.s_Name:= 'L3-N';
			GetPSBData.s_Type:= 'AC Phasevoltage';
			GetPSBData.s_Unit:= 'VAC';
			GetPSBData.i_precision:= 1;
			GetPSBData.r_Data:= data.powermonitor.ar_PhaseVoltage[3];					
	22:		GetPSBData.s_Name:= 'Rotation field';
			GetPSBData.s_Type:= 'AC';
			GetPSBData.s_Unit:= SEL(data.Powerstatus.b_RotaryField, 'RIGHT', 'LEFT');
	23: 	GetPSBData.s_Name:= 'Energy in';                 
			GetPSBData.s_Type:= 'Energy'; 
			GetPSBData.s_Unit:= 'kWh';                 
			GetPSBData.i_precision:= 0;
			GetPSBData.b_warning := monitor.powermonitor.outputfield.r_EnergyConsumed < 0;              
			GetPSBData.r_Data:= data.powermonitor.r_EnergyConsumed;
	24: 	GetPSBData.s_Name:= 'Energy out';                 
			GetPSBData.s_Type:= 'Energy'; 
			GetPSBData.s_Unit:= 'kWh';                 
			GetPSBData.i_precision:= 0;
			GetPSBData.b_warning := monitor.powermonitor.outputfield.r_EnergySupplied < 0;              
			GetPSBData.r_Data:= data.powermonitor.r_EnergySupplied;
ELSE	
		RETURN;
END_CASE
]]></ST>
      </Implementation>
    </Method>
    <Method Name="GetSBMUData" Id="{355d51c9-ed30-4d57-9a42-70ab2dcd0b09}" FolderPath="ArrayDataMethods\">
      <Declaration><![CDATA[METHOD GetSBMUData : ST_HMI_Monitor_ArrayDataFormat
VAR_IN_OUT CONSTANT
	data 			: st_SBMU_Status;
END_VAR

VAR_INPUT
	id: INT;
	SBMU_NO	: BYTE;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[CASE ID OF 
	1: 		GetSBMUData.s_Name:= 'Warning word';
			GetSBMUData.s_Type:= 'status';
			GetSBMUData.s_unit:= TO_STRING(data.w_SystemWarning);
	2: 		GetSBMUData.s_Name:= 'Precharge Relay';
			GetSBMUData.s_Type:= 'status';
			GetSBMUData.s_unit:= SEL(data.b_PrechargeRelayClosed, 'OPEN', 'CLOSED');
	3: 		GetSBMUData.s_Name:= 'Positive Relay';
			GetSBMUData.s_Type:= 'status';
			GetSBMUData.s_unit:= SEL(data.b_MainPosRelayClosed,'OPEN', 'CLOSED');
	4: 		GetSBMUData.s_Name:= 'Negative Relay';
			GetSBMUData.s_Type:= 'status';
			GetSBMUData.s_unit:= SEL(data.b_MainNegRelayClosed,'OPEN', 'CLOSED');
	5: 		GetSBMUData.s_Name:= 'Fan';
			GetSBMUData.s_Type:= 'status';
			GetSBMUData.s_unit:= SEL(data.b_ControlBoxFanOn,'ON', 'OFF');
	6: 		GetSBMUData.s_Name:= 'Balance status';
			GetSBMUData.s_Type:= 'status';
			GetSBMUData.s_unit:= SEL(data.b_BalanceStatus,'ON', 'OFF');
	7:		GetSBMUData.s_Name:= 'Voltage';
			GetSBMUData.s_Type:= 'power';
			GetSBMUData.s_Unit:= 'VDC';
			GetSBMUData.i_precision:= 1;
			GetSBMUData.r_Data:= data.BatteryStatus.r_SystemVoltage;
	8:		GetSBMUData.s_Name:= 'Current';
			GetSBMUData.s_Type:= 'power';
			GetSBMUData.s_Unit:= 'A';
			GetSBMUData.i_precision:= 0;
			GetSBMUData.r_Data:= data.BatteryStatus.r_SystemCurrent;
	9:		GetSBMUData.s_Name:= 'Max charge current';
			GetSBMUData.s_Type:= 'limit';
			GetSBMUData.s_Unit:= 'A';
			GetSBMUData.i_precision:= 0;
			GetSBMUData.r_Data:= data.BatteryStatus.r_MaxChargeCurrentAllowed;
	10:		GetSBMUData.s_Name:= 'Max discharge current';
			GetSBMUData.s_Type:= 'limit';
			GetSBMUData.s_Unit:= 'A';
			GetSBMUData.i_precision:= 0;
			GetSBMUData.r_Data:= data.BatteryStatus.r_MaxDischargeCurrentAllowed;
	11:		GetSBMUData.s_Name:= 'Total charge energy';                       
			GetSBMUData.s_Type:= 'energy';                       
			GetSBMUData.s_Unit:= 'kWh';                               
			GetSBMUData.i_precision:= 0;                              
			GetSBMUData.r_Data:= data.BatteryStatus.r_HistAccChargeEnergy;
	12:		GetSBMUData.s_Name:= 'Total discharge energy';                         
			GetSBMUData.s_Type:= 'energy';                                 
			GetSBMUData.s_Unit:= 'kWh';                                         
			GetSBMUData.i_precision:= 0;                                        
			GetSBMUData.r_Data:= data.BatteryStatus.r_HistAccDischargeEnergy;
	13:		GetSBMUData.s_Name:= 'Min. cell temperature';                               
			GetSBMUData.s_Type:= 'cell';                                        
			GetSBMUData.s_Unit:= '°C';                                                
			GetSBMUData.i_precision:= 2;                                               
			GetSBMUData.r_Data:= data.BatteryStatus.ar_CellTemperature[0];
	14:		GetSBMUData.s_Name:= 'Avg. cell temperature';                               
			GetSBMUData.s_Type:= 'cell';                                        
			GetSBMUData.s_Unit:= '°C';                                                
			GetSBMUData.i_precision:= 2;                                               
			GetSBMUData.r_Data:= data.BatteryStatus.ar_CellTemperature[1];	
	15:		GetSBMUData.s_Name:= 'Max. cell temperature';                               
			GetSBMUData.s_Type:= 'cell';                                        
			GetSBMUData.s_Unit:= '°C';                                                
			GetSBMUData.i_precision:= 2;                                               
			GetSBMUData.r_Data:= data.BatteryStatus.ar_CellTemperature[2];
	16:		GetSBMUData.s_Name:= 'Min. cell voltage';                               
			GetSBMUData.s_Type:= 'cell';                                        
			GetSBMUData.s_Unit:= 'VDC';                                                
			GetSBMUData.i_precision:= 2;                                               
			GetSBMUData.r_Data:= monitor.battery.BatteryInfo.ar_Cellvoltage[0];
	17:		GetSBMUData.s_Name:= 'Avg. cell voltage';                               
			GetSBMUData.s_Type:= 'cell';                                        
			GetSBMUData.s_Unit:= 'VDC';                                                
			GetSBMUData.i_precision:= 2;                                               
			GetSBMUData.r_Data:= data.BatteryStatus.ar_CellVoltage[1];	
	18:		GetSBMUData.s_Name:= 'Max. cell voltage';                               
			GetSBMUData.s_Type:= 'cell';                                        
			GetSBMUData.s_Unit:= 'VDC';                                                
			GetSBMUData.i_precision:= 2;                                               
			GetSBMUData.r_Data:= data.BatteryStatus.ar_CellVoltage[2];
	19:		GetSBMUData.s_Name:= 'SOH';
			GetSBMUData.s_Type:= 'status';
			GetSBMUData.s_Unit:= '%';
			GetSBMUData.i_precision:= 1;
			GetSBMUData.r_Data:= data.BatteryStatus.r_SOH;	
	20:		GetSBMUData.s_Name:= 'SOC actual';                          
			GetSBMUData.s_Type:= 'status';                  
			GetSBMUData.s_Unit:= '%';                            
			GetSBMUData.i_precision:= 1;                         
			GetSBMUData.r_Data:= data.BatteryStatus.r_SOC;	
	21: 	GetSBMUData.s_Name:= 'ID';                          
			GetSBMUData.s_Type:= 'ID';                                                                    
			GetSBMUData.r_Data:= SBMU_NO;
	ELSE	
		RETURN;			
END_CASE
]]></ST>
      </Implementation>
    </Method>
    <Method Name="Hour_Minute_To_TOW" Id="{4fd84871-a229-4c04-9ac1-4641aaa901aa}" FolderPath="SchedulerMethods\">
      <Declaration><![CDATA[METHOD PRIVATE Hour_Minute_To_TOW : WORD
VAR_INPUT
	dayofweek: USINT;
	hour	: USINT;
	minute	: USINT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[Hour_Minute_To_TOW := dayofweek * 24 * 60 + hour * 60 + minute;]]></ST>
      </Implementation>
    </Method>
    <Action Name="MapPLCvarsToHMIVars" Id="{1166b49a-6a5d-4f8a-be6d-bc583eb075e4}" FolderPath="MonitorHandlingMethods\">
      <Implementation>
        <ST><![CDATA[//System
	monitoringvars.System.e_SystemState 				:= monitor.system.e_State;
	monitoringvars.System.b_startAllowed				:= monitor.system.b_StartAllowed;
	monitoringvars.System.e_GridMode					:= monitor.system.e_gridmode;
	monitoringvars.System.e_UgridPowermode				:= monitor.system.e_UgridPowermode;
	monitoringvars.System.b_earthingSelected			:= monitor.controlfb.HardSettings.system.e_EarthingSystem <> eEarthingsystems.None;
	monitoringvars.System.b_CustomNameConfigured		:= monitor.system.b_CustomNameConfigured;
	monitoringvars.System.b_SMSnumberConfigured			:= monitor.system.b_SMSnumberConfigured;
	monitoringvars.System.r_averageEfficiency			:= monitor.system.r_AvgEfficiency;
	monitoringvars.System.r_currentEfficiency			:= monitor.system.r_CurrentEfficiency;
	monitoringvars.System.r_RountripEfficiency			:= monitor.system.r_RoundtripEfficiency;
	monitoringvars.System.s_SystemName					:= monitor.system.s_SystemName;
	monitoringvars.System.r_ChargedEnergy				:= monitor.powermonitor.BESS.r_EnergyConsumed;
	monitoringvars.System.r_DischargeEnergy				:= monitor.powermonitor.BESS.r_EnergySupplied;
	monitoringvars.System.b_Alert						:= GVL.b_WarningActive OR GVL.b_NormalShutdownActive OR GVL.b_QuickshutdownActive OR GVL.b_EmergencyShutdownActive OR NOT monitor.system.b_StartAllowed; 
	monitoringvars.System.b_TransportModePending		:= monitor.system.b_TransportModePending;

//AC DC charger
	monitoringvars.AcDcCharger.available				:= settings.Configuration.b_DcCharger AND monitor.AcDcCharger.by_NoModulesInstalled > 0;
	monitoringvars.AcDcCharger.r_AcPower				:= monitor.AcDcCharger.ACmeasurements.ar_ActivePower[0];
	monitoringvars.AcDcCharger.r_AcVoltage				:= monitor.AcDcCharger.ar_ACvoltage[0];
	monitoringvars.AcDcCharger.r_DcPower				:= monitor.AcDcCharger.r_DcPower;
	monitoringvars.AcDcCharger.state					:= TO_STRING(monitor.AcDcCharger.e_SystemStatus);	
	monitoringvars.AcDcCharger.r_AcCurrent				:= monitor.AcDcCharger.ACmeasurements.ar_Current[0];
	monitoringvars.AcDcCharger.r_AcCurrentMax			:= KwToCurrent(monitor.AcDcCharger.r_AvailablePower, monitor.AcDcCharger.ar_ACvoltage[0]);
	monitoringvars.AcDcCharger.r_AcPowerMax				:= monitor.AcDcCharger.r_AvailablePower;
			
//hystorize vars
	historizevars.Inverter.ActivePower					:=monitor.powerstack.r_Activepower;
	historizevars.Inverter.ReactivePower				:=monitor.powerstack.r_Reactivepower;
	historizevars.Inverter.Current						:=monitor.powerstack.r_ACcurrent;
	historizevars.Inverter.Voltage						:=monitor.powerstack.r_ACVoltageSupply;
	historizevars.Inverter.Frequency					:=monitor.powerstack.r_FrequencySupply;
	historizevars.Input.ActivePower						:=monitor.powermonitor.InputField.ar_ActivePower[0];
	historizevars.Input.ReactivePower					:=monitor.powermonitor.InputField.ar_ReactivePower[0];
	historizevars.Input.Current							:=monitor.powermonitor.InputField.ar_Current[0];
	historizevars.Input.Voltage							:=monitor.powermonitor.InputField.ar_LineVoltage[0];
	historizevars.Input.Frequency						:=monitor.powermonitor.InputField.ar_Frequency[0];
	historizevars.Output.ActivePower					:=monitor.powermonitor.OutputField.ar_ActivePower[0];
	historizevars.Output.ReactivePower					:=monitor.powermonitor.OutputField.ar_ReactivePower[0];
	historizevars.Output.Current						:=monitor.powermonitor.OutputField.ar_Current[0];
	historizevars.Output.Voltage						:=monitor.powermonitor.OutputField.ar_LineVoltage[0];
	historizevars.Output.Frequency						:=monitor.powermonitor.OutputField.ar_Frequency[0];
	historizevars.PSB.ActivePower						:=monitor.peakshavebox.Powermonitor.ar_ActivePower[0];
	historizevars.PSB.ReactivePower						:=monitor.peakshavebox.Powermonitor.ar_ReactivePower[0];
	historizevars.PSB.Current							:=monitor.peakshavebox.Powermonitor.ar_Current[0];
	historizevars.PSB.Voltage							:=monitor.peakshavebox.Powermonitor.ar_LineVoltage[0];
	historizevars.PSB.Frequency							:=monitor.peakshavebox.Powermonitor.ar_Frequency[0];
	historizevars.Battery.Current						:=monitor.battery.BatteryInfo.r_SystemCurrent;
	historizevars.Battery.Voltage						:=monitor.battery.BatteryInfo.r_SystemVoltage;
	historizevars.Battery.Power							:=monitor.battery.BatteryInfo.r_SystemPower;
	historizevars.Battery.SOC							:=monitor.battery.BatteryInfo.r_SocScaled;
	historizevars.Charger.ActivePower					:=monitor.AcDcCharger.ACmeasurements.ar_ActivePower[0];
	historizevars.Charger.ReactivePower					:=monitor.AcDcCharger.ACmeasurements.ar_ReactivePower[0];
	historizevars.Charger.Current						:=monitor.AcDcCharger.ACmeasurements.ar_Current[0];
	historizevars.Charger.Voltage						:=monitor.AcDcCharger.ar_ACvoltage[0];
	
//Powercontroller
	Monitoringvars.Powercontroller := monitor.system.PowerController;

//GengridController
	Monitoringvars.GenGridController := monitor.system.GenGridController;

//Switchgear
	Monitoringvars.Switchgear.b_NetContactorState 		:= monitor.powerstack.Netcontactor.b_NetConFb;
	Monitoringvars.Switchgear.b_ACInputState 			:= monitor.ACswitchgear.b_InputContactorfb AND monitor.ACswitchgear.b_InputMCCBfb;
	Monitoringvars.Switchgear.b_ACOutputState 			:= monitor.ACswitchgear.b_OutputMCCBfb;
	Monitoringvars.Switchgear.r_ACInputPower 			:= monitor.powermonitor.InputField.ar_Current[0];
	Monitoringvars.Switchgear.r_ACOutputPower 			:= monitor.powermonitor.OutputField.ar_Current[0];
	Monitoringvars.Switchgear.b_ACDetectedBusbar 		:= monitor.powerstack.b_ACDetected;
	Monitoringvars.Switchgear.b_ACDetectedInput 		:= monitor.powermonitor.InputField.e_ACrotationStatus <> 0;
	Monitoringvars.Switchgear.b_DCCouplingState 		:= monitor.DCswitchgear.b_CouplingState;
	Monitoringvars.Switchgear.b_DCDetected				:= monitor.battery.BatteryInfo.r_SystemVoltage > 120;
	Monitoringvars.Switchgear.r_DCCouplingCurrent 		:= monitor.DCswitchgear.r_Current;
	Monitoringvars.Switchgear.b_PeNeutralLink 			:= monitor.ACswitchgear.b_PENlinkfb;
	Monitoringvars.Switchgear.b_InputSync				:= monitor.ACswitchgear.b_InputSynchronizerfb;
	Monitoringvars.Switchgear.r_ACInputPower			:= monitor.powermonitor.InputField.ar_ActivePower[0];
	Monitoringvars.Switchgear.r_ACOutputPower			:= monitor.powermonitor.OutputField.ar_ActivePower[0];
	Monitoringvars.Switchgear.r_DCCouplingCurrent		:= 0; //monitor.powermonitor.DCbus.?

//Enclosure
	Monitoringvars.enclosure.b_DoorClosedClientPanel 	:= monitor.enclosure.doors.b_ClientpanelDoorClosed;
	Monitoringvars.enclosure.b_DoorClosedControlPanel	:= monitor.enclosure.doors.b_ControlPanelDoorClosed;
	Monitoringvars.enclosure.b_DoorClosedInverter		:= monitor.safety.b_InverterDoorOK;
	Monitoringvars.enclosure.b_HumidityHigh				:= monitor.enclosure.climate.events.b_HumidityHigh;
	Monitoringvars.enclosure.b_HumidityTooHigh			:= monitor.enclosure.climate.events.b_HumidityTooHigh;
	Monitoringvars.enclosure.b_TemperatureHigh			:= monitor.enclosure.climate.events.b_TemperatureHigh;
	Monitoringvars.enclosure.b_TemperatureTooHigh 		:= monitor.enclosure.climate.events.b_TemperatureTooHigh;
	Monitoringvars.enclosure.b_TemperatureLow 			:= monitor.enclosure.climate.events.b_TemperatureLow;
	Monitoringvars.enclosure.b_TemperatureTooLow 		:= monitor.enclosure.climate.events.b_TemperatureTooLow;
	Monitoringvars.enclosure.r_Humidity					:= monitor.enclosure.climate.r_Humidity;
	Monitoringvars.enclosure.r_Temperature 				:= monitor.enclosure.climate.r_Temperature;
	
//Firedetection
	Monitoringvars.firedetection.e_SmokeDetectorState 	:= monitor.protections.FireDetection.SmokeDetectors.State;
	Monitoringvars.firedetection.e_CoDetectorState 		:= monitor.protections.FireDetection.CoDetectors.State;
	Monitoringvars.firedetection.r_CoDetectorLeftValue 	:= monitor.protections.FireDetection.CoDetectors.Value[1];
	Monitoringvars.firedetection.r_CoDetectorRightValue := monitor.protections.FireDetection.CoDetectors.Value[2];
	
//Overcurrent protection
	monitoringvars.OCP.b_InputMCCBstate					:= monitor.ACswitchgear.b_InputMCCBfb;
	monitoringvars.OCP.b_OutputMCCBstate				:= monitor.ACswitchgear.b_OutputMCCBfb;
	monitoringvars.OCP.b_InputOverloadAlarm 			:= monitor.protections.OvercurrentProtection.b_InputAlarm;
	monitoringvars.OCP.b_OutputOverloadAlarm 			:= monitor.protections.OvercurrentProtection.b_OutputAlarm;
	monitoringvars.OCP.b_InputOverloadWarning 			:= monitor.protections.OvercurrentProtection.b_InputWarning;
	monitoringvars.OCP.b_OutputOverloadWarning 			:= monitor.protections.OvercurrentProtection.b_OutputWarning;
	monitoringvars.OCP.r_CurrentPeak 					:= monitor.protections.OvercurrentProtection.r_PeakCurrent;
	monitoringvars.OCP.s_Location 						:= monitor.protections.OvercurrentProtection.s_locationPeak;
	monitoringvars.OCP.t_PeakDuration 					:= monitor.protections.OvercurrentProtection.t_PeakCurrentDuration;
	
//protections
	monitoringvars.protections.b_InsulationOk 			:= monitor.safety.b_InsulationMonitorOK;
	monitoringvars.protections.e_EarthingSystemDetected := monitor.protections.Insulation.e_EarthingSystemDetected;
	monitoringvars.protections.b_InsulationAlarm 		:= NOT monitor.safety.b_InsulationMonitorOK;
	monitoringvars.protections.b_InsulationPenDetected 	:= monitor.protections.Insulation.b_PENlinkDetected;
	monitoringvars.protections.b_InsulationEnable 		:= monitor.protections.Insulation.b_Enabled;
	monitoringvars.protections.b_InsulationWarning 		:= monitor.protections.Insulation.b_Warning;
	monitoringvars.protections.b_MrcdbWarning			:= monitor.protections.MRCDB.b_prewarning;
	monitoringvars.protections.b_MrcdbOK 				:= monitor.safety.b_MRCDBOK;
	monitoringvars.protections.b_MrcdbAlarm 			:= NOT monitor.safety.b_MRCDBOK;
	monitoringvars.protections.b_SurgeType12OK 			:= monitor.protections.Surge.b_Type12_OK;
	monitoringvars.protections.b_SurgeType3OK 			:= monitor.protections.Surge.b_Type3_OK;

	
//UPS
	monitoringvars.UPS.b_BatteryLowCritical				:= monitor.internalpsu.UPS.Events.b_BatteryLowError;
	monitoringvars.UPS.b_BatteryLowWarning				:= monitor.internalpsu.UPS.Events.b_BatteryLowWarning;
	monitoringvars.UPS.b_BatteryLowInfo					:= monitor.internalpsu.UPS.Events.b_BatteryLowInfo;
	monitoringvars.UPS.b_ChargerActive					:= monitor.internalpsu.UPS.b_ChargerActive;
	monitoringvars.UPS.b_InputVoltageFault				:= monitor.internalpsu.UPS.Events.b_InputVoltageWarning;
	monitoringvars.UPS.b_SupplyOnBattery				:= monitor.internalpsu.UPS.b_SystemOnBattery;
	monitoringvars.UPS.r_BatteryVoltage					:= monitor.internalpsu.UPS.r_BatteryVoltage;
	monitoringvars.UPS.r_InputVoltage					:= monitor.internalpsu.UPS.r_InputVoltage;
	monitoringvars.UPS.r_OutputVoltage					:= monitor.internalpsu.UPS.r_OutputVoltage;
	monitoringvars.UPS.r_OutputCurrent					:= monitor.internalpsu.UPS.r_OutputCurrent;
	monitoringvars.UPS.ui_SoC							:= monitor.internalpsu.UPS.ui_SOC;
	
//Internal powersupply
	monitoringvars.IPSU.b_24VdcOK						:= monitor.internalpsu.b_24VdcAvailable;
	monitoringvars.IPSU.b_400VacOK						:= monitor.internalpsu.b_400VACAvailable;
	monitoringvars.IPSU.b_HvdcOK						:= monitor.internalpsu.b_HVDCAvailable;
	monitoringvars.IPSU.e_400VSource					:= monitor.internalpsu.e_400VSupplySource;
	monitoringvars.IPSU.b_CeeFuseOK						:= NOT(monitor.internalpsu.Events.b_CEEInputFuseTripped);
	monitoringvars.IPSU.b_GridFuseOK					:= NOT(monitor.internalpsu.Events.b_GridInputFuseTripped);
	
//Zeropoint transformer
	monitoringvars.ZPT.b_ZPTOverloadAlarm				:= monitor.neutraltransformer.events.b_OvercurrentAlarm OR monitor.neutraltransformer.events.b_NeutralCurrentTooHigh;
	monitoringvars.ZPT.b_ZPTOverloadWarning				:= monitor.neutraltransformer.events.b_OvercurrentWarning OR monitor.neutraltransformer.events.b_NeutralCurrentHigh;
	monitoringvars.ZPT.b_VoltageUnbalanceAlarm			:= monitor.neutraltransformer.events.b_VoltageUnbalanceTooHigh;
	monitoringvars.ZPT.b_VoltageUnbalanceWarning		:= monitor.neutraltransformer.events.b_VoltageUnbalanceHigh;
	monitoringvars.ZPT.r_TemperatureL1					:= monitor.neutraltransformer.r_TemperaturePhase[1];
	monitoringvars.ZPT.r_TemperatureL2					:= monitor.neutraltransformer.r_TemperaturePhase[2];
	monitoringvars.ZPT.r_TemperatureL3					:= monitor.neutraltransformer.r_TemperaturePhase[3];
	monitoringvars.ZPT.r_voltageunbalance				:= monitor.powermonitor.OutputField.r_VoltageUnbalance;
	monitoringvars.ZPT.r_powerload						:= monitor.neutraltransformer.r_Powerload;
	monitoringvars.ZPT.b_TempWarningL1					:= monitor.neutraltransformer.events.b_TemperatureHighPhase[1];
	monitoringvars.ZPT.b_TempWarningL2					:= monitor.neutraltransformer.events.b_TemperatureHighPhase[2];
	monitoringvars.ZPT.b_TempWarningL3					:= monitor.neutraltransformer.events.b_TemperatureHighPhase[3];
	monitoringvars.ZPT.b_TempAlarmL1					:= monitor.neutraltransformer.events.b_TemperatureTooHighPhase[1];
	monitoringvars.ZPT.b_TempAlarmL2					:= monitor.neutraltransformer.events.b_TemperatureTooHighPhase[2];
	monitoringvars.ZPT.b_TempAlarmL3					:= monitor.neutraltransformer.events.b_TemperatureTooHighPhase[3];

//connections
	monitoringvars.Connections.b_IoTEnabled				:= Iotcontrolvars.b_Active;
	monitoringvars.Connections.e_IoTConnectionState		:= IoTcontrolvars.e_ConnectionState;
	monitoringvars.Connections.b_ExtControllerEnabled	:= PNcontrolvars.b_Active;
	monitoringvars.Connections.e_ExtConnectionState		:= PNcontrolvars.e_ConnectionState;
	monitoringvars.Connections.s_OutputJson				:= PNcontrolvars.s_OutputJson;
	monitoringvars.Connections.b_PsbOK					:= monitor.peakshavebox.b_buscouplerReady;
	monitoringvars.Connections.e_ActiveController		:= controlvars.HardSettings.setup.e_ControlSource;
	monitoringvars.Connections.e_EthercatState			:= monitor.PLC.e_EthercatState;
	monitoringvars.Connections.e_ProfinetState			:= monitor.PLC.e_ProfinetState;
	monitoringvars.Connections.r_CPUload				:= monitor.PLC.r_CPUload;
	
//battery
	monitoringvars.Battery.r_SoCReal					:= monitor.battery.BatteryInfo.r_SOC;
	monitoringvars.Battery.e_status						:= monitor.battery.BatteryInfo.e_BMS_Status;
	monitoringvars.Battery.r_SocScaled					:= monitor.battery.BatteryInfo.r_SOCScaled;
	monitoringvars.Battery.r_MaxDischargePower			:= monitor.battery.BatteryInfo.r_MaxDischargePowerAllowed;
	monitoringvars.Battery.r_MaxChargePower				:= monitor.battery.BatteryInfo.r_MaxChargePowerAllowed;
	monitoringvars.Battery.r_CellTempMin				:= monitor.battery.BatteryInfo.ar_CellTemperature[eSubValues.Minimum];
	monitoringvars.Battery.r_CellTempMax				:= monitor.battery.BatteryInfo.ar_CellTemperature[eSubValues.Maximum];													
	monitoringvars.Battery.r_CellVoltageMin				:= monitor.battery.BatteryInfo.ar_CellVoltage[eSubValues.Minimum];
	monitoringvars.Battery.r_CellVoltageMax				:= monitor.battery.BatteryInfo.ar_CellVoltage[eSubValues.Maximum];								
	monitoringvars.Battery.r_SoH						:= monitor.battery.BatteryInfo.r_SOH;
	monitoringvars.Battery.r_DCcurrent					:= monitor.battery.BatteryInfo.r_SystemCurrent;
	monitoringvars.Battery.r_DCvoltage					:= monitor.battery.BatteryInfo.r_SystemVoltage;
	monitoringvars.Battery.r_NetRemainingCapacity		:= monitor.battery.BatteryInfo.r_RemainingDischargeEnergyNett;
	monitoringvars.Battery.ui_CycleCount				:= monitor.battery.BatteryInfo.ui_CycleCount;
	
//Powerstack
	monitoringvars.Powerstack.b_ACDetected				:= monitor.powerstack.b_GridACdetected;
	monitoringvars.Powerstack.b_DCDetected				:= monitor.powerstack.b_DCDetected;
	monitoringvars.Powerstack.b_StartedState			:= monitor.powerstack.b_StartedState;
	monitoringvars.Powerstack.b_ControlEnabled			:= monitor.powerstack.b_ControlEnabled;
	monitoringvars.Powerstack.b_MasterEnabled			:= monitor.powerstack.PowermoduleMaster.b_online;
	monitoringvars.Powerstack.b_SlaveEnabled			:= monitor.powerstack.PowermoduleSlave.b_online AND settings.Configuration.b_DoublePowerModule;
	monitoringvars.Powerstack.r_ActivePower				:= monitor.powerstack.r_ActivePower;
	monitoringvars.Powerstack.r_DcPower					:= monitor.powerstack.r_Dcpower;
	monitoringvars.Powerstack.r_Powerload				:= monitor.powerstack.r_LoadPercent;
	monitoringvars.Powerstack.e_MasterState				:= monitor.powerstack.Powermodulemaster.e_Status;
	monitoringvars.Powerstack.e_SlaveState				:= monitor.powerstack.Powermoduleslave.e_Status;
	monitoringvars.Powerstack.b_MasterCurrThrotActive	:= monitor.powerstack.PowermoduleMaster.Events.b_CurrThrottlingActive;
	monitoringvars.Powerstack.b_MasterTempThrotActive	:= monitor.powerstack.PowermoduleMaster.Events.b_TempThrottlingActive;
	monitoringvars.Powerstack.r_MasterthrotValue		:= monitor.powerstack.PowermoduleMaster.r_OverCurrentValue;
	monitoringvars.Powerstack.b_MasterWarning			:= monitor.powerstack.Events.b_MasterWarning;
	monitoringvars.Powerstack.b_MasterMCCBfb			:= monitor.powerstack.PowermoduleMaster.b_MccbFb;
	monitoringvars.Powerstack.b_SlaveCurrThrotActive	:= monitor.powerstack.PowermoduleSlave.Events.b_CurrThrottlingActive;
	monitoringvars.Powerstack.b_SlaveTempThrotActive	:= monitor.powerstack.PowermoduleSlave.Events.b_TempThrottlingActive;
	monitoringvars.Powerstack.r_SlavethrotValue			:= monitor.powerstack.PowermoduleSlave.r_OverCurrentValue;
	monitoringvars.Powerstack.b_SlaveWarning			:= monitor.powerstack.Events.b_SlaveWarning;
	monitoringvars.Powerstack.b_SlaveMCCBfb				:= monitor.powerstack.PowermoduleSlave.b_MccbFb;
	monitoringvars.Powerstack.r_throttlingValue			:= monitor.powerstack.r_OvercurrentValueAct;
	monitoringvars.Powerstack.e_NetContState			:= monitor.powerstack.Netcontactor.e_NetConState;
	monitoringvars.powerstack.e_StatusPowerStack		:= monitor.powerstack.e_State;
	monitoringvars.Powerstack.e_ACrotationState			:= monitor.powermonitor.OutputField.e_ACrotationStatus;
	monitoringvars.Powerstack.b_islandOperation			:= monitor.powerstack.b_InverterGridFormingMode;
	
//Coolingsystem
	monitoringvars.cooling.e_OperationMode 				:= monitor.Cooling.CoolingSystemMode;
	monitoringvars.cooling.r_CoolantPressure			:= monitor.Cooling.r_CoolantPressure;
	monitoringvars.cooling.r_CoolantTemperature			:= monitor.Cooling.r_CoolantTemperature;
	monitoringvars.cooling.r_EnclosureDewpoint			:= monitor.Cooling.r_EnclosureDewpoint;
	monitoringvars.cooling.e_HeatPumpStatus				:= monitor.Cooling.HeatPumpStatus;
	monitoringvars.cooling.b_HeatPumpError				:= monitor.Cooling.Events.b_HeatpumpWarning;
	monitoringvars.cooling.b_HeatPumpWarning			:= monitor.Cooling.Events.b_HeatpumpError;
	monitoringvars.cooling.b_CoolantPressureError		:= monitor.Cooling.Events.b_CoolingLoopIdlePressureError OR monitor.Cooling.Events.b_InverterCoolingLoopError;
	monitoringvars.cooling.b_CoolantPressureWarning		:= monitor.Cooling.Events.b_CoolingLoopIdlePressureWarning;
	monitoringvars.cooling.b_CoolantTempWarning			:= monitor.Cooling.Events.b_SystemOvertemperatureWarning OR monitor.Cooling.Events.b_SystemUndertemperatureWarning;
	
//control feedback
	monitoringvars.controlfb 							:= monitor.controlfb.control;
	
//limits
	monitoringvars.Limits.r_ACcurrentLimit				:= 650;
	monitoringvars.Limits.r_ApparentPowerlimit			:= 450;
	monitoringvars.Limits.r_ActivePowerlimit			:= 360;
	monitoringvars.Limits.r_DCcurrentLimit				:= monitor.battery.BatteryInfo.r_ratedCurrent;
	monitoringvars.limits.r_DroopLimit 					:= settings.MachineParams.Powerstack.r_DroopMaximum;
	
//ConditionalFormatting
	ConditionalFormatting(monitoringvars.ConditionalFormatting, controlvars);
	
//PSB
	monitoringvars.PSB.b_Connected 						:= monitor.peakshavebox.b_buscouplerReady;
	monitoringvars.PSB.b_Active							:= monitor.peakshavebox.b_active;
]]></ST>
      </Implementation>
    </Action>
    <Method Name="ResetControlvarsOnVariant" Id="{f7df607d-9743-4bb9-a8dd-30ad9d8c8fd1}" FolderPath="ControlsHandlingMethods\">
      <Declaration><![CDATA[METHOD ResetControlvarsOnVariant : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF NOT settings.Configuration.b_ACInputConnection THEN
	controlvars.SoftSettings.setup.e_AcInputType := eACInputType.None;
END_IF
]]></ST>
      </Implementation>
    </Method>
    <Method Name="ResetHMIvarsOnEvent" Id="{ec0fbc6c-351a-466b-975b-6461819ae91a}" FolderPath="ControlsHandlingMethods\">
      <Declaration><![CDATA[METHOD ResetHMIvarsOnEvent

VAR_INST
	
END_VAR

]]></Declaration>
      <Implementation>
        <ST><![CDATA[rTrigResetPowerSetpoints(CLK:= NOT monitor.powerstack.b_StartedState); //monitor.controlfb.HardSettings.setup.e_ControlSource <> 0 OR monitor.system.e_gridmode <> eGridmode.forming);

IF rTrigResetPowerSetpoints.Q THEN
	Controlvars.Operation.system.r_PFset := 1;
	controlvars.Operation.system.r_Pset := 0;
	controlvars.Operation.system.r_Qset := 0;
	controlvars.control.b_start := FALSE;
	controlvars.control.b_stop := FALSE;
END_IF

IF monitor.controlfb.Operation.system.b_GridTakeOverEnable AND monitor.powerstack.b_InverterGridFormingMode THEN
	controlvars.Operation.system.r_Pset := monitor.powerstack.r_ActivePower;
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="SetArraydata" Id="{d229777b-dbdb-4148-ba6c-0979fccd3c91}" FolderPath="ArrayDataMethods\">
      <Declaration><![CDATA[METHOD SetArraydata : BOOL

VAR_IN_OUT
	arrays			: ST_HMI_Monitor_Arraydata;
	init			: BOOL;
END_VAR

VAR_INPUT
	b_sync			: BOOL;
END_VAR

VAR
	index				: INT ;	
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF b_sync OR init THEN
	FOR index := 1 TO (SIZEOF(Arrays.ACInputData) / SIZEOF(st_HMIData)) DO
		DataToHMIArrayFormat(data:= GetAcInputArrayData(data := monitor.powermonitor.inputfield, id:=index), init:= init, st_DataOut := arrays.ACInputData[index]);
	END_FOR
	FOR index := 1 TO (SIZEOF(Arrays.ACOutputData) / SIZEOF(st_HMIData)) DO
		DataToHMIArrayFormat(data:= GetAcOutputArrayData(data := monitor.powermonitor.OutputField, id:=index), init:= init, st_DataOut := arrays.ACOutputData[index]);
	END_FOR
	FOR index := 1 TO (SIZEOF(Arrays.PowerstackData) / SIZEOF(st_HMIData)) DO
		DataToHMIArrayFormat(data:= GetPowerstackArrayData(id:=index), init:= init, st_DataOut := arrays.PowerstackData[index]);
	END_FOR
	FOR index := 1 TO (SIZEOF(Arrays.PmMasterData) / SIZEOF(st_HMIData)) DO
		DataToHMIArrayFormat(data:= GetPowerModuleArrayData(data := monitor.powerstack.PowermoduleMaster, id:=index), init:= init, st_DataOut := arrays.PmMasterData[index]);
	END_FOR
	IF settings.Configuration.b_DcCharger OR INIT THEN
		FOR index := 1 TO (SIZEOF(Arrays.AcDcChargerData) / SIZEOF(st_HMIData)) DO
			DataToHMIArrayFormat(data:= GetDcChargerData(data := monitor.AcDcCharger, id:=index), init:= init, st_DataOut := arrays.AcDcChargerData[index]);
		END_FOR
	END_IF
	IF settings.Configuration.b_DCbuscoupling OR INIT THEN
		FOR index := 1 TO (SIZEOF(Arrays.DcExtension) / SIZEOF(st_HMIData)) DO
			DataToHMIArrayFormat(data:= GetDcExtData(data := monitor.DCswitchgear, id:=index), init:= init, st_DataOut := arrays.DcExtension[index]);
		END_FOR
	END_IF
	IF settings.Configuration.b_DoublePowerModule THEN
		FOR index := 1 TO (SIZEOF(Arrays.PmSlaveData) / SIZEOF(st_HMIData)) DO
			DataToHMIArrayFormat(data:= GetPowerModuleArrayData(data := monitor.powerstack.PowermoduleSlave, id:=index), init:= init, st_DataOut := arrays.PmSlaveData[index]);
		END_FOR
	END_IF
	IF settings.MachineParams.GenComm.GenControlProtocol <> 0 OR init THEN
		FOR index := 1 TO (SIZEOF(Arrays.Genset) / SIZEOF(st_HMIData)) DO
			DataToHMIArrayFormat(data:= GetGensetData(data := monitor.Generator, id:=index), init:= init, st_DataOut := arrays.Genset[index]);
		END_FOR
	END_IF
	FOR index := 1 TO (SIZEOF(Arrays.PNcontrolData) / SIZEOF(st_HMIData)) DO
		DataToHMIArrayFormat(data:= GetextcontrolData(data := Pncontrolvars, id:=index), init:= init, st_DataOut := arrays.PNcontrolData[index]);
	END_FOR
	
	FOR index := 1 TO (SIZEOF(Arrays.iotcontrolData) / SIZEOF(st_HMIData)) DO
		DataToHMIArrayFormat(data:= GetextcontrolData(data := IOtcontrolvars, id:=index), init:= init, st_DataOut := arrays.IotcontrolData[index]);
	END_FOR
	FOR index := 1 TO (SIZEOF(Arrays.PSBData) / SIZEOF(st_HMIData)) DO
		DataToHMIArrayFormat(data:= GetPSBData(data := Monitor.peakshavebox, id:=index), init:= init, st_DataOut := arrays.PSBData[index]);
	END_FOR
	FOR index := 1 TO (SIZEOF(Arrays.MBMUdata) / SIZEOF(st_HMIData)) DO
		DataToHMIArrayFormat(data:= GetMBMUData(data := monitor.battery.BatteryInfo, id:=index), init:= init, st_DataOut := arrays.MBMUdata[index]);
	END_FOR
	FOR index := 1 TO (SIZEOF(Arrays.SBMU1data) / SIZEOF(st_HMIData)) DO
		DataToHMIArrayFormat(data:= GetSBMUData(data := monitor.battery.SBMU[0], id:=index, 1), init:= init, st_DataOut := arrays.SBMU1data[index]);
	END_FOR
	FOR index := 1 TO (SIZEOF(Arrays.SBMU2data) / SIZEOF(st_HMIData)) DO
		DataToHMIArrayFormat(data:= GetSBMUData(data := monitor.battery.SBMU[1], id:=index, 2), init:= init, st_DataOut := arrays.SBMU2data[index]);
	END_FOR
	FOR index := 1 TO (SIZEOF(Arrays.SBMU3data) / SIZEOF(st_HMIData)) DO
		DataToHMIArrayFormat(data:= GetSBMUData(data := monitor.battery.SBMU[2], id:=index, 3), init:= init, st_DataOut := arrays.SBMU3data[index]);
	END_FOR
	FOR index := 1 TO (SIZEOF(Arrays.SBMU4data) / SIZEOF(st_HMIData)) DO
		DataToHMIArrayFormat(data:= GetSBMUData(data := monitor.battery.SBMU[3], id:=index, 4), init:= init, st_DataOut := arrays.SBMU4data[index]);
	END_FOR
	FOR index := 1 TO (SIZEOF(Arrays.CoolingSystem) / SIZEOF(st_HMIData)) DO
		DataToHMIArrayFormat(data:= GetCoolingData(data := monitor.Cooling, id:=index), init:= init, st_DataOut := arrays.CoolingSystem[index]);
	END_FOR
	FOR index := 1 TO (SIZEOF(Arrays.CoolingSystemHp1) / SIZEOF(st_HMIData)) DO
		DataToHMIArrayFormat(data:= GetHeatpumpData(data := monitor.Cooling.HeatPumpSystem.PrimaryHeatpumpGet, id:=index), init:= init, st_DataOut := Arrays.CoolingSystemHp1[index]);
	END_FOR
	FOR index := 1 TO (SIZEOF(Arrays.CoolingSystemHp2) / SIZEOF(st_HMIData)) DO
		DataToHMIArrayFormat(data:= GetHeatpumpData(data := monitor.Cooling.HeatPumpSystem.SecondaryHeatpumpGet, id:=index), init:= init, st_DataOut := Arrays.CoolingSystemHp2[index]);
	END_FOR
	
END_IF

]]></ST>
      </Implementation>
    </Method>
    <Method Name="SettingsChanged" Id="{78c35c0b-34ec-42b9-bcd7-3f10c45fdf5a}" FolderPath="MonitorHandlingMethods\">
      <Declaration><![CDATA[METHOD SettingsChanged : BOOL

VAR_INPUT
	adr1		: DWORD;
	adr2		: DWORD;
	size		: DWORD;
END_VAR

//VAR_IN_OUT CONSTANT
//	hs_user					: ST_hardsettings;
//	hs_PLC					: ST_hardsettings;
	
//END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[SettingsChanged := (MEMCMP(adr1, adr2, size) <> 0);

]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="HMI">
      <LineId Id="361" Count="28" />
      <LineId Id="80" Count="0" />
    </LineIds>
    <LineIds Name="HMI.ConditionalFormatting">
      <LineId Id="253" Count="26" />
      <LineId Id="86" Count="0" />
    </LineIds>
    <LineIds Name="HMI.CopyActSettingsFromPLC">
      <LineId Id="5" Count="0" />
      <LineId Id="9" Count="0" />
      <LineId Id="15" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="30" Count="0" />
    </LineIds>
    <LineIds Name="HMI.DataToHMIArrayFormat">
      <LineId Id="6" Count="3" />
      <LineId Id="38" Count="0" />
      <LineId Id="41" Count="0" />
      <LineId Id="36" Count="1" />
      <LineId Id="11" Count="3" />
      <LineId Id="24" Count="1" />
      <LineId Id="15" Count="0" />
      <LineId Id="5" Count="0" />
      <LineId Id="53" Count="0" />
      <LineId Id="52" Count="0" />
      <LineId Id="51" Count="0" />
      <LineId Id="54" Count="0" />
    </LineIds>
    <LineIds Name="HMI.GetAcInputArrayData">
      <LineId Id="1103" Count="170" />
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="HMI.GetAcOutputArrayData">
      <LineId Id="170" Count="0" />
      <LineId Id="13" Count="2" />
      <LineId Id="133" Count="2" />
      <LineId Id="281" Count="62" />
      <LineId Id="493" Count="0" />
      <LineId Id="345" Count="29" />
      <LineId Id="259" Count="0" />
      <LineId Id="381" Count="3" />
      <LineId Id="445" Count="0" />
      <LineId Id="385" Count="4" />
      <LineId Id="446" Count="0" />
      <LineId Id="390" Count="4" />
      <LineId Id="447" Count="0" />
      <LineId Id="395" Count="4" />
      <LineId Id="448" Count="0" />
      <LineId Id="280" Count="0" />
      <LineId Id="401" Count="3" />
      <LineId Id="449" Count="0" />
      <LineId Id="405" Count="4" />
      <LineId Id="450" Count="0" />
      <LineId Id="410" Count="4" />
      <LineId Id="451" Count="0" />
      <LineId Id="415" Count="4" />
      <LineId Id="452" Count="0" />
      <LineId Id="400" Count="0" />
      <LineId Id="421" Count="3" />
      <LineId Id="453" Count="0" />
      <LineId Id="425" Count="4" />
      <LineId Id="454" Count="0" />
      <LineId Id="430" Count="4" />
      <LineId Id="455" Count="0" />
      <LineId Id="435" Count="4" />
      <LineId Id="456" Count="0" />
      <LineId Id="420" Count="0" />
      <LineId Id="463" Count="1" />
      <LineId Id="462" Count="0" />
      <LineId Id="482" Count="2" />
      <LineId Id="475" Count="0" />
      <LineId Id="471" Count="0" />
      <LineId Id="470" Count="0" />
      <LineId Id="477" Count="4" />
      <LineId Id="476" Count="0" />
      <LineId Id="380" Count="0" />
      <LineId Id="278" Count="0" />
      <LineId Id="17" Count="0" />
      <LineId Id="277" Count="0" />
    </LineIds>
    <LineIds Name="HMI.GetActiveTimeSlotScheduler">
      <LineId Id="116" Count="0" />
      <LineId Id="127" Count="0" />
      <LineId Id="123" Count="0" />
      <LineId Id="126" Count="0" />
      <LineId Id="177" Count="0" />
      <LineId Id="128" Count="1" />
      <LineId Id="125" Count="0" />
      <LineId Id="81" Count="2" />
      <LineId Id="88" Count="1" />
      <LineId Id="91" Count="1" />
      <LineId Id="109" Count="0" />
      <LineId Id="130" Count="0" />
      <LineId Id="111" Count="1" />
      <LineId Id="131" Count="0" />
      <LineId Id="110" Count="0" />
      <LineId Id="117" Count="1" />
      <LineId Id="154" Count="0" />
      <LineId Id="115" Count="0" />
    </LineIds>
    <LineIds Name="HMI.GetCoolingData">
      <LineId Id="8" Count="6" />
      <LineId Id="115" Count="2" />
      <LineId Id="119" Count="0" />
      <LineId Id="118" Count="0" />
      <LineId Id="120" Count="3" />
      <LineId Id="19" Count="5" />
      <LineId Id="108" Count="1" />
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="HMI.GetDcChargerData">
      <LineId Id="1323" Count="66" />
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="HMI.GetDcExtData">
      <LineId Id="1323" Count="3" />
      <LineId Id="1342" Count="14" />
      <LineId Id="1387" Count="2" />
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="HMI.GetextcontrolData">
      <LineId Id="863" Count="39" />
      <LineId Id="906" Count="64" />
      <LineId Id="977" Count="5" />
      <LineId Id="989" Count="53" />
      <LineId Id="1046" Count="26" />
      <LineId Id="1086" Count="1" />
      <LineId Id="1085" Count="0" />
      <LineId Id="1088" Count="0" />
      <LineId Id="1073" Count="2" />
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="HMI.GetGensetData">
      <LineId Id="868" Count="40" />
      <LineId Id="983" Count="4" />
      <LineId Id="909" Count="0" />
      <LineId Id="915" Count="14" />
      <LineId Id="989" Count="0" />
      <LineId Id="994" Count="0" />
      <LineId Id="999" Count="3" />
      <LineId Id="995" Count="0" />
      <LineId Id="993" Count="0" />
      <LineId Id="992" Count="0" />
      <LineId Id="990" Count="1" />
      <LineId Id="980" Count="2" />
      <LineId Id="277" Count="0" />
    </LineIds>
    <LineIds Name="HMI.GetHeatpumpData">
      <LineId Id="13" Count="6" />
      <LineId Id="38" Count="3" />
      <LineId Id="37" Count="0" />
      <LineId Id="20" Count="4" />
      <LineId Id="42" Count="3" />
      <LineId Id="29" Count="0" />
      <LineId Id="46" Count="3" />
      <LineId Id="34" Count="0" />
      <LineId Id="51" Count="3" />
      <LineId Id="50" Count="0" />
      <LineId Id="56" Count="3" />
      <LineId Id="55" Count="0" />
      <LineId Id="62" Count="3" />
      <LineId Id="61" Count="0" />
      <LineId Id="67" Count="3" />
      <LineId Id="66" Count="0" />
      <LineId Id="71" Count="3" />
      <LineId Id="60" Count="0" />
      <LineId Id="76" Count="2" />
      <LineId Id="84" Count="3" />
      <LineId Id="83" Count="0" />
      <LineId Id="89" Count="3" />
      <LineId Id="88" Count="0" />
      <LineId Id="79" Count="0" />
      <LineId Id="36" Count="0" />
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="HMI.GetMBMUData">
      <LineId Id="421" Count="82" />
      <LineId Id="530" Count="13" />
      <LineId Id="556" Count="1" />
      <LineId Id="555" Count="0" />
      <LineId Id="544" Count="2" />
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="HMI.GetPowerModuleArrayData">
      <LineId Id="477" Count="184" />
      <LineId Id="696" Count="3" />
      <LineId Id="695" Count="0" />
      <LineId Id="701" Count="3" />
      <LineId Id="700" Count="0" />
      <LineId Id="706" Count="3" />
      <LineId Id="705" Count="0" />
      <LineId Id="711" Count="3" />
      <LineId Id="710" Count="0" />
      <LineId Id="716" Count="3" />
      <LineId Id="715" Count="0" />
      <LineId Id="721" Count="3" />
      <LineId Id="738" Count="0" />
      <LineId Id="741" Count="3" />
      <LineId Id="740" Count="0" />
      <LineId Id="746" Count="3" />
      <LineId Id="745" Count="0" />
      <LineId Id="755" Count="0" />
      <LineId Id="752" Count="2" />
      <LineId Id="750" Count="0" />
      <LineId Id="756" Count="3" />
      <LineId Id="739" Count="0" />
      <LineId Id="761" Count="3" />
      <LineId Id="760" Count="0" />
      <LineId Id="766" Count="3" />
      <LineId Id="765" Count="0" />
      <LineId Id="771" Count="3" />
      <LineId Id="770" Count="0" />
      <LineId Id="667" Count="5" />
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="HMI.GetPowerstackArrayData">
      <LineId Id="170" Count="0" />
      <LineId Id="13" Count="2" />
      <LineId Id="281" Count="34" />
      <LineId Id="392" Count="8" />
      <LineId Id="391" Count="0" />
      <LineId Id="316" Count="18" />
      <LineId Id="385" Count="0" />
      <LineId Id="336" Count="2" />
      <LineId Id="341" Count="2" />
      <LineId Id="346" Count="2" />
      <LineId Id="407" Count="10" />
      <LineId Id="406" Count="0" />
      <LineId Id="280" Count="0" />
      <LineId Id="278" Count="0" />
      <LineId Id="17" Count="0" />
      <LineId Id="277" Count="0" />
    </LineIds>
    <LineIds Name="HMI.GetPSBdata">
      <LineId Id="170" Count="0" />
      <LineId Id="13" Count="2" />
      <LineId Id="133" Count="2" />
      <LineId Id="281" Count="24" />
      <LineId Id="503" Count="3" />
      <LineId Id="502" Count="0" />
      <LineId Id="306" Count="9" />
      <LineId Id="326" Count="48" />
      <LineId Id="259" Count="0" />
      <LineId Id="463" Count="1" />
      <LineId Id="462" Count="0" />
      <LineId Id="482" Count="2" />
      <LineId Id="475" Count="0" />
      <LineId Id="471" Count="0" />
      <LineId Id="470" Count="0" />
      <LineId Id="477" Count="4" />
      <LineId Id="476" Count="0" />
      <LineId Id="380" Count="0" />
      <LineId Id="278" Count="0" />
      <LineId Id="17" Count="0" />
      <LineId Id="277" Count="0" />
    </LineIds>
    <LineIds Name="HMI.GetSBMUData">
      <LineId Id="642" Count="94" />
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="HMI.Hour_Minute_To_TOW">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="HMI.MapPLCvarsToHMIVars">
      <LineId Id="2629" Count="23" />
      <LineId Id="2872" Count="0" />
      <LineId Id="2874" Count="0" />
      <LineId Id="2873" Count="0" />
      <LineId Id="2653" Count="25" />
      <LineId Id="2876" Count="1" />
      <LineId Id="2879" Count="0" />
      <LineId Id="2878" Count="0" />
      <LineId Id="2679" Count="188" />
      <LineId Id="534" Count="0" />
    </LineIds>
    <LineIds Name="HMI.ResetControlvarsOnVariant">
      <LineId Id="6" Count="2" />
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="HMI.ResetHMIvarsOnEvent">
      <LineId Id="15" Count="1" />
      <LineId Id="5" Count="1" />
      <LineId Id="8" Count="1" />
      <LineId Id="23" Count="1" />
      <LineId Id="7" Count="0" />
      <LineId Id="32" Count="0" />
      <LineId Id="31" Count="0" />
      <LineId Id="33" Count="1" />
    </LineIds>
    <LineIds Name="HMI.SetArraydata">
      <LineId Id="201" Count="1" />
      <LineId Id="436" Count="0" />
      <LineId Id="321" Count="0" />
      <LineId Id="461" Count="1" />
      <LineId Id="460" Count="0" />
      <LineId Id="480" Count="1" />
      <LineId Id="478" Count="0" />
      <LineId Id="483" Count="1" />
      <LineId Id="482" Count="0" />
      <LineId Id="666" Count="0" />
      <LineId Id="669" Count="1" />
      <LineId Id="667" Count="1" />
      <LineId Id="672" Count="3" />
      <LineId Id="671" Count="0" />
      <LineId Id="627" Count="0" />
      <LineId Id="630" Count="1" />
      <LineId Id="628" Count="1" />
      <LineId Id="646" Count="0" />
      <LineId Id="650" Count="1" />
      <LineId Id="649" Count="0" />
      <LineId Id="648" Count="0" />
      <LineId Id="502" Count="1" />
      <LineId Id="479" Count="0" />
      <LineId Id="609" Count="0" />
      <LineId Id="519" Count="2" />
      <LineId Id="590" Count="1" />
      <LineId Id="589" Count="0" />
      <LineId Id="538" Count="1" />
      <LineId Id="537" Count="0" />
      <LineId Id="541" Count="1" />
      <LineId Id="540" Count="0" />
      <LineId Id="544" Count="1" />
      <LineId Id="543" Count="0" />
      <LineId Id="547" Count="1" />
      <LineId Id="546" Count="0" />
      <LineId Id="550" Count="1" />
      <LineId Id="549" Count="0" />
      <LineId Id="567" Count="1" />
      <LineId Id="566" Count="0" />
      <LineId Id="570" Count="1" />
      <LineId Id="569" Count="0" />
      <LineId Id="573" Count="1" />
      <LineId Id="572" Count="0" />
      <LineId Id="518" Count="0" />
      <LineId Id="322" Count="0" />
      <LineId Id="324" Count="0" />
      <LineId Id="476" Count="0" />
    </LineIds>
    <LineIds Name="HMI.SettingsChanged">
      <LineId Id="49" Count="0" />
      <LineId Id="14" Count="0" />
      <LineId Id="34" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>