<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="WinlineUXR100040G" Id="{bcc9d53c-d926-49d7-a9d7-e15bbef623fc}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK WinlineUXR100040G IMPLEMENTS ACDCChargerElement
VAR_INPUT
END_VAR

VAR_OUTPUT
END_VAR

VAR
	
END_VAR


VAR CONSTANT
	UnitPower	:	Real := 40;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Disable" Id="{6718066a-b33b-4271-b0de-4ea0b20b15bc}">
      <Declaration><![CDATA[METHOD Disable : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Enable" Id="{752dabc4-f475-475c-bbcb-40c8349eda22}">
      <Declaration><![CDATA[METHOD Enable : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="SetPowerLevel" Id="{ebd03c02-44b6-4acf-b972-f4a5bc639d09}">
      <Declaration><![CDATA[METHOD SetPowerLevel : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="WinlineUXR100040G">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="WinlineUXR100040G.Disable">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="WinlineUXR100040G.Enable">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="WinlineUXR100040G.SetPowerLevel">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>