<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FB_GenGridController" Id="{a63d5ed0-c6cf-4c4f-86fc-7fad2a0575f5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_GenGridController
VAR_IN_OUT CONSTANT
	monitor						: ST_System_Monitor;
	st_params					: ST_GenGridController_params;
	control						: ST_System_Control;
END_VAR

VAR_INPUT
	Enable						: BOOL;
	b_ForceOperate				: BOOL;
	b_EMSTOP					: BOOL;
END_VAR

VAR_OUTPUT
	TargetData					: ST_PowerControl_Target;
	InverterMode				: eInverterModes;
	PowerMode					: ePowermodes;
	b_inputContactorClose		: BOOL;
	b_inputContactorOpen		: BOOL;
	b_InputSyncEnable			: BOOL;
	b_ExtContactorClose			: BOOL;
	b_IOStartStop				: BOOL;
	b_NetcontactorHoldClose		: BOOL;
	b_ExtGridConnected			: BOOL;
	b_slowLom					: BOOL;
	get							: ST_GenGridController_get;
END_VAR

VAR
	InputContactor				: FB_ContactorControl;
	ExtContactor				: FB_ContactorControl;
	LoadStart					: FB_StartStop := (GreaterThan := TRUE);
	SocStart					: FB_StartStop := (GreaterThan := FALSE);
	ChargeLoadStart				: FB_StartStop := (GreaterThan := TRUE);
	BatFullStart				: FB_StartStop := (GreaterThan := TRUE);	
		
	b_BreakerACok				: BOOL;
	b_BreakerCMDfb				: BOOL;
	b_Breakerfb 				: BOOL;
	ar_BreakerCurrent			: ARRAY[0..4] OF REAL;
	b_InputACOK					: BOOL;
	b_InputMCCBfb				: BOOL;
	b_BusbarACOK				: BOOL;
	b_ExtACOK					: BOOL;
	b_SFCmodetransInhibit		: BOOL;
	b_GridCodeTripInverter		: BOOL;
	b_GridCodeActive			: BOOL;
	b_GridACDetected			: BOOL;
	b_SkipGensetCooldown		: BOOL;
	b_loadbankEnable			: BOOL;
	b_hybridMode				: BOOL;
	b_ManGenStartStop			: BOOL;
	b_GridTakeOverMode			: BOOL;
	b_AMFEnabled				: BOOL;
	b_autoSwitching				: BOOL;
	b_GenStarted				: BOOL;
	b_GenfreqProtection			: BOOL;
	GenFailCounter				: CTU;
	b_GridcodeOK				: BOOL;
	b_AFEActive					: BOOL;
	r_Soc						: REAL;
	r_ACVoltageBusbar			: REAL;
	b_PSBActive					: BOOL;	
	b_BESSReady					: BOOL;		
	 
	//Scheduler
	b_TimeSlot1					: BOOL;
	b_TimeSlot2					: BOOL;
	
	//Signals
	SFCEnable					: BOOL := TRUE;
	b_StartCondition			: BOOL;
	SFCTransTrigger			: TON := (PT :=T#10MS);
	SFCResetTrigger				: BOOL; // from inside SFC itself
	
	//Genset
	GensetSetpoints				: ST_Genset_Setpoints;
	t_CooldownTime				: TIME;
	t_WarmupTime				: TIME;
	
	//ControlModes
	b_ActivateTransition		: BOOL;
	b_ActivatePowerControl		: BOOL;
	eModeLocal 					: (AFE, UgridDroop, UgridIso, UgridIsland);
	PowerControlMode			: ePowerControlmode;
	BreakerOperationMode		: eBreakerOperationMode;
	ExtGensetEnable				: BOOL;
	
	// future work : eGenPowerTarget 				: (minimum, efficiency, maximum);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//FIRST SETUP IO
InputContactor(monitor := monitor, control := control, SyncData := targetdata.Syncdata, st_params := st_params.Contactor,
	b_FbIn := monitor.ACswitchgear.b_InputContactorfb,
	r_AcVoltageRef := monitor.powermonitor.InputField.ar_LineVoltage[0],
	r_AcFreqRef := monitor.powermonitor.InputField.ar_Frequency[0],
	li_VoltCrossRef := monitor.powermonitor.InputField.li_TimeVoltZeroCrossup,
	li_VoltCrossBus := monitor.peakshavebox.Powermonitor.li_TimeVoltZeroCrossup,
	e_AcRotationRef := monitor.powermonitor.InputField.e_ACrotationStatus,
	e_AcRotationBus := monitor.powermonitor.Outputfield.e_ACrotationStatus,
	b_SyncOK := monitor.ACswitchgear.b_InputSynchronizerfb,
	b_deloadEnable := TRUE,
	ar_current := Monitor.powermonitor.InputField.ar_Current,
	r_Power := Monitor.powermonitor.InputField.ar_ActivePower[0],
	CloseCMD => b_inputContactorClose,
	OpenCMD	=> b_inputContactorOpen,
	SyncEnable => b_InputSyncEnable,
	RotationFault => get.events.b_RotationFieldFault,
	b_deadbus := NOT b_BusbarACOK,
);

ExtContactor(monitor := monitor, control := control, syncdata := targetdata.Syncdata, st_params := st_params.Contactor,
	b_FbIn := monitor.peakshavebox.b_ContactorFb,	 
	r_AcVoltageRef:= monitor.peakshavebox.Powermonitor.ar_LineVoltage[0],
	r_AcFreqRef := monitor.peakshavebox.Powermonitor.ar_Frequency[0],
	li_VoltCrossRef := monitor.peakshavebox.Powermonitor.li_TimeVoltZeroCrossup,
	b_SyncOK := monitor.peakshavebox.b_SyncFb,
	b_deloadEnable := FALSE,
	ar_current := Monitor.peakshavebox.Powermonitor.ar_Current,
	CloseCMD => b_ExtContactorClose,
	b_deadbus := NOT b_BusbarACOK
);

//Map monitor vars to local vars for clearity.
b_ExtACOK := ExtContactor.ACok;
b_InputACOK := InputContactor.ACok AND monitor.ACswitchgear.b_InputMCCBfb AND NOT InputContactor.RotationFault;
b_InputMCCBfb := monitor.ACswitchgear.b_InputMCCBfb;
b_BusbarACOK :=  ACcheck(monitor.powerstack.r_ACVoltageD7 , monitor.powerstack.r_FrequencyD7);
r_ACVoltageBusbar := monitor.powerstack.r_ACVoltageD7;
b_AFEActive	:= monitor.powerstack.b_StartedState AND monitor.powerstack.e_InverterMode = einvertermodes.Afe;
b_TimeSlot1 := control.SoftSettings.system.ScheduleTimeSlot1.b_active;
b_TimeSlot2 := control.SoftSettings.system.ScheduleTimeSlot2.b_active;
SFCEnable := BreakerOperationMode <> eBreakerOperationMode.none AND enable AND NOT get.b_faultActive AND NOT b_EMStop;
b_GridCodeTripInverter := NOT monitor.powerstack.b_GridCodeOK;
b_loadbankEnable := control.softSettings.inputgenset.Loadbank.b_Enable;
b_hybridMode := control.softsettings.inputgenset.b_HydridMode;
b_GridTakeOverMode := (control.Operation.system.b_GridTakeOverEnable AND control.SoftSettings.setup.e_AcInputType = eACInputType.Grid);
get.e_GensetStartStop := GensetStartStop(control.softSettings.inputgenset.b_AutoStartStop, control.Operation.Genset.b_manualStart); 
b_AMFEnabled := control.SoftSettings.system.b_AMF;
//b_AutoResyncGridReco := control.SoftSettings.inputgrid.b_AutoResyncAfterGridRecovery;
b_autoSwitching	:= control.SoftSettings.inputgrid.breaker.AutoConnect;
t_CooldownTime := TO_TIME(TO_DINT(control.softSettings.inputgenset.Generator.ui_CooldownTime) * 60000);
t_WarmUpTime := TO_TIME(TO_DINT(control.softSettings.inputgenset.Generator.ui_WarmupTime) * 60000);
b_GenfreqProtection	:= control.SoftSettings.inputgenset.b_FreqProtectionEnable;
r_soc := Monitor.battery.BatteryInfo.r_SOCScaled;
b_GridCodeActive := control.SoftSettings.inputgrid.b_GridCodesActive;//monitor.powerstack.b_GridCodeCheckActive;
b_GridAcDetected := monitor.powerstack.b_GridACdetected;
b_BreakerACok := SEL(BreakerOperationMode = eBreakerOperationMode.ExtGrid, b_InputACOK, b_ExtACOK);
b_BreakerCMDfb := SEL(BreakerOperationMode = eBreakerOperationMode.ExtGrid, b_inputContactorClose, b_ExtContactorClose);
b_Breakerfb := SEL(BreakerOperationMode = eBreakerOperationMode.ExtGrid, inputcontactor.b_fb, extcontactor.b_fb);
ar_BreakerCurrent := SEL(BreakerOperationMode = eBreakerOperationMode.ExtGrid, inputcontactor.ar_current, extcontactor.ar_current);
b_ActivateTransition := control.Operation.system.b_GenGridModeTrans;
b_PSBActive := monitor.peakshavebox.b_active;
b_BESSReady := monitor.powerstack.b_StartedState;
StartStopConditions((SFCenable OR control.softSettings.setup.b_ExtGenset) AND monitor.powerstack.b_ControlEnabled);

GetControlTarget(
	control:= control,
	monitor := monitor,
	PowerControlMode := PowerControlMode,
	TargetData := TargetData,
	GensetSetpoints := GensetSetpoints,
	b_SFCPIDActivation:= b_ActivatePowerControl,
	b_deload := Inputcontactor.b_Deload OR ExtContactor.b_Deload,
	b_PSBactive := b_PSBactive);

SetBreakerAndPowercontrolMode(
	ACInputType := control.SoftSettings.setup.e_AcInputType,
	GridMode:= control.SoftSettings.setup.e_Gridmode,
	GensetMode := control.softSettings.inputgenset.Generator.e_GensetMode,
	PSBMode := monitor.peakshavebox.PSBmode,
	PSBenable := b_PSBActive, // control.SoftSettings.setup.b_PeakshaveBoxEnable,
	b_Extgenset := control.SoftSettings.setup.b_ExtGenset,
	PowerControlMode := PowerControlMode,
	ExtGensetMode := ExtGensetEnable);
	
SetInverterMode(
	Gridmode := control.SoftSettings.setup.e_Gridmode,
	UgridPowerMode := control.SoftSettings.system.e_UgridPowerMode,
	BreakerMode := BreakerOperationMode,
	PSBMode := monitor.peakshavebox.PSBmode,
	b_inputGridCodeEnabled := b_GridCodeActive AND NOT b_GridTakeOverMode,
	b_gridacDetected := b_GridACDetected, 
	b_PowerstackStarted := monitor.powerstack.b_StartedState,
	b_extFb := ExtContactor.b_fb,
	b_InputFb := InputContactor.b_fb,
	b_AMF := b_AMFEnabled)
;

//SFC actions
SFCtransTrigger(); //timer
GenGridSFC();

//ExtGenset control
ExtGensetControl(
	soft := control.SoftSettings.inputgenset,
	setpoints := gensetsetpoints,
	ExtGensetEnable);

//Get events that give fault states and reset SFC
BundleFaultEvents(events := get.events);

//some resets
SFCReset := NOT SFCEnable OR SFCResetTrigger;
IF NOT monitor.powerstack.b_StartedState THEN
	Genfailcounter.RESET := TRUE;
END_IF
]]></ST>
    </Implementation>
    <Folder Name="ControlTarget Methods" Id="{ead89aff-de93-4c70-a582-b4ea6fc2c144}" />
    <Folder Name="Future Work" Id="{2968c542-117e-4863-ae5e-caa0b8749307}" />
    <Folder Name="Nested Methods" Id="{c1c4e82e-8459-46f1-b4f2-d414785d427e}" />
    <Folder Name="SFC" Id="{9b153395-94b7-4124-aa4b-c8df91853bfd}" />
    <Method Name="BundleFaultEvents" Id="{567f3acc-48d3-44ae-97bd-6228e7e5171d}" FolderPath="Nested Methods\">
      <Declaration><![CDATA[METHOD BundleFaultEvents : BOOL
VAR_IN_OUT
	events : ST_GenGridController_Events;
END_VAR

]]></Declaration>
      <Implementation>
        <ST><![CDATA[get.b_faultActive := 
	//events.b_OverFreqTrip 				OR
	//events.b_UnderFreqTrip				OR
	events.b_StartupFault				OR
	events.b_SynchronisationFault 		OR
	events.b_WarmupFault;
	//events.b_OverloadTrip;

IF get.b_faultActive THEN
	get.e_state := eGenGridState.Init;
END_IF

IF BreakerOperationMode <> eBreakerOperationmode.GridFeedthrough OR BreakerOperationMode <> eBreakerOperationmode.ExtGrid THEN
	events.b_GridLostTrip := FALSE;
END_IF]]></ST>
      </Implementation>
    </Method>
    <Action Name="ContinousActions" Id="{62eeff78-aee4-4a38-8edf-45381e48b6fa}" FolderPath="SFC\">
      <Implementation>
        <ST><![CDATA[//if AMF is enabled, netcontactor must always stay closed.
IF monitor.powerstack.b_ControlEnabled AND (BreakerOperationMode <> eBreakerOperationMode.None AND BreakerOperationMode <> eBreakerOperationMode.GenFix) THEN
	b_NetcontactorHoldClose := b_AMFEnabled;
ELSE
	b_NetcontactorHoldClose := FALSE;
END_IF

]]></ST>
      </Implementation>
    </Action>
    <Method Name="Cooldown" Id="{50f2983a-cd41-4aeb-8138-53d7a2686a22}" FolderPath="Nested Methods\">
      <Declaration><![CDATA[METHOD Cooldown : BOOL
VAR_INPUT
	SynchroneGenMode	: BOOL;
END_VAR

VAR_INST
	t_time				: TIME;
	b_stopfb			: BOOL;
	ton_StopTimeOut		: TON;
	ton_CoolDownTimeOut	: TON;
	tp_releaseTimer		: Tp := (PT := T#20MS);
	r_CurrentThresholdShutdown: REAL := 10;
	b_CurrentDown		: BOOL;
	b_release			: BOOL;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[get.e_state := eGenGridState.Cooldown;
b_release := FALSE;

IF b_SkipGensetCooldown THEN
	ton_StopTimeOut.PT := T#0S;
ELSE
	ton_StopTimeOut.PT :=t_CooldownTime;
END_IF

//Set timers for cooldown and cooldown time out (if nothing happens when stop is given).
ton_StopTimeOut(IN := b_breakerACOK AND b_CurrentDown AND NOT ton_StopTimeOut.Q); 
b_CurrentDown := monitor.powermonitor.InputField.ar_Current[0] < r_CurrentThresholdShutdown;
ton_CoolDownTimeOut(IN:= NOT b_CurrentDown AND NOT b_IOStartStop AND NOT ton_CoolDownTimeOut.Q, PT:=t_CooldownTime + T#3M);

IF SynchroneGenMode THEN
	b_IOStartStop := FALSE;
	get.b_gensetHot := FALSE;
	b_release := NOT b_IOStartStop AND b_CurrentDown OR ton_CoolDownTimeOut.Q;
ELSE
	IF ton_StopTimeOut.Q OR NOT b_breakerACOK THEN
		ton_StopTimeOut.IN := FALSE;
		b_IOStartStop := FALSE;	
		b_release := TRUE;
		get.b_gensetHot := FALSE;
	END_IF
END_IF

IF ton_CoolDownTimeOut.Q THEN
	get.events.b_ShutdownTimeOut := TRUE;	
END_IF

tp_releaseTimer(IN :=b_release AND NOT tp_releaseTimer.Q, Q => COOLDOWN);
//cooldown := b_release;]]></ST>
      </Implementation>
    </Method>
    <Method Name="CurrentLimitProtection" Id="{071db2d4-0863-4796-85e0-1ee3ea030d8e}" FolderPath="Nested Methods\">
      <Declaration><![CDATA[METHOD CurrentLimitProtection : BOOL
VAR_INPUT
	enable				: BOOL;
	FeedinLimit 		: REAL;
	SupplyLimit			: REAL;
	Current				: REAL;
	Power				: REAL;
	TripDelay			: TIME := T#5S;
END_VAR

VAR_INST
	Direction			: SINT;
	ton_DelayTimer		: TON;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[ton_DelayTimer(PT := TripDelay, Q => CurrentLimitProtection);

IF Current * LIMIT(-1, power, 1) < 0 AND enable THEN
	ton_DelayTimer.IN := ABS(Current) > ABS(supplyLimit + st_params.by_CurrentLimitMargin);
ELSIF Current * LIMIT(-1, power, 1) > 0 AND enable THEN
	ton_DelayTimer.IN := ABS(Current) > ABS(feedinLimit + st_params.by_CurrentLimitMargin);
ELSE
	ton_DelayTimer.IN := FALSE;
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="ExtGensetControl" Id="{aa23766a-22fe-4b57-b35f-aac428f9eabe}" FolderPath="Nested Methods\">
      <Declaration><![CDATA[METHOD ExtGensetControl : BOOL

VAR_IN_OUT CONSTANT
	soft		: ST_SoftSettings_Genset;
END_VAR

VAR_IN_OUT
	setpoints 	: ST_Genset_setpoints;
END_VAR

VAR_INPUT
	enable				: BOOL;
END_VAR

VAR_INST
	trip				: BOOL;
	rtrigreset			: R_TRIG;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF enable THEN
	get.e_GensetMode := eGensetmode.FixedPower;
	IF b_TimeSlot2 THEN
		setpoints := soft.setpointTimeslot2;
	ELSE 
		setpoints := soft.setpointTimeslot1;
	END_IF
	
	//set trip
	trip := GenFreqVoltProtections(TRUE, TRUE ,NOT enable OR control.control.b_Reset, 0);
	
	IF trip THEN
		b_IOstartstop := FALSE;
	ELSE
		b_IOstartStop := b_startcondition;
	END_IF	
END_IF
 
	//Reset OCP trip
rTrigReset(CLK := NOT enable OR control.control.b_Reset);
IF rtrigReset.Q THEN
	b_IOstartstop := FALSE;
END_IF
	]]></ST>
      </Implementation>
    </Method>
    <Method Name="ExtIOControl" Id="{e65d5cdd-afb1-4525-a0b5-da6e6ea3967e}" FolderPath="Future Work\">
      <Declaration><![CDATA[METHOD ExtIOControl : BOOL
VAR_INPUT
	r_Power	: REAL;
	r_RatedPower : REAL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="GenDownCheck" Id="{ce419edb-2ed4-49ed-a1db-2010618df4f7}" FolderPath="Nested Methods\">
      <Declaration><![CDATA[METHOD GenDownCheck : BOOL
VAR_INPUT
	enable				: BOOL;
	reset				: BOOL;
END_VAR

VAR_INST
	GenFailLimitReached			: BOOL;
	r_ActivePower				: REAL;
	ton_FlatZeroPowerTimeOut 	: TON := (PT:= T#3S);
	ton_reversePowerTrip		: TON := (PT:= T#1S);
	ton_EnableRelease			: TON := (PT:= T#2S);
	ton_GenStartTimeOut			: TON := (PT:= T#1M);
	
	rTrigStarted				: R_Trig;
	
	GenDown						: BOOL;
	i_reversePowerThreshold		: INT := 10; 
	r_FreqLowLimit				: REAL := 49;
	
	GendownTrigger				: STRING;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[r_ActivePower := monitor.powermonitor.InputField.ar_ActivePower[0];

//rTrigStarted(CLK :=  r_ActivePower > 1 OR r_ActivePower < -1);
IF r_ActivePower > 1 OR r_ActivePower < -1 THEN
	b_genStarted := TRUE;
END_IF

ton_GenStartTimeOut(IN := ton_EnableRelease.Q AND NOT b_genStarted);
IF ton_GenStartTimeOut.Q THEN
	get.events.b_StartupFault := TRUE;
END_IF

IF reset AND NOT get.events.b_GenDownTrip THEN
	GenDown := FALSE;
	GendownTrigger := '';
	ton_FlatZeroPowerTimeOut.IN := FALSE;
	ton_reversePowerTrip.IN := FALSE;
END_IF

ton_EnableRelease(IN := enable);
ton_reversePowerTrip();
ton_FlatZeroPowerTimeOut();

IF ton_EnableRelease.Q THEN
	ton_reversePowerTrip.IN := NOT b_loadbankEnable AND r_ActivePower > i_reversePowerThreshold;
	ton_FlatZeroPowerTimeOut.IN := LIMIT(-0.5, r_ActivePower, 0.5) = r_ActivePower AND NOT RESET AND b_breakerFB AND b_IOStartStop AND b_GenStarted;
ELSE
	ton_reversePowerTrip.IN := FALSE;
	ton_FlatZeroPowerTimeOut.IN := FALSE;
END_IF

IF (*ton_FlatZeroPowerTimeOut.Q*) ZeroCurrentDisconnect() THEN
	GenDownTrigger := 'zero power trigger';
ELSIF ton_reversePowerTrip.Q THEN
	GenDownTrigger := 'reverse power trigger';
ELSIF SEL(b_GenfreqProtection, FALSE, GenFreqVoltProtections(FALSE, GenFailLimitReached, reset, r_ActivePower)) THEN
	GenDownTrigger := 'Frequency protections trigger';
END_IF

IF GenDownTrigger <> '' THEN	
	IF GenFailLimitReached THEN
		get.events.b_GenDownTrip := TRUE;
	END_IF	 
	GenDown := TRUE;
	b_genStarted := FALSE;
END_IF

GenFailCounter(CU := GenDown, PV := st_params.Genset.GenDownRetries, Q=>GenFailLimitReached, RESET := reset AND get.events.b_GenDownTrip);

IF NOT b_IOStartStop THEN
	b_genStarted := FALSE;
END_IF
GenDownCheck := GenDown;
 ]]></ST>
      </Implementation>
    </Method>
    <Method Name="GenFreqVoltProtections" Id="{a8a20dfe-25e8-4463-911a-a5b1a631debc}" FolderPath="Nested Methods\">
      <Declaration><![CDATA[METHOD GenFreqVoltProtections : BOOL
VAR_INPUT
	FixedPowerOverloadProtect : BOOL;
	enableEvents	: BOOL;
	reset : BOOL;
	Power : REAL;
END_VAR

VAR_INST
	ton_OCPDelay			: TON := (PT := T#3S);
	ton_OverFreqTripDelay 	: TON := (PT := T#3S);
	ton_UnderFreqTripDelay 	: TON := (PT := T#3S);
	ton_OverVoltTripDelay 	: TON := (PT := T#3S);
	ton_UnderVoltTripDelay 	: TON := (PT := T#3S);
	b_TripDetected			: BOOL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ton_UnderFreqTripDelay(PT := TO_TIME(ST_params.Genset.UnderfrequencyTripDelay));
ton_OverFreqTripDelay(PT := TO_TIME(ST_params.Genset.OverfrequencyTripDelay));
ton_UnderVoltTripDelay(PT := TO_TIME(ST_params.Genset.UnderVoltageTripDelay));
ton_OverVoltTripDelay(PT := TO_TIME(ST_params.Genset.OverVoltageTripDelay));
ton_OCPDelay(PT := TO_TIME(ST_params.Genset.OverloadTripDelay));

IF reset THEN
	ton_OverFreqTripDelay.IN := FALSE;
	ton_UnderFreqTripDelay.IN := FALSE;
	ton_OverVoltTripDelay.IN := FALSE;
	ton_UnderVoltTripDelay.IN := FALSE;
	ton_OCPDelay.IN := FALSE;
ELSIF monitor.powerstack.b_StartedState THEN
	//Overfrequency protection
	ton_OverFreqTripDelay.IN := monitor.powerstack.r_FrequencyD7 > st_params.Genset.OverFrequencyLimit;
	IF ton_OverFreqTripDelay.Q THEN
		get.events.b_OverFreqTrip := TRUE;
	END_IF
	
	ton_UnderFreqTripDelay.IN := monitor.powerstack.r_FrequencyD7 < st_params.Genset.UnderFrequencyLimit;
	IF ton_UnderFreqTripDelay.Q THEN
		get.events.b_UnderFreqTrip := TRUE;
	END_IF
	
	ton_OvervoltTripDelay.IN := monitor.powerstack.r_ACVoltageD7 > st_params.Genset.OverVoltageLimit AND NOT FixedPowerOverloadProtect;
	IF ton_OverVoltTripDelay.Q THEN
		get.events.b_OverVoltTrip := TRUE;
	END_IF
	
	ton_UnderVoltTripDelay.IN := monitor.powerstack.r_ACVoltageD7 < st_params.Genset.UnderVoltageLimit AND NOT FixedPowerOverloadProtect;
	IF ton_UnderVoltTripDelay.Q THEN
		get.events.b_UnderVoltTrip := TRUE;
	END_IF
	
	//Overcurrent protection
	ton_OCPDelay.IN := FixedPowerOverloadProtect AND monitor.powerstack.r_LoadPercent > monitor.powerstack.r_OvercurrentValueAct * 100 AND monitor.powerstack.e_PowerState = ePowerstate.Charging;
	IF ton_OCPDelay.Q THEN
		get.events.b_OverloadTrip := TRUE;
	END_IF
END_IF

b_TripDetected := get.events.b_OverloadTrip 
	OR get.events.b_OverFreqTrip 
	OR get.events.b_UnderFreqTrip
	OR get.events.b_OverVoltTrip
	OR get.events.b_UnderVoltTrip;

IF NOT enableEvents THEN
	get.events.b_OverFreqTrip := FALSE;
	get.events.b_OverloadTrip := FALSE;
	get.events.b_OverVoltTrip := FALSE;
	get.events.b_UnderVoltTrip := FALSE;
	get.events.b_UnderFreqTrip := FALSE;
END_IF

GenFreqVoltProtections := b_TripDetected;]]></ST>
      </Implementation>
    </Method>
    <Action Name="GenGridSFC" Id="{7b135b84-cd18-4d6a-b3d2-35f15ae5881a}" FolderPath="SFC\">
      <Implementation>
        <SFC>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="SFCImplementationObject">
                <o n="Root" t="SFCSegment">
                  <o n="ElementList" t="SFCElementList">
                    <l2 n="InnerList">
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"INIT"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">3L</v>
                            <v n="IdParent">2L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">4L</v>
                            <v n="IdParent">2L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">5L</v>
                            <v n="IdParent">2L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">6L</v>
                            <v n="IdParent">2L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"TRUE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">7L</v>
                            <v n="IdParent">2L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">8L</v>
                            <v n="IdParent">2L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"T#2s"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">9L</v>
                            <v n="IdParent">2L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">10L</v>
                            <v n="IdParent">2L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"INIT_active"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">11L</v>
                            <v n="IdParent">2L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">12L</v>
                            <v n="IdParent">2L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"SFCtipReset"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">13L</v>
                            <v n="IdParent">2L</v>
                          </o>
                        </l2>
                        <v n="Id">2L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"INIT__to__IDLE"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"SFCEnable"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">15L</v>
                            <v n="IdParent">14L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">16L</v>
                            <v n="IdParent">14L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">17L</v>
                            <v n="IdParent">14L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">18L</v>
                            <v n="IdParent">14L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">19L</v>
                            <v n="IdParent">14L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">20L</v>
                            <v n="IdParent">14L</v>
                          </o>
                        </l2>
                        <v n="Id">14L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" cet="SFCActionAssociation">
                            <o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"ContinousActions"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">182L</v>
                                  <v n="IdParent">181L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">183L</v>
                                  <v n="IdParent">181L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">184L</v>
                                  <v n="IdParent">181L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                  <o n="Value" t="EnumValue">
                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                    <n n="BaseType" />
                                    <v n="Value">"0"</v>
                                    <v n="DefaultValue">"0"</v>
                                  </o>
                                  <v n="Id">185L</v>
                                  <v n="IdParent">181L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">"S"</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">186L</v>
                                  <v n="IdParent">181L</v>
                                </o>
                              </l2>
                              <v n="Id">181L</v>
                              <v n="IdParent">63L</v>
                            </o>
                          </l2>
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"IDLE"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">64L</v>
                            <v n="IdParent">63L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">65L</v>
                            <v n="IdParent">63L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">66L</v>
                            <v n="IdParent">63L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">67L</v>
                            <v n="IdParent">63L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">68L</v>
                            <v n="IdParent">63L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">69L</v>
                            <v n="IdParent">63L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"T#1s"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">70L</v>
                            <v n="IdParent">63L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">71L</v>
                            <v n="IdParent">63L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"IDLE_active"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">72L</v>
                            <v n="IdParent">63L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"SFCtipReset"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">73L</v>
                            <v n="IdParent">63L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"SFCtipReset"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">74L</v>
                            <v n="IdParent">63L</v>
                          </o>
                        </l2>
                        <v n="Id">63L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"IDLE__to__WAITINGTRIGGER"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"monitor.powerstack.b_ControlEnabled"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">188L</v>
                            <v n="IdParent">187L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">189L</v>
                            <v n="IdParent">187L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">190L</v>
                            <v n="IdParent">187L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">191L</v>
                            <v n="IdParent">187L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">192L</v>
                            <v n="IdParent">187L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">193L</v>
                            <v n="IdParent">187L</v>
                          </o>
                        </l2>
                        <v n="Id">187L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"WAITINGTRIGGER"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">195L</v>
                            <v n="IdParent">194L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">196L</v>
                            <v n="IdParent">194L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">197L</v>
                            <v n="IdParent">194L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">198L</v>
                            <v n="IdParent">194L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">199L</v>
                            <v n="IdParent">194L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">200L</v>
                            <v n="IdParent">194L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"T#1s"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">201L</v>
                            <v n="IdParent">194L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">202L</v>
                            <v n="IdParent">194L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"WAITINGTRIGGER_active"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">203L</v>
                            <v n="IdParent">194L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"SFCTipReset"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">204L</v>
                            <v n="IdParent">194L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"SFCTipReset"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">205L</v>
                            <v n="IdParent">194L</v>
                          </o>
                        </l2>
                        <v n="Id">194L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCBranch">
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" cet="SFCSegment">
                            <o>
                              <o n="ElementList" t="SFCElementList">
                                <l2 n="InnerList" cet="SFCTransition">
                                  <o>
                                    <v n="VariableName">"Branch0__WAITINGTRIGGER__to__STARTUP"</v>
                                    <n n="EmbeddedTransition" />
                                    <l2 n="EmbeddedTransitionProperties" />
                                    <l2 n="Attributes" cet="SFCAttribute">
                                      <o>
                                        <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">"false"</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">76L</v>
                                        <v n="IdParent">75L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">77L</v>
                                        <v n="IdParent">75L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">78L</v>
                                        <v n="IdParent">75L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                        <o n="Value" t="EnumValue">
                                          <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                          <n n="BaseType" />
                                          <v n="Value">"0"</v>
                                          <v n="DefaultValue">"0"</v>
                                        </o>
                                        <v n="Id">79L</v>
                                        <v n="IdParent">75L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">80L</v>
                                        <v n="IdParent">75L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                        <o n="Value" t="EnumValue">
                                          <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                          <n n="BaseType" />
                                          <v n="Value">"0"</v>
                                          <v n="DefaultValue">"0"</v>
                                        </o>
                                        <v n="Id">81L</v>
                                        <v n="IdParent">75L</v>
                                      </o>
                                    </l2>
                                    <v n="Id">75L</v>
                                    <v n="IdParent">452L</v>
                                  </o>
                                </l2>
                              </o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">453L</v>
                                  <v n="IdParent">452L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">454L</v>
                                  <v n="IdParent">452L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">455L</v>
                                  <v n="IdParent">452L</v>
                                </o>
                              </l2>
                              <v n="Id">452L</v>
                              <v n="IdParent">447L</v>
                            </o>
                            <o>
                              <o n="ElementList" t="SFCElementList">
                                <l2 n="InnerList">
                                  <o t="SFCTransition">
                                    <v n="VariableName">"Branch1__WAITINGTRIGGER__to__IDLE"</v>
                                    <n n="EmbeddedTransition" />
                                    <l2 n="EmbeddedTransitionProperties" />
                                    <l2 n="Attributes" cet="SFCAttribute">
                                      <o>
                                        <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">"NOT monitor.powerstack.b_ControlEnabled"</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">461L</v>
                                        <v n="IdParent">460L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">462L</v>
                                        <v n="IdParent">460L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">463L</v>
                                        <v n="IdParent">460L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                        <o n="Value" t="EnumValue">
                                          <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                          <n n="BaseType" />
                                          <v n="Value">"0"</v>
                                          <v n="DefaultValue">"0"</v>
                                        </o>
                                        <v n="Id">464L</v>
                                        <v n="IdParent">460L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">465L</v>
                                        <v n="IdParent">460L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                        <o n="Value" t="EnumValue">
                                          <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                          <n n="BaseType" />
                                          <v n="Value">"0"</v>
                                          <v n="DefaultValue">"0"</v>
                                        </o>
                                        <v n="Id">466L</v>
                                        <v n="IdParent">460L</v>
                                      </o>
                                    </l2>
                                    <v n="Id">460L</v>
                                    <v n="IdParent">456L</v>
                                  </o>
                                  <o t="SFCJump">
                                    <l2 n="Attributes" cet="SFCAttribute">
                                      <o>
                                        <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">"IDLE"</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">487L</v>
                                        <v n="IdParent">486L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">488L</v>
                                        <v n="IdParent">486L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">489L</v>
                                        <v n="IdParent">486L</v>
                                      </o>
                                    </l2>
                                    <v n="Id">486L</v>
                                    <v n="IdParent">456L</v>
                                  </o>
                                </l2>
                              </o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">457L</v>
                                  <v n="IdParent">456L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">458L</v>
                                  <v n="IdParent">456L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">459L</v>
                                  <v n="IdParent">456L</v>
                                </o>
                              </l2>
                              <v n="Id">456L</v>
                              <v n="IdParent">447L</v>
                            </o>
                          </l2>
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Branch0_GenGridSFC"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">448L</v>
                            <v n="IdParent">447L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">449L</v>
                            <v n="IdParent">447L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">450L</v>
                            <v n="IdParent">447L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">451L</v>
                            <v n="IdParent">447L</v>
                          </o>
                        </l2>
                        <v n="Id">447L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"STARTUP"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">83L</v>
                            <v n="IdParent">82L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">84L</v>
                            <v n="IdParent">82L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">85L</v>
                            <v n="IdParent">82L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">86L</v>
                            <v n="IdParent">82L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">87L</v>
                            <v n="IdParent">82L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">88L</v>
                            <v n="IdParent">82L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"T#100ms"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">89L</v>
                            <v n="IdParent">82L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">90L</v>
                            <v n="IdParent">82L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"STARTUP_active"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">91L</v>
                            <v n="IdParent">82L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"SFCTipReset"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">92L</v>
                            <v n="IdParent">82L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"SFCTipReset"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">93L</v>
                            <v n="IdParent">82L</v>
                          </o>
                        </l2>
                        <v n="Id">82L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCBranch">
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" cet="SFCSegment">
                            <o>
                              <o n="ElementList" t="SFCElementList">
                                <l2 n="InnerList" cet="SFCTransition">
                                  <o>
                                    <v n="VariableName">"Branch0__STARTUP__to__RUN"</v>
                                    <n n="EmbeddedTransition" />
                                    <l2 n="EmbeddedTransitionProperties" />
                                    <l2 n="Attributes" cet="SFCAttribute">
                                      <o>
                                        <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">"false"</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">95L</v>
                                        <v n="IdParent">94L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">96L</v>
                                        <v n="IdParent">94L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">97L</v>
                                        <v n="IdParent">94L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                        <o n="Value" t="EnumValue">
                                          <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                          <n n="BaseType" />
                                          <v n="Value">"0"</v>
                                          <v n="DefaultValue">"0"</v>
                                        </o>
                                        <v n="Id">98L</v>
                                        <v n="IdParent">94L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">99L</v>
                                        <v n="IdParent">94L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                        <o n="Value" t="EnumValue">
                                          <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                          <n n="BaseType" />
                                          <v n="Value">"0"</v>
                                          <v n="DefaultValue">"0"</v>
                                        </o>
                                        <v n="Id">100L</v>
                                        <v n="IdParent">94L</v>
                                      </o>
                                    </l2>
                                    <v n="Id">94L</v>
                                    <v n="IdParent">495L</v>
                                  </o>
                                </l2>
                              </o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">496L</v>
                                  <v n="IdParent">495L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">497L</v>
                                  <v n="IdParent">495L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">498L</v>
                                  <v n="IdParent">495L</v>
                                </o>
                              </l2>
                              <v n="Id">495L</v>
                              <v n="IdParent">490L</v>
                            </o>
                            <o>
                              <o n="ElementList" t="SFCElementList">
                                <l2 n="InnerList">
                                  <o t="SFCTransition">
                                    <v n="VariableName">"Branch1__STARTUP__to__STOP"</v>
                                    <n n="EmbeddedTransition" />
                                    <l2 n="EmbeddedTransitionProperties" />
                                    <l2 n="Attributes" cet="SFCAttribute">
                                      <o>
                                        <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">"NOT monitor.powerstack.b_ControlEnabled"</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">504L</v>
                                        <v n="IdParent">503L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">505L</v>
                                        <v n="IdParent">503L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">506L</v>
                                        <v n="IdParent">503L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                        <o n="Value" t="EnumValue">
                                          <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                          <n n="BaseType" />
                                          <v n="Value">"0"</v>
                                          <v n="DefaultValue">"0"</v>
                                        </o>
                                        <v n="Id">507L</v>
                                        <v n="IdParent">503L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">508L</v>
                                        <v n="IdParent">503L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                        <o n="Value" t="EnumValue">
                                          <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                          <n n="BaseType" />
                                          <v n="Value">"0"</v>
                                          <v n="DefaultValue">"0"</v>
                                        </o>
                                        <v n="Id">509L</v>
                                        <v n="IdParent">503L</v>
                                      </o>
                                    </l2>
                                    <v n="Id">503L</v>
                                    <v n="IdParent">499L</v>
                                  </o>
                                  <o t="SFCJump">
                                    <l2 n="Attributes" cet="SFCAttribute">
                                      <o>
                                        <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">"STOP"</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">530L</v>
                                        <v n="IdParent">529L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                        <o n="Value" t="StringValue">
                                          <v n="Value">""</v>
                                          <v n="DefaultValue">""</v>
                                        </o>
                                        <v n="Id">531L</v>
                                        <v n="IdParent">529L</v>
                                      </o>
                                      <o>
                                        <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                        <o n="Value" t="BoolValue">
                                          <v n="Value">"FALSE"</v>
                                          <v n="DefaultValue">"FALSE"</v>
                                        </o>
                                        <v n="Id">532L</v>
                                        <v n="IdParent">529L</v>
                                      </o>
                                    </l2>
                                    <v n="Id">529L</v>
                                    <v n="IdParent">499L</v>
                                  </o>
                                </l2>
                              </o>
                              <l2 n="Attributes" cet="SFCAttribute">
                                <o>
                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">500L</v>
                                  <v n="IdParent">499L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                  <o n="Value" t="StringValue">
                                    <v n="Value">""</v>
                                    <v n="DefaultValue">""</v>
                                  </o>
                                  <v n="Id">501L</v>
                                  <v n="IdParent">499L</v>
                                </o>
                                <o>
                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                  <o n="Value" t="BoolValue">
                                    <v n="Value">"FALSE"</v>
                                    <v n="DefaultValue">"FALSE"</v>
                                  </o>
                                  <v n="Id">502L</v>
                                  <v n="IdParent">499L</v>
                                </o>
                              </l2>
                              <v n="Id">499L</v>
                              <v n="IdParent">490L</v>
                            </o>
                          </l2>
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Branch1_GenGridSFC"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">491L</v>
                            <v n="IdParent">490L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">492L</v>
                            <v n="IdParent">490L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">493L</v>
                            <v n="IdParent">490L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">494L</v>
                            <v n="IdParent">490L</v>
                          </o>
                        </l2>
                        <v n="Id">490L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"RUN"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">102L</v>
                            <v n="IdParent">101L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">103L</v>
                            <v n="IdParent">101L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">104L</v>
                            <v n="IdParent">101L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">105L</v>
                            <v n="IdParent">101L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">106L</v>
                            <v n="IdParent">101L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">107L</v>
                            <v n="IdParent">101L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"T#50ms"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">108L</v>
                            <v n="IdParent">101L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">109L</v>
                            <v n="IdParent">101L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"RUN_active"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">110L</v>
                            <v n="IdParent">101L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"SFCTipReset"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">111L</v>
                            <v n="IdParent">101L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"SFCTipReset"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">112L</v>
                            <v n="IdParent">101L</v>
                          </o>
                        </l2>
                        <v n="Id">101L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"RUN__to__STOP"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"False"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">114L</v>
                            <v n="IdParent">113L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">115L</v>
                            <v n="IdParent">113L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">116L</v>
                            <v n="IdParent">113L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">117L</v>
                            <v n="IdParent">113L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">118L</v>
                            <v n="IdParent">113L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">119L</v>
                            <v n="IdParent">113L</v>
                          </o>
                        </l2>
                        <v n="Id">113L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"STOP"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">160L</v>
                            <v n="IdParent">159L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">161L</v>
                            <v n="IdParent">159L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">162L</v>
                            <v n="IdParent">159L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">163L</v>
                            <v n="IdParent">159L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">164L</v>
                            <v n="IdParent">159L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">165L</v>
                            <v n="IdParent">159L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"T#2s"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">166L</v>
                            <v n="IdParent">159L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">167L</v>
                            <v n="IdParent">159L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"STOP_active"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">168L</v>
                            <v n="IdParent">159L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">169L</v>
                            <v n="IdParent">159L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"SFCTipReset"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">170L</v>
                            <v n="IdParent">159L</v>
                          </o>
                        </l2>
                        <v n="Id">159L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"STOP__to__IDLE"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"False"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">172L</v>
                            <v n="IdParent">171L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">173L</v>
                            <v n="IdParent">171L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">174L</v>
                            <v n="IdParent">171L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">175L</v>
                            <v n="IdParent">171L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">176L</v>
                            <v n="IdParent">171L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">177L</v>
                            <v n="IdParent">171L</v>
                          </o>
                        </l2>
                        <v n="Id">171L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCJump">
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"IDLE"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">22L</v>
                            <v n="IdParent">21L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">23L</v>
                            <v n="IdParent">21L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">24L</v>
                            <v n="IdParent">21L</v>
                          </o>
                        </l2>
                        <v n="Id">21L</v>
                        <v n="IdParent">1L</v>
                      </o>
                    </l2>
                  </o>
                  <l2 n="Attributes" cet="SFCAttribute">
                    <o>
                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                      <o n="Value" t="StringValue">
                        <v n="Value">""</v>
                        <v n="DefaultValue">""</v>
                      </o>
                      <v n="Id">178L</v>
                      <v n="IdParent">1L</v>
                    </o>
                    <o>
                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                      <o n="Value" t="StringValue">
                        <v n="Value">""</v>
                        <v n="DefaultValue">""</v>
                      </o>
                      <v n="Id">179L</v>
                      <v n="IdParent">1L</v>
                    </o>
                    <o>
                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                      <o n="Value" t="BoolValue">
                        <v n="Value">"FALSE"</v>
                        <v n="DefaultValue">"FALSE"</v>
                      </o>
                      <v n="Id">180L</v>
                      <v n="IdParent">1L</v>
                    </o>
                  </l2>
                  <v n="Id">1L</v>
                  <v n="IdParent">-1L</v>
                </o>
                <d2 n="Categories" ckt="Guid" cvt="SFCAttributeCategory">
                  <v>1c5c6e05-2bb7-4258-bcee-fd16a540c63c</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Identifier">"Specific"</v>
                    <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                    <v n="Description">"Element type specific properties"</v>
                  </o>
                  <v>20f0fc67-978d-438b-979f-eef294f34ee4</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Identifier">"Actions"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Action definitions"</v>
                  </o>
                  <v>6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Identifier">"Common"</v>
                    <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                    <v n="Description">"Common properties"</v>
                  </o>
                  <v>d336ba06-8a67-4e6b-9697-50f83ba6bdde</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                    <v n="Identifier">"Times"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Time definitions"</v>
                  </o>
                </d2>
                <d2 n="Attributes" ckt="Guid" cvt="SFCAttributeDescription">
                  <v>01580b27-6378-448b-8ecb-0e4b795b58d6</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">true</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                    <v n="Identifier">"Exclude"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Exclude this element from build"</v>
                  </o>
                  <v>23bdaa98-72ec-41f7-817b-9dede5697086</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                    <v n="Identifier">"Parallel"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Sets the branch to parallel mode"</v>
                  </o>
                  <v>38391c6d-6d4a-42f8-8ee7-9f45e5adafa8</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                    <v n="Identifier">"Name"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Name of the element"</v>
                  </o>
                  <v>62e1754b-7629-4e63-9cec-10ae0c536f1f</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                    <v n="Identifier">"Duplication"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Copies the implementation of step actions or transitions with the element. Otherwise, copies the reference to an existing implementation."</v>
                  </o>
                  <v>6844a48e-46c2-4cc8-a185-a478f3b99cc0</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                    <v n="Identifier">"InitStep"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Sets the step as the initial step"</v>
                  </o>
                  <v>700a583f-b4d4-43e4-8c14-629c7cd3bec8</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                    <v n="Identifier">"MainAction"</v>
                    <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Description">"Name of the action to be called if the step is active"</v>
                  </o>
                  <v>7d894980-aeea-405c-a0f6-e2b26429c58f</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">true</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                    <v n="Identifier">"Comment"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Comment of the element"</v>
                  </o>
                  <v>8294df19-5962-4dee-a874-1051dabb0e3e</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                    <v n="Identifier">"Monitoring"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Indicates transition monitoring setting."</v>
                  </o>
                  <v>a2621e18-7de3-4ea6-ae6d-89e9e0b7befd</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                    <v n="Identifier">"ExitAction"</v>
                    <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Description">"Name of the action to be called if the step is deactivated"</v>
                  </o>
                  <v>a6b08bd8-b696-47e3-9cbf-7408b61c9ff8</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                    <v n="Identifier">"EntryAction"</v>
                    <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Description">"Name of the action to be called if the step is activated"</v>
                  </o>
                  <v>b693554c-1b01-4a8d-afde-9e3a46f7465d</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                    <v n="Identifier">"MaxTime"</v>
                    <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                    <v n="Description">"Defines the maximal active time for the step"</v>
                  </o>
                  <v>bc882c11-1e91-4dd8-a6b8-2075724ed18b</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                    <v n="Identifier">"Symbol"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Symbol configuration setting of the element"</v>
                  </o>
                  <v>cacf1a68-236e-47c2-b7b1-1cf9199718cb</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                    <v n="Identifier">"MinTime"</v>
                    <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                    <v n="Description">"Defines the minimal active time for the step"</v>
                  </o>
                  <v>e174fc0d-80b0-4a9e-a530-ca239c249a50</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                    <v n="Identifier">"Qualifier"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Qualifier of the action association"</v>
                  </o>
                </d2>
                <d2 n="EnumTemplates" ckt="Guid" cvt="EnumValueTemplate">
                  <v>6ecff51c-9b8f-4338-aab0-67c2b31b07e9</v>
                  <o>
                    <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                    <l n="Values" t="ArrayList" cet="EnumEntry">
                      <o>
                        <v n="Identifier">"None"</v>
                        <v n="Value">0L</v>
                        <v n="Key">"None"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Variable"</v>
                        <v n="Value">1L</v>
                        <v n="Key">"Variable"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Call"</v>
                        <v n="Value">2L</v>
                        <v n="Key">"Call"</v>
                      </o>
                    </l>
                    <v n="BaseType">"INT"</v>
                  </o>
                  <v>79a4fdd5-c859-4de4-aa8d-c03372c880c2</v>
                  <o>
                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                    <l n="Values" t="ArrayList" cet="EnumEntry">
                      <o>
                        <v n="Identifier">"Unspecified"</v>
                        <v n="Value">0L</v>
                        <v n="Key">"Unspecified"</v>
                      </o>
                      <o>
                        <v n="Identifier">"None"</v>
                        <v n="Value">1L</v>
                        <v n="Key">"None"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Read"</v>
                        <v n="Value">2L</v>
                        <v n="Key">"Read"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Write"</v>
                        <v n="Value">3L</v>
                        <v n="Key">"Write"</v>
                      </o>
                      <o>
                        <v n="Identifier">"ReadWrite"</v>
                        <v n="Value">4L</v>
                        <v n="Key">"ReadWrite"</v>
                      </o>
                    </l>
                    <v n="BaseType">"INT"</v>
                  </o>
                </d2>
                <v n="ImplId">533L</v>
              </o>
            </Data>
            <TypeList>
              <Type n="ArrayList">System.Collections.ArrayList</Type>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="BoolValue">{89e1c7bb-c9f8-4be3-b8a7-019cdbb9f7e8}</Type>
              <Type n="EnumEntry">{4185e6da-1717-44c9-b705-102861764479}</Type>
              <Type n="EnumValue">{4dd7572b-4b9d-4d35-963e-6a34a4aaa5c1}</Type>
              <Type n="EnumValueTemplate">{d6bfe4f0-d62f-4b5f-9f95-2bbeb1950e28}</Type>
              <Type n="Guid">System.Guid</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="SFCActionAssociation">{a94bb75d-5fb3-40ad-9d01-41d5b980784d}</Type>
              <Type n="SFCAttribute">{21f3f16e-04fa-4637-b6b7-d84e4192e99f}</Type>
              <Type n="SFCAttributeCategory">{679adacf-f2a4-4167-a3f7-d21cfc5d451f}</Type>
              <Type n="SFCAttributeDescription">{d851789d-af2c-4990-9d48-a7bdc9181773}</Type>
              <Type n="SFCBranch">{e221b778-bb8f-44ba-8a6a-f796287d4e62}</Type>
              <Type n="SFCElementList">{587d6556-cfe6-4e76-9cc9-fc0daf0c8c29}</Type>
              <Type n="SFCImplementationObject">{74f81948-1328-492c-b6c1-a9ea72048b28}</Type>
              <Type n="SFCJump">{7e39ac27-154f-419a-a255-6a6cf37d5ed0}</Type>
              <Type n="SFCSegment">{f1db7f6f-4774-46a6-ad9b-a94414f875fc}</Type>
              <Type n="SFCStep">{86ee92a2-d863-4136-be27-82b36d84211c}</Type>
              <Type n="SFCTransition">{4ecb29e8-a90a-4646-84ac-2ff54215ab29}</Type>
              <Type n="String">System.String</Type>
              <Type n="StringValue">{778c8bac-3fa0-41e1-99d3-2b628d12d3e5}</Type>
            </TypeList>
          </XmlArchive>
        </SFC>
      </Implementation>
      <ObjectProperties>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="SFCProperty">
              <n n="SFCErrorAnalyzation" />
              <n n="SFCErrorAnalyzationTable" />
              <n n="SFCCurrentSteps" />
              <n n="SFCMetaSteps" />
              <v n="Title">"IecSfc"</v>
              <v n="Company">"System"</v>
              <v n="Version">"3.4.2.0"</v>
              <v n="Namespace">""</v>
              <d2 n="Flags" ckt="Flags" cvt="SFCPropertyFlagData">
                <v>EnableLimit</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Init</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Reset</v>
                <o>
                  <v n="Use">true</v>
                  <v n="Declare">true</v>
                </o>
                <v>QuitError</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Pause</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Error</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Trans</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>ErrorStep</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>ErrorPOU</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>CurrentStep</v>
                <o>
                  <v n="Use">true</v>
                  <v n="Declare">true</v>
                </o>
                <v>Tip</v>
                <o>
                  <v n="Use">true</v>
                  <v n="Declare">true</v>
                </o>
                <v>TipMode</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>SFCErrorAnalyzation</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>SFCErrorAnalyzationTable</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>CurrentSteps</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">false</v>
                </o>
                <v>MetaSteps</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">false</v>
                </o>
              </d2>
              <v n="CalcActiveTransOnly">false</v>
              <v n="UseDefaults">false</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="Flags">{27d8150b-ef58-4fff-8da1-1f7dd5f9ea51}</Type>
            <Type n="SFCProperty">{58548d2c-f1b1-453d-9195-66c94e2a3ae0}</Type>
            <Type n="SFCPropertyFlagData">{24565a38-6368-4874-ab9a-0ef7ec269521}</Type>
            <Type n="String">System.String</Type>
          </TypeList>
        </XmlArchive>
      </ObjectProperties>
    </Action>
    <Method Name="GensetStartStop" Id="{88d4b184-56d9-4a33-aca6-cc4d4190f044}" FolderPath="Nested Methods\">
      <Declaration><![CDATA[METHOD GensetStartStop : eGensetStartStop
VAR_INPUT
	b_autoMode : BOOL;
	b_ManStartStop : BOOL;
END_VAR

VAR_INST
	rTRIG_StartStop	: r_TRIG;
	ManualStart		: BOOL;
	StateInAutoMode	: BOOL;
	GensetTransInhibit: BOOL;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[rTRIG_StartStop(CLK := b_ManStartStop);
IF rTRIG_StartStop.Q THEN
	ManualStart := NOT ManualStart;
	StateInAutoMode := FALSE;
END_IF

IF get.e_state = eGenGridState.Idle AND get.b_ModeTransActive THEN
	ManualStart := FALSE;
END_IF


IF b_AutoMode AND NOT get.events.b_TransFromInputGenAckRQ THEN
	GensetStartStop := eGensetStartStop.Auto;
	StateInAutoMode := b_IOstartStop;
ELSE
	IF ManualStart OR StateInAutoMode THEN
		GensetStartStop := eGensetStartStop.Start;
	ELSE
		GensetStartStop := eGensetStartStop.Stop;	
	END_IF
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="GetControlTarget" Id="{b5e5d72b-7305-469e-b0bf-d7b4578525a6}" FolderPath="ControlTarget Methods\">
      <Declaration><![CDATA[METHOD GetControlTarget

VAR_IN_OUT CONSTANT
	Control					: ST_System_Control;
	monitor					: ST_System_Monitor;
END_VAR

VAR_IN_OUT
	TargetData				: ST_PowerControl_Target;
	GensetSetpoints			: ST_Genset_Setpoints;
END_VAR

VAR_INPUT
	PowerControlMode			: ePowerControlMode;
	b_SFCPIDActivation			: BOOL;
	b_Deload					: BOOL;
	b_PSBactive					: BOOL;
END_VAR

VAR_INST
	b_PSBActiveConditions	: BOOL;
	b_SFCDeactivationEnable : BOOL;
	b_SoCTargetEnable		: BOOL;
	b_inputOvercurrent		: BOOL;	
	r_activePowerMeas		: REAL;
	
	r_MaxActive				: REAL;			
END_VAR

]]></Declaration>
      <Implementation>
        <ST><![CDATA[b_PSBActiveConditions := monitor.peakshavebox.b_active AND b_ExtACOK;
b_SFCDeactivationEnable := TRUE;
b_SoCTargetEnable := control.HardSettings.setup.e_ControlSource = eControlsources.Local AND NOT control.Operation.system.b_GridTakeOverEnable;

CASE PowerControlMode OF
	ePowerControlMode.None:
		Targetdata.Measurements.r_ActivePower := monitor.powermonitor.OutputField.ar_ActivePower[0];
		Targetdata.Measurements.r_ReactivePower := monitor.powermonitor.OutputField.ar_ReactivePower[0];
		Targetdata.Measurements.r_PhaseVoltage := 0;
		IF inputcontactor.b_fb OR monitor.powerstack.b_InverterGridFormingMode THEN
			Targetdata.PIDmode := ePIDmode.None;
		ELSE
			Targetdata.r_FeedInCurrentLimit := 1000;
			Targetdata.r_SupplyCurrentLimit := 1000;
			Targetdata.PIDmode := ePIDmode.Both;
		END_IF
		Targetdata.b_GenIsoPID := FALSE;
		Targetdata.r_droopMinimum := 0;
		b_SFCDeactivationEnable := FALSE;	
		
//Grid extern peakshaver
	ePowerControlMode.PeakshaveExt: 
		//peakshave ext genset in droop
		IF control.softsettings.inputgenset.b_PSBExtGensetMonitoring THEN
			TargetData := MapGensetTarget(
				soft := control.SoftSettings.inputgenset,
				r_activePower := monitor.peakshavebox.Powermonitor.ar_ActivePower[0],
				r_reactivePower := monitor.peakshavebox.Powermonitor.ar_ReactivePower[0],
				r_Phasevoltage	:= monitor.peakshavebox.Powermonitor.ar_LineVoltage[0],
				b_active := b_PSBActiveConditions AND monitor.powerstack.b_StartedState AND b_IOstartstop, //IF PSB added, this must be activated by HMI toggle button or something.
				setpoints := Gensetsetpoints);
		ELSE
			IF BreakerOperationMode = eBreakerOperationmode.GridFeedthrough THEN
				//Check inputsection for overcurrent, to be used later
			b_InputOvercurrent := ValueOutOfRange(
				r_min := 0,
				r_max := control.SoftSettings.inputgrid.setpointTimeslot1.r_supplyCurrentLimitSoft,
				r_var := monitor.powermonitor.InputField.ar_Current[0]);
			ELSE
				b_inputOvercurrent := FALSE;
			END_IF
			
			TargetData := MapGridTarget(
				slot1 := control.SoftSettings.PSB.setpointTimeslot1,
				slot2 := control.SoftSettings.PSB.setpointTimeslot2,
				r_activePower := monitor.peakshavebox.Powermonitor.ar_ActivePower,
				r_reactivePower := monitor.peakshavebox.Powermonitor.ar_ReactivePower,
				r_Phasevoltage	:= monitor.peakshavebox.Powermonitor.ar_PhaseVoltage[0],
				Peakshavemode := control.SoftSettings.PSB.PeakshaveMode,
				r_feedInCurrentLimit:= monitor.peakshavebox.r_MaxCTCurrent,
				r_supplyCurrentLimit:= monitor.peakshavebox.r_MaxCTCurrent,
				b_active := b_PSBActiveConditions AND SEL(control.SoftSettings.psb.b_BreakerControl,TRUE, monitor.peakshavebox.b_ContactorFb)
					AND NOT monitor.powerstack.b_InverterGridFormingMode
					AND monitor.powerstack.b_StartedState,
				b_enableSocTarget := b_SoCTargetEnable);
				b_SFCDeactivationEnable := control.softsettings.psb.b_BreakerControl;
		END_IF
	


//Grid input peakshaver
	ePowerControlMode.PeakshaveInputGrid:
		r_MaxActive := MIN(monitor.powermonitor.InputField.ar_ActivePower[1], monitor.powermonitor.InputField.ar_ActivePower[2], monitor.powermonitor.InputField.ar_ActivePower[3]) * 3;		
		
		TargetData := MapGridTarget(
			slot1 := control.SoftSettings.inputgrid.setpointTimeslot1,
			slot2 := control.SoftSettings.inputgrid.setpointTimeslot2,
			r_activePower := monitor.powermonitor.InputField.ar_ActivePower,						
			r_reactivePower := monitor.powermonitor.InputField.ar_ReactivePower,
			r_Phasevoltage	:= monitor.powermonitor.InputField.ar_PhaseVoltage[0],
			Peakshavemode := control.SoftSettings.inputgrid.PeakshaveMode,
			r_feedInCurrentLimit:= settings.Properties.r_ratedCurrentInput,
			r_supplyCurrentLimit:= settings.Properties.r_ratedCurrentInput,
			b_active := monitor.ACswitchgear.b_InputMCCBfb AND monitor.ACswitchgear.b_InputContactorfb AND b_InputACOK AND NOT b_gridTakeoverMode,
			b_enableSocTarget := b_SoCTargetEnable);


//Genset iso mode mapping (kind of peakshaver of genset)
	ePowerControlMode.PeakshaveInputGen:
		TargetData := MapGensetTarget(
				soft := control.SoftSettings.inputgenset,
				r_activePower := monitor.powermonitor.InputField.ar_ActivePower[0],
				r_reactivePower := monitor.powermonitor.InputField.ar_ReactivePower[0],
				r_Phasevoltage	:= monitor.powermonitor.InputField.ar_PhaseVoltage[0],
				b_active := monitor.ACswitchgear.b_InputMCCBfb AND monitor.ACswitchgear.b_InputContactorfb AND b_InputACOK,
				setpoints := gensetsetpoints);
	
		IF get.e_GensetMode = eGensetmode.FixedPower AND b_PSBactive THEN
			TargetData := MapGridTarget(
				slot1 := control.SoftSettings.PSB.setpointTimeslot1,
				slot2 := control.SoftSettings.PSB.setpointTimeslot2,
				r_activePower := monitor.peakshavebox.Powermonitor.ar_ActivePower,
				r_reactivePower := monitor.peakshavebox.Powermonitor.ar_ReactivePower,
				r_Phasevoltage	:= monitor.peakshavebox.Powermonitor.ar_PhaseVoltage[0],
				Peakshavemode := control.SoftSettings.PSB.PeakshaveMode,
				r_feedInCurrentLimit:= monitor.peakshavebox.r_MaxCTCurrent,
				r_supplyCurrentLimit:= monitor.peakshavebox.r_MaxCTCurrent,
				b_active := b_PSBActiveConditions AND SEL(control.softsettings.psb.b_BreakerControl,TRUE, monitor.peakshavebox.b_ContactorFb)
					AND NOT monitor.powerstack.b_InverterGridFormingMode
					AND monitor.powerstack.b_StartedState,
				b_enableSocTarget := b_SoCTargetEnable);
				b_SFCDeactivationEnable := control.softsettings.psb.b_BreakerControl;
		END_IF
END_CASE

//allow deactivation of powercontroller from inside functionblock
IF NOT b_SFCPIDActivation AND b_SFCDeactivationEnable THEN
	Targetdata.PIDmode := ePIDmode.None;
END_IF

//deload with PID controller
IF b_Deload THEN
	Targetdata.PIDmode := ePIDmode.BOTH;
	TargetData.r_FeedInCurrentLimit := 0;
	TargetData.r_SupplyCurrentLimit := 0;
	//TargetData.b_GenIsoPID := TRUE;
END_IF

//SOC drooping
IF (b_GridTakeOverMode OR eModeLocal = UgridIsland OR eModeLocal = UgridIso OR b_Deload) AND b_BESSReady THEN
	TargetData.b_EnableSocDrooping := FALSE;
ELSE
	TargetData.b_EnableSocDrooping := TRUE;
END_IF

//FUTURE WORK : make summation of multiple peakshave boxes.

]]></ST>
      </Implementation>
    </Method>
    <Method Name="GetDiagnostics" Id="{651b3d78-7ca4-49d7-8e0d-d568a6ebf937}">
      <Declaration><![CDATA[METHOD GetDiagnostics
VAR_IN_OUT
	AddError		: ARRAY [*] OF FB_AddErrorST;
	a_ActiveEvents	: ARRAY [*] OF ST_ErrorStruct;
	w_Index			: WORD;
END_VAR


VAR_INST
	s_dynamicStringModeTrans	: STRING := 'input disconnected by user, acknowledge to continue operation';;
	rTrigModeTrans				: R_TRIG;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[(*Grid lost trip*)				AddError[w_Index](
		b_ErrorTrig				:= get.events.b_GridLostTrip,
		out_ST_Error			:= a_ActiveEvents[w_Index],
		w_ErrorID				:= 1,
		e_ObjectID				:= eObject_ID.GenGridController,
		s_Message				:= 'Grid loss trip',
		e_sev					:= eseverity.warning,
		b_autoClear				:= TRUE
	);
	w_Index := w_Index +1;
	
(**)	AddError[w_Index](
		b_ErrorTrig				:= FALSE,
		out_ST_Error			:= a_ActiveEvents[w_Index],
		w_ErrorID				:= 2,
		s_Message				:= '',
		e_sev					:= eseverity.info,
		b_autoClear				:= TRUE
	);
	w_Index := w_Index +1;
	
(**)		AddError[w_Index](
		b_ErrorTrig				:= FALSE,
		out_ST_Error			:= a_ActiveEvents[w_Index],
		w_ErrorID				:= 3,
		s_Message				:= '',
		e_sev					:= eseverity.info,
		b_autoClear				:= TRUE
	);
	w_Index := w_Index +1;
	

(*Over Freq Trip*)				AddError[w_Index](
		b_ErrorTrig				:= get.events.b_OverFreqTrip,
		out_ST_Error			:= a_ActiveEvents[w_Index],
		w_ErrorID				:= 4,
		s_Message				:= 'overfrequency trip',
		e_sev					:= eseverity.Warning,
	);
	w_Index := w_Index +1;
	
(*Under Freq Trip*)				AddError[w_Index](
		b_ErrorTrig				:= get.events.b_UnderFreqTrip,
		out_ST_Error			:= a_ActiveEvents[w_Index],
		w_ErrorID				:= 5,
		s_Message				:= 'underfrequency trip',
		e_sev					:= eseverity.Warning,
	
	);
	w_Index := w_Index +1;

(*Overload Trip*)			AddError[w_Index](
		b_ErrorTrig				:= get.events.b_OverloadTrip,
		out_ST_Error			:= a_ActiveEvents[w_Index],
		w_ErrorID				:= 6,
		s_Message				:= 'overload trip',
		e_sev					:= eseverity.Warning,
	);
	w_Index := w_Index +1;
	
(*SFC startup fault*)			AddError[w_Index](
		b_ErrorTrig				:= get.events.b_StartupFault,
		out_ST_Error			:= a_ActiveEvents[w_Index],
		w_ErrorID				:= 7,
		s_Message				:= 'Startup fault',
		e_sev					:= eseverity.Warning,
	);
	w_Index := w_Index +1;
	
(*SFC Sync fault*)			AddError[w_Index](
		b_ErrorTrig				:= get.events.b_SynchronisationFault,
		out_ST_Error			:= a_ActiveEvents[w_Index],
		w_ErrorID				:= 8,
		s_Message				:= 'Synchronisation fault',
		e_sev					:= eseverity.Warning,
	);
	w_Index := w_Index +1;

(*SFC warmup fault*)			AddError[w_Index](
		b_ErrorTrig				:= get.events.b_WarmupFault,
		out_ST_Error			:= a_ActiveEvents[w_Index],
		w_ErrorID				:= 9,
		s_Message				:= 'warmup fault',
		e_sev					:= eseverity.Warning,
	);
	w_Index := w_Index +1;
	
(*SFC shutdown timeout*)			AddError[w_Index](
		b_ErrorTrig				:= get.events.b_ShutdownTimeOut,
		out_ST_Error			:= a_ActiveEvents[w_Index],
		w_ErrorID				:= 10,
		s_Message				:= 'shutdown timeout',
		e_sev					:= eseverity.warning,
	);
	w_Index := w_Index +1;
	
(*breakermode transition iso inhibit*)			AddError[w_Index](
		b_ErrorTrig				:= get.events.b_TransToGenIsoInhibit,
		out_ST_Error			:= a_ActiveEvents[w_Index],
		w_ErrorID				:= 11,
		s_Message				:= 'generator iso mode inhibited, because grid ac was detected',
		e_sev					:= eseverity.warning,
		t_triggertime 			:= T#1S,
		b_autoclear				:= TRUE
	);
	w_Index := w_Index +1;
	
(*breakermode transition iso inhibit*)			AddError[w_Index](
		b_ErrorTrig				:= get.events.b_TransToGenDroopInhibit,
		out_ST_Error			:= a_ActiveEvents[w_Index],
		w_ErrorID				:= 12,
		s_Message				:= 'generator droop mode inhibited, because grid ac was detected',
		e_sev					:= eseverity.warning,
		t_triggertime 			:= T#1S,
		b_autoclear				:= TRUE
	);
	w_Index := w_Index +1;
	
	
	
	(*input grid active, acknowledge required*)			AddError[w_Index](
		b_ErrorTrig				:= get.events.b_TransFromInputGridAckRQ,
		out_ST_Error			:= a_ActiveEvents[w_Index],
		w_ErrorID				:= 13,
		s_Message				:= 'transition hold: input grid coupled, acknowledge by disconnecting AC or inputcontactor',
		e_sev					:= eseverity.warning,
		t_triggertime 			:= T#100MS,
		b_autoclear				:= TRUE
	);
	w_Index := w_Index +1;
	
rTrigModeTrans(CLK := get.b_ModeTransActive);
IF rTrigModeTrans.Q THEN
	IF get.events.b_CurrentLimitTrip THEN
		s_dynamicStringModeTrans := 'input disconnected by currentlimit trip, acknowledge to reconnect input';
	ELSIF get.events.b_EmstopDisconnect THEN
		s_dynamicStringModeTrans := 'input disconnected by EM-stop, clear EMstop and acknowledge to continue operation';
	ELSIF get.events.b_ShutdownDisconnect THEN
		s_dynamicStringModeTrans := 'input disconnected by shutdown, clear diagnostics and acknowledge to continue operation';
	ELSE
		s_dynamicStringModeTrans := 'input disconnected, acknowledge to continue operation';
	END_IF
END_IF
	
(*Mode transition active*)			AddError[w_Index](
		b_ErrorTrig				:= get.b_ModeTransActive,
		out_ST_Error			:= a_ActiveEvents[w_Index],
		w_ErrorID				:= 14,
		s_Message				:= s_dynamicStringModeTrans,
		e_sev					:= eseverity.warning,
		t_triggertime 			:= T#100MS,
		b_autoclear				:= TRUE
	);
	w_Index := w_Index +1;
	
(*input grid active, acknowledge required*)			AddError[w_Index](
		b_ErrorTrig				:= get.events.b_TransFromInputGenAckRQ,
		out_ST_Error			:= a_ActiveEvents[w_Index],
		w_ErrorID				:= 15,
		s_Message				:= 'transition hold: input genset started, acknowledge by stopping generator',
		e_sev					:= eseverity.warning,
		t_triggertime 			:= T#100MS,
		b_autoclear				:= TRUE
	);
	w_Index := w_Index +1;
	
(*genfix faulty start condition*)			AddError[w_Index](
		b_ErrorTrig				:= get.events.b_TransToGenFixInhibit,
		out_ST_Error			:= a_ActiveEvents[w_Index],
		w_ErrorID				:= 16,
		s_Message				:= 'AC detected at input before start stop was given, disconnect AC to continue',
		e_sev					:= eseverity.warning,
		t_triggertime 			:= T#100MS,
		b_autoclear				:= TRUE
	);
	w_Index := w_Index +1;
	
(*Starting inhibit*)			AddError[w_Index](
		b_ErrorTrig				:= get.events.b_StartingInhibit,
		out_ST_Error			:= a_ActiveEvents[w_Index],
		w_ErrorID				:= 17,
		s_Message				:= 'input control inhibited because input MCCB is opened',
		e_sev					:= eseverity.warning,
		t_triggertime 			:= T#100MS,
		b_autoclear				:= TRUE
	);
	w_Index := w_Index +1;
	
(*Starting inhibit*)			AddError[w_Index](
		b_ErrorTrig				:= get.events.b_RotationFieldFault,
		out_ST_Error			:= a_ActiveEvents[w_Index],
		w_ErrorID				:= 18,
		s_Message				:= 'Input rotation field fault, synchronization on hold',
		e_sev					:= eseverity.warning,
		t_triggertime 			:= T#100MS,
		b_autoclear				:= TRUE
	);
	w_Index := w_Index +1;
	
(*Gen down*)			AddError[w_Index](
		b_ErrorTrig				:= get.events.b_GenDownTrip,
		out_ST_Error			:= a_ActiveEvents[w_Index],
		w_ErrorID				:= 19,
		s_Message				:= 'Genset down trip, synchronization on hold',
		e_sev					:= eseverity.warning,
		t_triggertime 			:= T#100MS,
		b_autoclear				:= TRUE
	);
	w_Index := w_Index +1;
	
(*Overvoltage Trip*)			AddError[w_Index](
		b_ErrorTrig				:= get.events.b_OverVoltTrip,
		out_ST_Error			:= a_ActiveEvents[w_Index],
		w_ErrorID				:= 20,
		s_Message				:= 'overvoltage trip',
		e_sev					:= eseverity.Warning,
	);
	w_Index := w_Index +1;
	
(*Overvoltage Trip*)			AddError[w_Index](
		b_ErrorTrig				:= get.events.b_underVoltTrip,
		out_ST_Error			:= a_ActiveEvents[w_Index],
		w_ErrorID				:= 21,
		s_Message				:= 'undervoltage trip',
		e_sev					:= eseverity.Warning,
	);
	w_Index := w_Index +1;

(*Generator low fuel warning*)	AddError[w_Index](
		b_ErrorTrig				:= monitor.HartingIO.b_GenLowFuel,
		out_ST_Error			:= a_ActiveEvents[w_Index],
		w_ErrorID				:= 22,
		s_Message				:= 'Generator low fuel warning',
		e_sev					:= eseverity.Warning,
		b_autoclear				:= TRUE
	);
	w_Index := w_Index +1;
	
(*Generator Soc start warning*)	AddError[w_Index](
		b_ErrorTrig				:= monitor.battery.BatteryInfo.r_SOCScaled < GensetSetpoints.r_SocStart -1 AND SOCStart.Q,
		out_ST_Error			:= a_ActiveEvents[w_Index],
		w_ErrorID				:= 23,
		s_Message				:= 'autostart SoC low warning, Generator not started',
		e_sev					:= eseverity.warning,
		t_Triggertime			:= T#30S,
		b_autoclear				:= FALSE
	);
	w_Index := w_Index +1;
	
(*Generator Soc stop warning*)	AddError[w_Index](
		b_ErrorTrig				:= monitor.battery.BatteryInfo.r_SOCScaled > GensetSetpoints.r_SocStop +1 AND SOCStart.Q,
		out_ST_Error			:= a_ActiveEvents[w_Index],
		w_ErrorID				:= 24,
		s_Message				:= 'autostop SoC high warning, Generator power not stopped',
		e_sev					:= eseverity.Warning,
		t_Triggertime			:= T#30S,
		b_autoclear				:= FALSE
	);
	w_Index := w_Index +1;]]></ST>
      </Implementation>
    </Method>
    <Method Name="GridOkDetect" Id="{4d1adf37-21ae-4d6a-9f7d-63759563804b}" FolderPath="Nested Methods\">
      <Declaration><![CDATA[METHOD GridOkDetect : BOOL

VAR_INPUT
	SkipGridCode			: BOOL;
END_VAR

VAR_INST
	b_skip					: BOOL;
	tof_SyncDelay			: TOF := (PT := T#1S);
	
	ton_GridOK				: TON := (PT := T#2S);
	tof_GridLostBackup		: TOF ;
	ton_GCFaultReset		: Ton := (PT := T#60S);
	ton_FlatZeroPowerTimeOut: TON := (PT := T#1S);
	r_activepower			: REAL;
	GridCodeTripDetected	: BOOL;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[tof_SyncDelay(IN := NOT b_breakerFB AND TargetData.Syncdata.b_Sync);
IF tof_syncDelay.Q THEN
	Settings.GridParams.ui_GCTripMaxTripTime := 500;
	
ELSE
	Settings.GridParams.ui_GCTripMaxTripTime := 40;
END_IF


tof_GridLostBackup(IN := b_BreakerACok, PT := TO_TIME(settings.GridParams.ui_GCTripMaxTripTime));


//detect flat power 
r_ActivePower := monitor.powermonitor.InputField.ar_ActivePower[0];
ton_FlatZeroPowerTimeOut(IN := r_ActivePower = 0 AND 
	b_breakerfb AND 
	ton_GridOK.Q AND monitor.powerstack.b_StartedState);

ton_GridOK(IN:= tof_GridLostBackup.Q);

b_skip := SkipGridcode OR NOT monitor.powerstack.b_StartedState OR b_gridtakeovermode;
ton_GCFaultReset(IN:= ton_GridOK.Q AND b_BreakerACok, PT := SEL(b_skip, TO_TIME(TO_REAL(settings.GridParams.ui_GCokReleaseTime)*1000), T#0S)); // AND ramp rate etc.etc. TBD

IF b_skip THEN
	b_GridCodeOK := ton_GridOK.Q;
ELSE
	b_GridCodeOK := ton_GCFaultReset.Q AND NOT b_GridCodeTripInverter AND NOT ton_FlatZeroPowerTimeOut.Q;
END_IF

get.events.b_GridLostTrip := NOT b_GridCodeOK;
GridOkDetect := b_gridCodeOK;]]></ST>
      </Implementation>
    </Method>
    <Action Name="IDLE_active" Id="{c5dd01a5-81cd-4b1a-a68d-79c98b304d5a}" FolderPath="SFC\">
      <Implementation>
        <ST><![CDATA[get.e_state := eGenGridState.Idle;
b_SFCmodeTransInhibit := FALSE;
get.b_active := FALSE;

CASE breakerOperationMode OF
	ebreakeroperationmode.ExtGrid, ebreakeroperationmode.gridfeedthrough : b_ActivatePowerControl := FALSE;
	ELSE
		b_ActivatePowerControl := b_startcondition;
END_CASE



]]></ST>
      </Implementation>
    </Action>
    <Action Name="INIT_active" Id="{3084fc0d-a4c3-417d-af84-8748c5d4ca38}" FolderPath="SFC\">
      <Implementation>
        <ST><![CDATA[SFCResetTrigger := FALSE;

//Default init conditions
get.e_state := eGenGridState.Init;


CASE breakeroperationmode OF
	eBreakeroperationmode.Geniso, eBreakeroperationmode.GenDroop, eBreakeroperationmode.GenFix:
		b_IOstartStop := b_startcondition;
	eBreakerOperationMode.GridFeedthrough:
		GridOKdetect(TRUE);
END_CASE

IF BreakerOperationMode <> eBreakerOperationMode.ExtGrid THEN
	Extcontactor.Open(TRUE);	
END_IF

b_NetcontactorHoldClose := FALSE;
b_ActivatePowerControl := FALSE;
get.b_active := FALSE;
b_SFCmodeTransInhibit := FALSE;
//targetdata.Syncdata.b_Sync:= FALSE;


]]></ST>
      </Implementation>
    </Action>
    <Method Name="InputContactorNC" Id="{3cbcc200-a0cc-45ff-a831-e70ed1b45e63}" FolderPath="Nested Methods\">
      <Declaration><![CDATA[METHOD InputContactorNC : BOOL
VAR_INPUT
	Enable 			: BOOL;
	//Toggle 		: BOOL;
END_VAR

VAR_INST
	TON_TriggerDelay 		: TON := (PT := T#500MS);
	TOF_ReleaseDelay 		: TOF := (PT := T#100MS);
	rtrig_ToggleState		: R_TRIG;
	rtrig_ToggleON			: R_TRIG;
	ftrig_ToggleOFF			: F_TRIG;
	b_ToggleState			: BOOL;
	ton_UpdateToggleState	: TON := (pt := T#500MS);
	b_Fb					: BOOL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[TON_TriggerDelay(IN := b_BreakerACOk AND Enable);
TOF_ReleaseDelay(IN:= TON_TriggerDelay.Q);
rtrig_ToggleON();
ftrig_ToggleOFF();	

IF get.b_ModeTransActive THEN
	b_ToggleState := FALSE;
	rtrig_ToggleON();
	ftrig_ToggleOFF.CLK := FALSE;
	rtrig_ToggleON.CLK := FALSE;
ELSE
	rtrig_ToggleON.CLK:= TON_TriggerDelay.Q;
	IF rtrig_ToggleON.Q THEN
		b_ToggleState := TRUE;
	END_IF
	
	ftrig_ToggleOFF(CLK := TOF_ReleaseDelay.Q);	
	IF ftrig_ToggleOFF.Q THEN
		b_ToggleState := FALSE;
	END_IF
END_IF


IF b_ToggleState THEN
	b_Fb := InputContactor.Close(TRUE);
ELSE
	b_Fb := NOT InputContactor.open(TRUE);
END_IF



]]></ST>
      </Implementation>
    </Method>
    <Method Name="MapGensetTarget" Id="{8b3ca7db-aefd-4a5c-9be9-851b21620b37}" FolderPath="ControlTarget Methods\">
      <Declaration><![CDATA[METHOD MapGensetTarget : ST_PowerControl_Target
VAR_IN_OUT CONSTANT
	soft		: ST_SoftSettings_Genset;
END_VAR

VAR_IN_OUT
	setpoints 	: ST_Genset_setpoints;
END_VAR

VAR_INPUT
	r_ActivePower				: REAL;
	r_ReactivePower				: REAL;
	r_phaseVoltage				: REAL;
	b_active					: BOOL;
END_VAR


VAR_INST
	r_chargePowerTarget			: REAL := 100; 
	r_GensetMaxCurrent			: REAL;
	r_GensetMinPower			: REAL;
	r_GensetMinCurrent			: REAL;
	r_GensetEffPower			: REAL;
	r_GensetEffCurrent			: REAL;
	r_GenCurSetpointModified	: REAL;
	r_GenCurSetpointLoadStart	: REAL;
	r_GenCurSetpointTemp		: REAL;
	r_GenCurSetpoint			: REAL;
	r_loadbankMaxCurrent		: REAL;
	enable						: BOOL := TRUE;
	r_dischargeloadmax			: REAL := 100;
	r_Chargeloadmax				: REAL := 100;
	r_loadmaxActual				: REAL;
	r_RatedInputCurrent			: REAL;
	ton_GenMaxCurrentDelay		: TON := (PT := T#5S);
	
	b_ConditionalStart			: BOOL;
	
	//params
	by_genloadMinLimit			: BYTE := 5;
END_VAR

]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF b_TimeSlot2 THEN
	setpoints := soft.setpointTimeslot2;
ELSE 
	setpoints := soft.setpointTimeslot1;
END_IF

MapgensetTarget.r_PIDRampRate := soft.Generator.r_ramprate;
MapgensetTarget.b_GenIsoPID  := FALSE; 
MapGensetTarget.PeakshaveMode := FALSE;
r_RatedInputCurrent := settings.Properties.r_ratedCurrentInput;
r_chargePowerTarget := settings.Properties.r_RatedActivePower;

IF st_params.GenIso_InverterMode = eGenIsoInverterMode.ISO_SLOWDROOP AND soft.generator.e_GensetMode = egensetmode.Isochronous THEN
	MapgensetTarget.r_droopMinimum := 20;
ELSE
	MapgensetTarget.r_droopMinimum := 0.1;
END_IF

//calculate related values from genset settings
r_GensetMaxCurrent := LIMIT(0, ABS(KWtoCurrent(soft.Generator.r_RatedPower * soft.Generator.r_powerloadMax / 100, r_phaseVoltage * 1.73)), r_RatedInputCurrent);
r_GensetMinCurrent := LIMIT(by_genloadMinLimit, ABS(KWtoCurrent(soft.Generator.r_RatedPower * soft.Generator.r_powerloadMin / 100, r_phaseVoltage * 1.73)), r_RatedInputCurrent);
r_GensetEffPower := soft.Generator.r_RatedPower * soft.Generator.r_powerloadEff / 100;
r_GensetEffCurrent := LIMIT(0, ABS(KWtoCurrent(r_GensetEffPower, r_phaseVoltage * 1.73)), r_RatedInputCurrent);
r_loadbankMaxCurrent := LIMIT(0, ABS(KWtoCurrent(soft.Loadbank.r_PowerRating, r_phaseVoltage * 1.73)), r_RatedInputCurrent);
r_dischargeloadmax := MIN(monitor.powerstack.r_Pmax / MAX(1, monitor.powerstack.r_RatedPower) * 100, 100);
r_Chargeloadmax := -MIN(monitor.powerstack.r_Pmin / MAX(1, monitor.powerstack.r_RatedPower) * 100, 100);

r_loadmaxActual := MAX(setpoints.r_BatteryloadStart, r_DisChargeloadmax);


//shift setpoint from eff. to max point if battery is at limit.
IF monitor.powerstack.e_PowerState = ePowerstate.Charging THEN
	r_GenCurSetpointLoadStart := r_GensetEffCurrent;
ELSE
	r_GenCurSetpointLoadStart := scale(
	monitor.powerstack.r_Loadpercent, 
	r_loadmaxActual - 3, 
	r_loadmaxActual,
	r_GensetEffCurrent,
	r_GensetMaxCurrent);
END_IF

b_ConditionalStart := (LoadStart.Q OR SOCStart.Q OR BatFullStart.Q OR ChargeLoadStart.Q);

ton_GenMaxCurrentDelay(IN:= b_ConditionalStart AND MAX(0, Monitor.powermonitor.OutputField.ar_ActivePower[0] + r_chargePowerTarget) > r_GensetEffPower);
IF ton_GenMaxCurrentDelay.Q THEN
	r_GenCurSetpointModified := r_GensetMaxCurrent;
ELSIF NOT b_ConditionalStart THEN
	r_GenCurSetpointModified := r_gensetMinCurrent;
ELSE 
	r_GenCurSetpointModified := r_GenCurSetpointLoadStart;
END_IF
	
//shift setpoint from current to zero if generator can not maintain frequency.
IF soft.generator.e_GensetMode = egensetmode.Isochronous AND emodelocal <> UgridDroop THEN
	r_GenCurSetpoint := LIMIT(0,scale(
		monitor.powerstack.r_FrequencyD7,
		settings.GridParams.r_GridFrequencyMin, 
		monitor.controlfb.Operation.system.r_NominalFrequency,
		0,
		r_GenCurSetpointModified),
		r_GenCurSetpointModified);
ELSE
	r_GenCurSetpoint := r_GenCurSetpointModified;	
END_IF

//Iso generator power setpoint override by user
IF monitor.controlfb.Operation.system.r_Pset < 0 THEN
	r_GenCurSetpoint := kwtoCurrent(-monitor.controlfb.Operation.system.r_Pset, monitor.powermonitor.OutputField.ar_LineVoltage[0]);
END_IF


//Activate mode
IF b_active AND (b_TimeSlot1 OR b_TimeSlot2) AND enable THEN
	CASE soft.generator.e_GensetMode OF
		egensetmode.FixedPower:
			MapGensetTarget.PIDmode := ePIDmode.None;
//		egensetmode.Droop:
//			MapgensetTarget.b_DisableSocDrooping := FALSE;
//			MapGensetTarget.r_FeedInCurrentLimit := settings.Properties.r_ratedCurrentInput;
//			MapGensetTarget.r_SupplyCurrentLimit := settings.Properties.r_ratedCurrentInput;
//			MapGensetTarget.PIDmode := ePIDmode.None;
		egensetmode.Isochronous, egensetmode.Droop:
			MapgensetTarget.b_GenIsoPID := TRUE;
			MapGensetTarget.r_SupplyCurrentLimit := MIN(r_gencursetpoint, settings.Properties.r_ratedCurrentInput);
			MapGensetTarget.r_FeedInCurrentLimit := -  MIN(r_gencursetpoint, settings.Properties.r_ratedCurrentInput);
			MapGensetTarget.PIDmode := ePIDmode.BOTH;
	END_CASE
END_IF

//raise invalid params and disable PID
IF r_GensetMinCurrent > r_GensetEffCurrent OR r_GensetEffCurrent > r_GensetMaxCurrent THEN
	get.events.b_InvalidGensetParameters := TRUE;
ELSE
	get.events.b_InvalidGensetParameters := FALSE;
END_IF

//reset current limits, to have nice ramp when starting.
IF MapGensetTarget.PIDmode = ePIDmode.None THEN
	MapGensetTarget.r_FeedInCurrentLimit := -r_GensetMinCurrent;
	MapGensetTarget.r_SupplyCurrentLimit := r_GensetMinCurrent;
END_IF

//Loadbank control, overwrite existing targetvalues
IF batfullstart.Q OR ChargeLoadStart.Q THEN
	MapGensetTarget.r_FeedInCurrentLimit := r_loadbankMaxCurrent;
	MapGensetTarget.r_SupplyCurrentLimit := 0;
END_IF

MapGensetTarget.Measurements.r_ActivePower := r_ActivePower;		
MapGensetTarget.Measurements.r_PhaseVoltage := r_PhaseVoltage;
MapGensetTarget.Measurements.r_ReactivePower:= r_ReactivePower;
]]></ST>
      </Implementation>
    </Method>
    <Method Name="MapGridTarget" Id="{4edf4767-1cd0-44a9-99b9-dd7150491a48}" FolderPath="ControlTarget Methods\">
      <Declaration><![CDATA[METHOD MapGridTarget : ST_PowerControl_Target;
VAR_IN_OUT CONSTANT
	Slot1 						: ST_peakshave_setpoints;
	Slot2 						: ST_peakshave_setpoints;
	r_ActivePower				: ARRAY [0..3] OF REAL;
	r_ReactivePower				: ARRAY [0..3] OF REAL;
END_VAR

VAR_INST
	b_enable: BOOL;
	singlePhaseMode : BOOL;
	
	sr_socTarget	: SR;
	r_IdlePowerTarget : REAL;
	r_SocTarget	: REAL;
END_VAR

VAR_INPUT
	r_phaseVoltage				: REAL;
	r_FeedInCurrentLimit		: REAL;
	r_SupplyCurrentLimit		: REAL;
	b_active					: BOOL;
	b_enableSocTarget			: BOOL;
	PeakshaveMode				: ePeakshaveMode;
END_VAR

VAR
	i_reverseFactor				: INT;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[//define value which is invalid such that function will not be used.
MapgridTarget.r_PIDRampRate := settings.MachineParams.system.GenGridController.r_PIDLimitRampDefault;
MapgridTarget.b_GenIsoPID := FALSE;	
MapGridtarget.PeakshaveMode := TRUE;

b_enable :=  b_active AND (b_TimeSlot1 OR b_TimeSlot2);

MapGridTarget.r_FeedInCurrentLimit := ThreepointSelector(
		r1max := r_FeedinCurrentLimit,
		r2 := slot1.r_FeedInCurrentLimitSoft,
		r3 := slot2.r_FeedInCurrentLimitSoft,
		b2 := b_TimeSlot1,
		b3 := b_TimeSlot2);
		
	MapGridTarget.r_SupplyCurrentLimit := ThreepointSelector(
		r1max := r_SupplyCurrentLimit,
		r2 := slot1.r_SupplyCurrentLimitSoft,
		r3 := slot2.r_SupplyCurrentLimitSoft,
		b2 := b_TimeSlot1,
		b3 := b_TimeSlot2);

	r_IdlePowerTarget := ThreepointSelector(
		r1max := 1000,
		r2 := slot1.r_IdleChargePower,
		r3 := slot2.r_IdleChargePower,
		b2 := b_TimeSlot1,
		b3 := b_TimeSlot2);
		
	r_SocTarget := ThreepointSelector(
		r1max := 100,
		r2 := slot1.r_SocTarget,
		r3 := slot2.r_SocTarget,
		b2 := b_TimeSlot1,
		b3 := b_TimeSlot2);
		
IF b_enable THEN
	MapGridTarget.PIDmode := ePIDmode.Both;
	
	
	IF b_enableSocTarget THEN
		sr_socTarget(
			SET1 := r_soc < r_SocTarget - st_params.r_SocHysteresis OR r_soc > r_SocTarget + st_params.r_SocHysteresis,
			RESET := r_soc = r_soctarget);
		
		IF r_Soc < r_socTarget AND sr_socTarget.Q1 THEN // when idletarget set to charging (negative) or soc target implies charging
			MapGridTarget.r_PowerTarget := -r_IdlePowerTarget;
		ELSIF r_Soc > r_SocTarget AND sr_socTarget.Q1 THEN
			MapGridTarget.r_PowerTarget := r_IdlePowerTarget;
		ELSE
			MapGridTarget.r_PowerTarget := 0;
		END_IF
	ELSE
		MapGridTarget.r_PowerTarget := control.Operation.system.r_Pset;	
	END_IF

ELSE
	//MapGridTarget.r_FeedInCurrentLimit := monitor.powerstack.r_RatedPower;
	//MapGridTarget.r_SupplyCurrentLimit := monitor.powerstack.r_RatedPower;
	MapGridTarget.PIDmode := ePIDmode.None;
END_IF

PeakshaveTotalizer(
	ActivePower := r_ActivePower,
	ReactivePower := r_ReactivePower,
	FeedInCurrent_A := MapGridTarget.r_FeedInCurrentLimit,
	SupplyCurrent_A := MapGridTarget.r_SupplyCurrentLimit,
	singleMode := PeakshaveMode = ePeakshaveMode.Singlephase,
	PhaseVoltage_V := r_phaseVoltage,
	TotalActivePowerMod => MapGridTarget.Measurements.r_ActivePower,
	TotalReactivePowerMod => MapGridTarget.Measurements.r_ReactivePower);

MapGridTarget.Measurements.r_PhaseVoltage := r_PhaseVoltage;
]]></ST>
      </Implementation>
    </Method>
    <Method Name="ModeSwitch" Id="{9c3f2fd1-525e-44ea-a26c-2f043e7ed724}" FolderPath="Nested Methods\">
      <Declaration><![CDATA[METHOD PRIVATE ModeSwitch : BOOL
VAR_INPUT
	RequestedMode			: eBreakerOperationMode;
END_VAR

VAR_INST
	b_EnableInputGridTriggers	: BOOL;
	b_ManualinputControl	: BOOL;
	rTrigModeTransManualClose	: R_TRIG;
	rTrigModeTransToggle		: R_TRIG;
	rTrigModeTransEmstop		: R_TRIG;
	fTrigReset					: F_TRIG;
	rTrigModeTransshutdown		: R_TRIG;
	rTrigModeTransCLimit		: R_TRIG;
	fTrigModeACreleased			: F_TRIG;
	tofRetryTimeOut				: TOF := (PT := T#60S);
	by_cLimitCounter			: BYTE;
	AllowModeSwitch				: BOOL;
	b_inhibitSum				: BOOL;
	b_AckRQSum					: BOOL;
	b_allowModeTransGen			: BOOL;
	
	b_GridAtOutput				: BOOL;
	b_UnwantedGenACatInput		: BOOL;	
	
	TonRecoverFromDisconnectDelay	: TON := (PT:= T#1S);
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[//reset events
get.events.b_TransToGenDroopInhibit := FALSE;
b_ManualinputControl := FALSE;
b_EnableInputGridTriggers := FALSE;
get.events.b_TransToGenIsoInhibit := FALSE;
get.events.b_TransToGenFixInhibit := FALSE;
get.events.b_TransFromInputGridAckRQ := FALSE;
get.events.b_TransFromInputGenAckRQ := FALSE;
b_allowModeTransGen := FALSE;
get.events.b_StartingInhibit := NOT b_InputMCCBfb AND BreakerOperationMode <> eBreakerOperationMode.None;
//Predefine some conditions
b_GridAtOutput := monitor.powerstack.b_GridACdetected AND NOT inputcontactor.b_fb AND NOT monitor.powerstack.b_InverterGridFormingMode;
b_UnwantedGenACatInput := b_inputACOK AND NOT inputcontactor.b_fb AND b_BusbarACOK;
get.b_ModeChanged := RequestedMode <> BreakerOperationMode;


//inhibited conditions
CASE RequestedMode OF
	eBreakerOperationMode.GenIso: 
		get.events.b_TransToGenIsoInhibit := b_GridAtOutput OR b_AFEactive;
	eBreakerOperationMode.GenDroop:
		get.events.b_TransToGenDroopInhibit := b_GridAtOutput OR b_AFEactive; // OR b_UnwantedGenACatInput;
	eBreakerOperationMode.genfix:
		get.events.b_TransToGenFixInhibit := b_UnwantedGenACatInput;
END_CASE

fTrigModeACreleased();
//Acknowledgeable conditions
CASE BreakerOperationMode OF
	eBreakerOperationMode.GridFeedthrough: 
		b_EnableInputGridTriggers := TRUE;
		b_ManualinputControl	:= NOT (b_autoSwitching OR b_Breakerfb OR get.b_ModeChanged);
		fTrigModeACreleased.CLK := b_breakerACOK;
		get.events.b_TransFromInputGridAckRQ := RequestedMode <> BreakerOperationMode AND InputContactor.b_fb AND b_inputACOK;
	eBreakerOperationMode.GenDroop, eBreakerOperationMode.GenIso: 
		get.events.b_TransFromInputGenAckRQ := RequestedMode <> BreakerOperationMode AND ((InputContactor.b_fb AND b_inputACOK) OR b_IOStartStop) AND enable;
		IF RequestedMode = eBreakerOperationMode.GenIso OR RequestedMode = eBreakerOperationMode.GenDroop THEN
			get.events.b_TransFromInputGenAckRQ := FALSE;
			b_allowModeTransGen := TRUE;
		END_IF
		
		b_SkipGensetCooldown := RequestedMode = eBreakerOperationMode.GridFeedthrough;
END_CASE

b_AckRQSum := 
	get.events.b_TransFromInputGridAckRQ OR
	get.events.b_TransFromInputGenAckRQ OR b_ManualinputControl;

b_inhibitSum := 
	get.events.b_TransToGenIsoInhibit OR
	get.events.b_TransToGenDroopInhibit OR
	b_SFCmodeTransInhibit;

IF BreakerOperationMode = RequestedMode AND NOT b_inhibitSum THEN
	get.b_ModeTransInhibit := FALSE;
ELSE
	get.b_ModeTransInhibit := b_inhibitSum;
END_IF

get.b_ShowModeTrans := ShowModeTransButton();

//if SFC is not active
IF NOT get.b_active THEN
	AllowModeSwitch := NOT (get.b_ModeTransInhibit OR b_AckRQSum);
ELSE
	AllowModeSwitch := b_allowModeTransGen;	
END_IF

//MODE CHANGE TRIGGERS
rTrigModeTransClimit(
	CLK := CurrentLimitProtection(
				enable := control.SoftSettings.inputgrid.Breaker.CurrentLimitDisconnect AND b_EnableInputGridTriggers,
				FeedinLimit := targetdata.r_FeedInCurrentLimit,
				SupplyLimit := targetdata.r_SupplyCurrentLimit,
				Current := monitor.powermonitor.InputField.ar_Current[0],
				power := monitor.powermonitor.inputfield.ar_activepower[0],
				tripdelay := st_params.CurrentLimitTripDelay));

// reset counter after 1 min of the trigger event.
tofRetryTimeOut(IN := rTrigModeTransClimit.Q);
IF NOT tofRetryTimeOut.Q THEN
	by_cLimitCounter := 0;
END_IF
		
IF rTrigModeTransClimit.Q THEN
	by_cLimitCounter := by_cLimitCounter + 1;
	get.events.b_CurrentLimitDisconnect := TRUE;
	get.b_ModeTransActive := TRUE;
END_IF

IF by_climitCounter > 0 AND get.b_ModeTransActive AND NOT b_breakerfb THEN
	get.events.b_CurrentLimitDisconnect := FALSE;
	IF by_climitCounter <= control.SoftSettings.inputgrid.Breaker.CurrentLimitRetries THEN
		get.b_ModeTransActive := FALSE;
	ELSE
		get.events.b_CurrentLimitTrip := TRUE;
	END_IF
END_IF

TonRecoverFromDisconnectDelay();
// triggers for disconnection of input
IF b_EnableInputGridTriggers AND settings.Configuration.b_ACInputConnection THEN
	rTrigModeTransEmstop(CLK := (gvl.b_QuickshutdownActive OR gvl.b_EmergencyShutdownActive) AND control.SoftSettings.inputgrid.Breaker.EMstopDisconnect);
	IF rTrigModeTransEmstop.Q THEN get.events.b_EmstopDisconnect := TRUE; TonRecoverFromDisconnectDelay.IN := b_autoSwitching; get.b_ModeTransActive := TRUE; END_IF
	rTrigModeTransShutdown(CLK := Monitor.system.e_State = eSystemState.shutdown AND control.SoftSettings.inputgrid.Breaker.ShutdownDisconnect);
	IF rTrigModeTransShutdown.Q THEN  get.events.b_shutdownDisconnect := TRUE; TonRecoverFromDisconnectDelay.IN := b_autoSwitching; get.b_ModeTransActive := TRUE; END_IF
	rTrigModeTransToggle(CLK := b_ActivateTransition);
	IF rTrigModeTransToggle.Q THEN get.b_ModeTransActive := NOT get.b_ModeTransActive; END_IF
	rTrigModeTransManualClose(CLK := b_ManualinputControl);
	IF rTrigModeTransManualClose.Q THEN get.b_ModeTransActive := TRUE; TonRecoverFromDisconnectDelay.IN := FALSE; END_IF
ELSE
	get.b_ModeTransActive := FALSE;	
END_IF

//auto clear emstop trigger once battery is ready again after EMstop
IF TonRecoverFromDisconnectDelay.Q AND b_BESSReady AND get.b_ModeTransActive THEN
	TonRecoverFromDisconnectDelay.IN := FALSE;
	get.b_ModeTransActive := FALSE;
END_IF

//reset disconnection triggers
fTrigReset(CLK := get.b_ModeTransActive);
IF fTrigReset.Q THEN
	get.events.b_EmstopDisconnect := FALSE;
	get.events.b_ShutdownDisconnect := FALSE;
END_IF

ModeSwitch := AllowModeSwitch AND NOT get.b_ModeTransActive;]]></ST>
      </Implementation>
    </Method>
    <Method Name="PeakshaveTotalizer" Id="{00bcbfcc-c2fe-4548-b131-b4ad1f8b25b7}" FolderPath="ControlTarget Methods\">
      <Declaration><![CDATA[METHOD PeakshaveTotalizer : BOOL
(*
    PeakshaveTotalizer
    - Inputs:
        ActivePower[kW], ReactivePower[kvar] per phase; index 0 = totals
        FeedInCurrent_A (>=0), SupplyCurrent_A (>=0)  -- CURRENT limits
        SingleMode = TRUE  -> enforce per-phase envelope (recommended)
        SingleMode = FALSE -> pass-through totals (with optional slew)
        PhaseVoltage_V = L-N RMS (e.g. 230 V)
        SafetyMargin_kW : small guard so we don't graze the boundary
        EnvTau_s        : low-pass on the safe envelope to kill jitter
        SlewP_kW_per_s / SlewQ_kvar_per_s with CycleTime_s
    - Outputs:
        TotalActivePowerMod (kW), TotalReactivePowerMod (kvar)
*)

VAR_IN_OUT CONSTANT
    ActivePower   : ARRAY[0..3] OF REAL;   // kW   [0]=totaal, [1..3]=L1..L3
    ReactivePower : ARRAY[0..3] OF REAL;   // kvar [0]=totaal, [1..3]=L1..L3
END_VAR
VAR_INPUT
    FeedInCurrent_A  : REAL;               // per-fase exportlimiet [A]
    SupplyCurrent_A  : REAL;               // per-fase importlimiet [A]
    SingleMode       : BOOL;               // TRUE = fase-selectie
    PhaseVoltage_V   : REAL := 230.0;      // L-N spanning [V]
END_VAR
VAR_OUTPUT
    TotalActivePowerMod   : REAL;          // kW
    TotalReactivePowerMod : REAL;          // kvar
END_VAR
VAR_INST
    Vph : REAL;
    Ptot, Qtot : REAL;
    Pmod: REAL;
    tmp : REAL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[(* basis: LN spanning *)
IF PhaseVoltage_V > 0.0 THEN
    Vph := PhaseVoltage_V;
ELSE
    Vph := 230.0;
END_IF;

Ptot := ActivePower[0];
Qtot := ReactivePower[0];

(* Multiphase = gewoon totaal doorgeven *)
IF NOT SingleMode THEN
    TotalActivePowerMod   := Ptot;
    TotalReactivePowerMod := Qtot;
    PeakshaveTotalizer := TRUE;
    RETURN;
END_IF;

(* kandidaat totaal = 3 × fase *)
Ptot := ActivePower[0];
IF Ptot > 30 THEN
    Pmod := 3.0 * MAX(ActivePower[1], ActivePower[2], ActivePower[3]);   // export: hoogste fase ×3
ELSIF Ptot < 0 THEN
    Pmod := 3.0 * MIN(ActivePower[1], ActivePower[2], ActivePower[3]);   // import: laagste (meest neg.) fase ×3
ELSE
    Pmod := Ptot;          // of ActivePower[0], of een kleine deadband
END_IF

(* kandidaat totaal = 3 × fase *)
//Pmod := 3.0 * ActivePower[phase];

(* outputs *)
TotalActivePowerMod   := Pmod;   // hierop laat je PID peakshaven
TotalReactivePowerMod := Qtot;   // Q onveranderd
PeakshaveTotalizer := TRUE;
]]></ST>
      </Implementation>
    </Method>
    <Method Name="Reset" Id="{8159a793-262c-47cf-9d98-bb9113c21bdf}">
      <Declaration><![CDATA[METHOD Reset : BOOL
VAR_INPUT
END_VAR

VAR_INST
	EmptyEventStruct 	: ST_GengridController_events;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[get.events := EmptyEventStruct;
RESET := GenFreqVoltProtections(FALSE, FALSE ,TRUE, 0);
]]></ST>
      </Implementation>
    </Method>
    <Action Name="RUN_active" Id="{862ee07e-68c5-48d0-a3b3-eae97627fbfa}" FolderPath="SFC\">
      <Implementation>
        <ST><![CDATA[get.e_state := eGenGridState.Running;
SFCTransTrigger.in := FALSE;

//TRANSITION
CASE BreakerOperationMode OF
	eBreakerOperationMode.GenIso, eBreakerOperationMode.GenDroop:
		b_ActivatePowerControl := b_GenStarted;
		get.b_gensetStarting := FALSE;
		IF b_hybridMode THEN
			SFCTransTrigger.in := GenDownCheck(TRUE, FALSE);
		ELSE
			SFCTransTrigger.in := NOT b_StartCondition OR GenDownCheck(TRUE, FALSE);
		END_IF
		
		
	eBreakerOperationMode.Genfix:
		//SFCTransTrigger.in := NOT b_StartCondition OR GenDownCheck(TRUE, FALSE)  OR GenFreqProtections(TRUE, FALSE,FALSE, Monitor.powermonitor.InputField.ar_ActivePower[0]);
		//SFCTransTrigger.in := GenDownCheck(b_StartCondition, FALSE) OR GenFreqProtections(TRUE, FALSE,FALSE, Monitor.powermonitor.InputField.ar_ActivePower[0]);
		SFCTransTrigger.in := NOT b_BusbarACOK OR GenFreqVoltProtections(TRUE, FALSE,FALSE, Monitor.powermonitor.InputField.ar_ActivePower[0]);
		b_IOstartStop := b_StartCondition;
		get.b_gensetStarting := FALSE;
		b_ActivatePowerControl := b_GenStarted;
		IF NOT b_IOstartStop THEN
			get.e_state := eGenGridState.Waiting_Trigger;
		ELSE
			IF Monitor.powermonitor.InputField.ar_ActivePower[0] = 0 THEN
				get.e_state := eGenGridState.Starting;
			END_IF
		END_IF
	
	eBreakerOperationMode.GridFeedthrough, eBreakerOperationMode.ExtGrid: 
		b_ActivatePowerControl := TRUE;
		IF NOT GridOKDetect(NOT b_AMFEnabled) OR ZeroCurrentDisconnect() THEN
			IF NOT b_AutoSwitching THEN
				Get.b_ModeTransActive := TRUE;
			ELSE
				SFCTransTrigger.in := TRUE;
			END_IF
		END_IF
END_CASE

IF NOT monitor.powerstack.b_ControlEnabled OR NOT b_breakerfb OR Get.b_ModeTransActive OR NOT b_InputMCCBfb THEN
	SFCTransTrigger.in := TRUE;
END_IF

SFCtip := SFCTransTrigger.Q AND NOT SFCtip;]]></ST>
      </Implementation>
    </Action>
    <Method Name="SetBreakerAndPowercontrolMode" Id="{b58b8bd4-f217-4404-8804-dd45757cd8e7}" FolderPath="Nested Methods\">
      <Declaration><![CDATA[METHOD SetBreakerAndPowercontrolMode : BOOL
VAR_INPUT
	ACInputType				: eACinputType;
	GridMode				: eGridMode;
	GensetMode				: eGensetMode;
	PSBMode					: ePSBMode;
	//b_extBreakerControl		: BOOL;
	PSBenable				: BOOL;
	b_extGenset				: BOOL;
END_VAR

VAR_IN_OUT
	PowerControlMode		: ePowerControlMode;
	ExtGensetMode			: BOOL;
END_VAR

VAR_INST
	RequestedBreakerMode	: eBreakerOperationMode;
END_VAR

]]></Declaration>
      <Implementation>
        <ST><![CDATA[//Initialize values
get.events.b_TransToGenIsoInhibit := FALSE;


	

//Default values
RequestedBreakerMode := eBreakerOperationMode.none;
CASE ACInputType OF
	eACinputType.grid: 
		RequestedBreakerMode := eBreakerOperationMode.GridFeedthrough;
	eACinputType.Genset: 
		CASE GensetMode OF
			eGensetMode.isochronous				: RequestedBreakerMode := eBreakerOperationMode.GenIso;
			eGensetMode.Droop					: RequestedBreakerMode := eBreakerOperationMode.GenDroop;
			eGensetMode.FixedPower				: RequestedBreakerMode := eBreakerOperationMode.GenFix;
		END_CASE
END_CASE

//breaker mode is most strict, and can be changed if modetransinhibit and no transition is active. ==> output of method
IF Modeswitch(RequestedMode := RequestedBreakerMode) THEN
	BreakerOperationMode := RequestedBreakerMode;	
END_IF

//power control is less strict, and can be changed if modetransinhibit is false
IF NOT get.b_ModeTransInhibit AND BreakerOperationMode = RequestedBreakerMode THEN
	CASE ACInputType OF
		eACinputType.grid: 
			PowerControlMode := ePowerControlMode.PeakshaveInputGrid; 
		eACinputType.Genset: 
			PowerControlMode := ePowerControlMode.PeakshaveInputGen;
		eACinputType.None:
			PowerControlMode:= ePowerControlMode.none;	
	END_CASE
END_IF


// Activation of PSB as powercontrol source (only when no generator is at input)
IF PSBenable AND BreakerOperationMode < 3 THEN
	CASE PSBMode OF
		ePSBMode.Monitor:
			PowerControlMode:= ePowerControlMode.PeakshaveExt;
		ePSBMode.MonitorControl:
			RequestedBreakerMode := eBreakerOperationMode.ExtGrid;		
	END_CASE
END_IF

	//ext genset control enabling
ExtGensetMode := ACInputType <> eACinputType.Genset AND b_extGenset;
get.b_gensetcontrol:= b_extGenset OR BreakerOperationMode = eBreakerOperationMode.GenFix OR BreakerOperationMode = eBreakerOperationMode.GenIso; 

//Fill get 
get.e_BreakerMode := BreakerOperationMode;
get.e_PowerControlMode := PowerControlMode;
get.e_GensetMode := control.softSettings.inputgenset.generator.e_GensetMode;
get.b_extGensetMode := ExtGensetMode;


]]></ST>
      </Implementation>
    </Method>
    <Method Name="SetInverterMode" Id="{bbf3ded8-d957-4271-9f77-5adb42bbce7d}" FolderPath="Nested Methods\">
      <Declaration><![CDATA[METHOD SetInverterMode : BOOL
VAR_INPUT
	Gridmode			: 	eGridmode;
	UgridPowermode		: 	eUgridpowermode;
	BreakerMode			:	eBreakerOperationMode;
	PSBMode				: 	ePSBMode;
	b_InputGridcodeEnabled	: 	BOOL;
	b_gridacDetected	: 	BOOL;
	b_PowerstackStarted	:	BOOL;
	b_ExtFb				: 	BOOL; //OPEN IS TRUE
	b_InputFB			: 	BOOL; //OPEN IS TRUE
	b_AMF				: 	BOOL;
END_VAR

VAR_OUTPUT
	b_MasterSlaveEnabled: BOOL;
END_VAR

VAR_INST
	b_parallelUgrid		: 	BOOL;
	b_test : BOOL;
END_VAR

]]></Declaration>
      <Implementation>
        <ST><![CDATA[b_ExtGridConnected := FALSE;
b_slowLom := TRUE;


//Get invertermode from breakermode
CASE BreakerMode OF
	eBreakerOperationMode.none:
		IF inputcontactor.b_fb THEN
			InputContactor.open(TRUE);
		END_IF
		b_slowLom := FALSE;
		
		IF NOT b_PowerstackStarted THEN
			IF NOT b_gridAcDetected THEN
				eModeLocal := UgridIsland;
			ELSE
				eModeLocal := AFE;
			END_IF
		END_IF
		
		//Overwrite for manual choice user or overruling parameters
	CASE gridmode OF
		egridmode.following: eModeLocal := AFE;
		egridmode.forming: eModeLocal := UgridDroop;	
	END_CASE
		
	eBreakerOperationMode.GridFeedthrough:
		IF NOT get.b_active AND NOT monitor.powerstack.b_ControlEnabled THEN
			InputContactorNC(b_autoSwitching);
		END_IF
		
		b_ExtGridConnected := b_inputACOK AND b_InputFB;
		IF NOT b_InputFB AND (NOT b_gridACdetected OR Gridmode = eGridmode.forming) THEN // OR (NOT b_netcontactorFB AND NOT GridOKdetect(FALSE)) THEN
			eModeLocal := SEL(Gridmode = eGridmode.forming, UgridIsland, UgridDroop);
		ELSIF b_inputgridCodeEnabled AND Gridmode <> egridmode.forming AND NOT get.b_ModeTransActive THEN
			eModeLocal := AFE;
		ELSE
			eModeLocal := UgridIso;
			b_slowLom := control.SoftSettings.inputgrid.b_WeakGridInput AND NOT b_inputgridCodeEnabled;
		END_IF
			
	eBreakerOperationMode.GenDroop:
		IF NOT get.b_active AND NOT monitor.powerstack.b_ControlEnabled AND NOT get.b_ModeTransActive THEN
			IF get.e_GensetStartStop = eGensetStartStop.Start AND monitor.ACswitchgear.b_InputMCCBfb THEN
					Inputcontactor.Close(TRUE);
			ELSE
					Inputcontactor.Open(TRUE);
			END_IF
		END_IF
		eModeLocal := UgridDroop;
	
	eBreakerOperationMode.GenFix:
		IF NOT get.b_active AND NOT monitor.powerstack.b_ControlEnabled AND NOT get.b_ModeTransActive THEN
			IF get.e_GensetStartStop = eGensetStartStop.Start AND monitor.ACswitchgear.b_InputMCCBfb THEN
					Inputcontactor.Close(TRUE);
			ELSIF NOT b_BusbarACOK THEN
				 Inputcontactor.Open(TRUE);		
			END_IF
		END_IF
	
		eModeLocal := UgridIsland;
		IF b_gridAcDetected THEN
			eModeLocal := AFE;
		END_IF
		
	eBreakerOperationMode.GenIso:
		b_slowLom := TRUE;
		IF NOT get.b_active AND NOT monitor.powerstack.b_ControlEnabled AND NOT get.b_ModeTransActive THEN
			IF get.e_GensetStartStop = eGensetStartStop.Start AND monitor.ACswitchgear.b_InputMCCBfb THEN
					Inputcontactor.Close(TRUE);
			ELSE
					Inputcontactor.Open(TRUE);
			END_IF
		END_IF
		
		IF st_params.GenIso_InverterMode <> eGenIsoInvertermode.AFE THEN
			eModeLocal := UgridIso;
		ELSE
			eModeLocal := AFE;
		END_IF
	
		IF NOT b_InputFB THEN
			eModeLocal := SEL(Gridmode = eGridmode.forming, UgridIsland, UgridDroop);
		END_IF
		
	eBreakerOperationMode.ExtGrid:
		eModeLocal := AFE;
		IF b_AMF AND b_ExtFb THEN
			eModeLocal := UgridIsland;
		END_IF
END_CASE

//Overwrite for grid detection
//IF b_AcDetected THEN
//	eModeLocal := AFE;
//END_IF

CASE GridMode OF
	eGridmode.forming: 
		eModeLocal := UgridDroop;
	eGridmode.following: 
		eModeLocal := AFE;	
END_CASE

//Catch mode inverter and powermode
CASE eModeLocal OF
	AFE 		: InverterMode := eInverterModes.Afe; PowerMode :=  ePowerModes.Droop;
	UgridDroop 	: InverterMode := eInverterModes.microgrid; PowerMode :=  ePowerModes.Droop;
	UgridIsland	: InverterMode := eInverterModes.Island; PowerMode :=  ePowerModes.Droop;	
	UgridIso	: InverterMode := eInverterModes.microgrid; PowerMode :=  ePowerModes.Isochronous;	
END_CASE

//MANUAL OVERWRITES
//Overwrite for manual choice user
CASE UgridPowermode OF
	eUgridPowermode.Droop: Powermode := ePowermodes.Droop;
	eUgridPowermode.DroopZeroStart: Powermode := ePowermodes.DroopZeroStart;
	eUgridPowermode.Isochronous: Powermode := ePowermodes.Isochronous;	
END_CASE

//Overwrite for parallel setup
IF (eModeLocal = UgridIsland AND b_parallelUgrid) THEN
	InverterMode := eInvertermodes.Microgrid;
END_IF



]]></ST>
      </Implementation>
    </Method>
    <Action Name="SFCTipReset" Id="{a17eec88-22ac-4b41-811b-51c96fe81c5d}" FolderPath="SFC\">
      <Implementation>
        <ST><![CDATA[SFCTip:= FALSE;
SFCtransTrigger.in := FALSE;
b_SFCmodetransInhibit := FALSE;
SFCResetTrigger := FALSE;
]]></ST>
      </Implementation>
    </Action>
    <Method Name="ShowModeTransButton" Id="{fb69b69e-fa1e-424b-996a-63a8d5b2753c}" FolderPath="Nested Methods\">
      <Declaration><![CDATA[METHOD ShowModeTransButton : BOOL
VAR_INPUT
END_VAR

VAR_INST
	b_ConditionalShow : BOOL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[CASE breakeroperationMode OF
	eBreakerOperationmode.GridFeedthrough: b_ConditionalShow := inputcontactor.b_fb;
	eBreakerOperationmode.Geniso: b_ConditionalShow := inputcontactor.b_fb AND b_hybridMode;
	ELSE
		b_ConditionalShow := FALSE;
END_CASE

ShowModeTransButton := get.b_ModeTransActive OR b_ConditionalShow;]]></ST>
      </Implementation>
    </Method>
    <Method Name="StartSequence" Id="{e69538f5-281d-46bd-8418-13b373470bfb}" FolderPath="Nested Methods\">
      <Declaration><![CDATA[METHOD StartSequence : BOOL
VAR_INPUT
	Mode			: eBreakerOperationMode;
	b_BreakerFb		: BOOL;
	b_ACOk			: BOOL;
	b_gridFollowingmode	: BOOL;
END_VAR
VAR_OUTPUT
	SFCReset		: BOOL;
END_VAR

VAR_INST
	SequenceOption1 :  ARRAY [0..4] OF BYTE := [1,2,3,0,0];	//Warmup/start then close contactor
	SequenceOption3 :  ARRAY [0..4] OF BYTE := [2,3,0,0,0]; //Close without warmup time 
	
	ExecIndex 			: BYTE;
	b_ExtContactor		: BOOL;
	by_SequenceIndexes 	: ARRAY [0..4] OF BYTE;
	ton_ResetSEQ		: TON := (PT:= T#20S);
	b_SynchroneGenset	: BOOL;	
	b_escapeCondition	: BOOL;
	by_CurrentStep		: BYTE;

	by_RetryCounter		: BYTE;
	b_trigger			: BOOL;
	b_GenOnly			: BOOL;

	ton_SeqPulse		: TON := (PT :=T#20MS);
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[b_GenOnly:= FALSE;
SFCreset := FALSE;

CASE mode OF
  	eBreakerOperationMode.GridFeedthrough, eBreakerOperationMode.ExtGrid : 
		by_SequenceIndexes := SequenceOption3; b_SynchroneGenset := FALSE; b_escapeCondition := b_breakerFB; 
  		b_GenOnly:= FALSE;
	eBreakerOperationMode.GenDroop:  
		by_SequenceIndexes := SequenceOption1; b_SynchroneGenset := FALSE; b_escapeCondition := b_breakerFB AND b_AcOK; //b_genstarter
		b_GenOnly:= TRUE;
	eBreakerOperationMode.GenIso :  
		by_SequenceIndexes := SequenceOption1; b_SynchroneGenset := FALSE; b_escapeCondition := b_breakerFB AND b_AcOK;
		b_GenOnly:= TRUE;
	eBreakerOperationMode.GenFix :  
		by_SequenceIndexes := SequenceOption3; b_SynchroneGenset := TRUE; b_escapeCondition := b_breakerFB;
		b_GenOnly:= TRUE;
END_CASE

get.b_gensetStarting := b_GenOnly;

StartSequence := FALSE;
b_ExtContactor := mode = eBreakerOperationMode.ExtGrid;
ton_ResetSEQ();

//SEQUENCER
CASE by_SequenceIndexes[ExecIndex] OF
	0: 	ExecIndex := 0; StartSequence := TRUE; by_RetryCounter := 0; by_CurrentStep := 0;
	1:	ton_ResetSEQ.IN := FALSE; by_CurrentStep := 1;
		b_trigger := Warmup(get.b_gensetHot);
	2:  b_trigger := SEL(b_ExtContactor, Inputcontactor.Close(b_SynchroneGenset OR b_GridFollowingMode), Extcontactor.Close(FALSE));
		get.e_state := eGenGridState.Synchronization; by_CurrentStep := 2;
		ton_ResetSEQ.IN := TRUE;
	3:	b_trigger := b_escapeCondition; by_CurrentStep := 3;
		get.e_state := eGenGridState.Starting;
END_CASE

ton_SeqPulse(IN := b_trigger AND NOT ton_SeqPulse.Q);
IF ton_SeqPulse.Q THEN
	ExecIndex := ExecIndex +1;
END_IF

IF ton_ResetSEQ.Q THEN
	ExecIndex := 0;
	ton_ResetSEQ.IN := FALSE;
	by_RetryCounter := by_RetryCounter + 1;
END_IF

IF by_RetryCounter > st_params.by_SyncRetries THEN
	by_RetryCounter := 0;
	get.events.b_WarmupFault := by_CurrentStep = 1;
	get.events.b_SynchronisationFault := by_CurrentStep = 2;
	get.events.b_StartupFault := by_CurrentStep = 3;
END_IF

//The exit from the current step. if breaker already closed, continue normal SFC procedure.
IF b_genOnly AND NOT b_startcondition AND NOT b_BreakerFb THEN
	b_IOStartStop := FALSE;
	SFCreset := TRUE;
END_IF

]]></ST>
      </Implementation>
    </Method>
    <Method Name="StartStopConditions" Id="{ed96d143-018a-4dd6-bfaf-c6fca19cd270}" FolderPath="Nested Methods\">
      <Declaration><![CDATA[METHOD StartStopConditions
VAR_INPUT
	enable			: BOOL;
END_VAR

VAR_INST
	r_LoadPercentOutput : REAL;
	b_Charging			: BOOL;
	r_InverterLoad		: REAL;
	r_InputLoad			: REAL;
	b_BatErrorGenStartTrigger : BOOL;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[b_Charging:= monitor.powerstack.r_ActivePower < 0;
r_InverterLoad := monitor.powerstack.r_LoadPercent * SEL(b_Charging, 1, -1) * 0.97;// * monitor.system.r_CurrentEfficiency/100;
r_InputLoad	:= monitor.powermonitor.InputField.r_loadshare;
r_LoadPercentOutput := r_InputLoad + r_InverterLoad;

IF enable THEN
	ChargeLoadStart(
		enable:= b_loadbankEnable,
		reset := FALSE,
		value:= monitor.powerstack.r_LoadPercent, 
		startvalue:= MIN(GensetSetpoints.r_BatteryloadStart, monitor.powerstack.r_OvercurrentValueAct *100),
		stopvalue := GensetSetpoints.r_BatteryloadStop - monitor.powermonitor.InputField.r_loadshare,
		OffDelay := T#3M,
		OnDelay := T#10S);
	
	LoadStart(
		enable := monitor.powerstack.b_ControlEnabled,
		reset := r_LoadPercentOutput < -10,// if charging reset.
		value := r_LoadPercentOutput,
		StartValue:= MIN(GensetSetpoints.r_BatteryloadStart, monitor.powerstack.r_OvercurrentValueAct *100),
		StopValue :=  GensetSetpoints.r_BatteryloadStop,
		OffDelay := St_params.Genset.OverloadOffDelay,
		OnDelay := St_params.Genset.OverloadOnDelay,
		);
	
	SoCStart(
		enable := monitor.system.e_State <> eSystemState.Discharging_Only,
		reset := FALSE,
		value := monitor.battery.BatteryInfo.r_SOCScaled,
		StartValue:=  GensetSetpoints.r_SocStart,
		StopValue :=  MAX(GensetSetpoints.r_SocStop, GensetSetpoints.r_SocStart + 0.5));
		
	BatFullStart(
		enable:= b_loadbankEnable,
		reset := monitor.powerstack.r_ActivePower < -5 AND NOT b_loadbankEnable,
		value := monitor.battery.BatteryInfo.r_SOCScaled,
		StartValue:=  control.SoftSettings.system.r_SocMax,
		StopValue :=  control.SoftSettings.system.r_SocMax - settings.MachineParams.BMS.r_SocHysteresis,
		OffDelay := T#3M,
		OnDelay := T#10S
		);


ELSE
	BatFullStart(reset:= TRUE);
	SoCStart(reset := TRUE);
	LoadStart(reset := TRUE);
	ChargeLoadStart(reset := TRUE);
END_IF

//Trigger genset start when battery down.
IF NOT gensetsetpoints.b_StartAtBatteryError OR b_BESSready	THEN
	b_BatErrorGenStartTrigger := FALSE;
ELSIF NOT b_startcondition THEN
	b_BatErrorGenStartTrigger := TRUE;
END_IF

//Summerize conditions
b_StartCondition := ((LoadStart.Q OR SOCStart.Q OR BatFullStart.Q OR ChargeLoadStart.Q OR b_BatErrorGenStartTrigger) AND
						get.e_GensetStartStop= eGensetStartStop.Auto) OR 
						get.e_GensetStartStop= eGensetStartStop.Start;

//get run condition
IF get.e_GensetStartStop= eGensetStartStop.Start THEN
	get.e_RunCondition := eRunCondition.ManuallyStarted;
ELSIF get.e_GensetStartStop= eGensetStartStop.stop THEN
	get.e_RunCondition := eRunCondition.ManuallyStopped;
ELSIF SOCStart.Q THEN
	get.e_RunCondition := eRunCondition.SoC;	
ELSIF LoadStart.Q THEN
	get.e_RunCondition := eRunCondition.DischargeOverload;
ELSIF ChargeLoadStart.Q THEN
	get.e_RunCondition := eRunCondition.ChargeOverload;
ELSIF BatFullStart.Q THEN
	get.e_RunCondition := eRunCondition.BattFull;
ELSE
	get.e_RunCondition := eRunCondition.None;
END_IF
]]></ST>
      </Implementation>
    </Method>
    <Action Name="STARTUP_active" Id="{aa641a6c-a8ec-4648-98d3-37b9088eaa4b}" FolderPath="SFC\">
      <Implementation>
        <ST><![CDATA[get.e_state := eGenGridState.Starting;
b_SFCmodetransInhibit := FALSE;
get.b_active := TRUE;


SFCtip := StartSequence(
			mode := BreakerOperationMode, 
			b_breakerfb := b_breakerFb,
			b_AcOK	:= b_BreakerACok,
			b_gridfollowingMode := b_GridACDetected,
			SFCreset => SFCResetTrigger
			) AND NOT sfctip;

//Reset before running again.		
GenDownCheck(FALSE, TRUE);]]></ST>
      </Implementation>
    </Action>
    <Action Name="STOP_active" Id="{bcfc1d02-3a86-4a21-900a-e64aecf6d818}" FolderPath="SFC\">
      <Implementation>
        <ST><![CDATA[get.e_state := eGenGridState.Stopping;
SFCtransTrigger.in := FALSE;

CASE BreakerOperationMode OF
	eBreakerOperationMode.GenFix:
		IF Cooldown(TRUE) THEN SFCTransTrigger.in := InputContactor.Open(FALSE); END_IF
	eBreakerOperationMode.GenIso, eBreakerOperationMode.GenDroop:
	IF GenDownCheck(FALSE, FALSE) OR NOT b_breakerACOK THEN
		SFCTransTrigger.in := Inputcontactor.Open(TRUE) AND cooldown(TRUE);
	ELSIF NOT b_hybridMode AND b_startCondition AND monitor.powerstack.b_ControlEnabled AND NOT Get.b_ModeTransActive THEN
		InputContactor.Deload(TRUE);
		SFCTransTrigger.in := TRUE;
	ELSE
		SFCTransTrigger.in := InputContactor.Open(b_hybridMode) AND_THEN Cooldown(FALSE);
	END_IF
		
	eBreakerOperationMode.GridFeedthrough:
		IF b_AMFEnabled AND monitor.powerstack.b_ControlEnabled OR get.b_ModeTransActive THEN SFCTransTrigger.in := inputcontactor.Open(NOT Get.b_ModeTransActive OR get.events.b_CurrentLimitTrip);
		ELSE SFCTransTrigger.in := TRUE; END_IF
	eBreakerOperationMode.ExtGrid: 
		IF b_AMFEnabled AND monitor.powerstack.b_ControlEnabled THEN SFCTransTrigger.in := extcontactor.Open(control.SoftSettings.PSB.b_BreakerControl);
		ELSE SFCTransTrigger.in := TRUE; END_IF
END_CASE



SFCtip := SFCTransTrigger.Q AND NOT SFCtip;]]></ST>
      </Implementation>
    </Action>
    <Method Name="ThreePointSelector" Id="{0c212d89-190b-4ea7-9e5c-fab8a16fabc9}" FolderPath="ControlTarget Methods\">
      <Declaration><![CDATA[METHOD ThreePointSelector : REAL
VAR_INPUT
	r1max	: REAL;
	r2      : REAL;
	r3      : REAL;
	b2		: BOOL;
	b3		: BOOL;
END_VAR

VAR
	temp	: REAL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF b2 AND NOT b3 THEN
	temp := r2;
ELSIF NOT b2 AND b3 THEN
	temp := r3;
ELSE
	temp := r1max;
END_IF

ThreepointSelector := LIMIT(0,temp,r1max);]]></ST>
      </Implementation>
    </Method>
    <Action Name="WAITINGTRIGGER_active" Id="{e6f1fc42-1d4a-4c5d-a358-ad84779a8a81}" FolderPath="SFC\">
      <Implementation>
        <ST><![CDATA[get.e_state := eGenGridState.Waiting_Trigger;
SFCTransTrigger.IN := FALSE;
get.b_active := FALSE;

CASE BreakerOperationMode OF
	eBreakerOperationMode.GenIso:
		SFCTransTrigger(IN := b_StartCondition AND NOT GenDownCheck(FALSE , b_StartCondition));
	eBreakerOperationMode.GenDroop:
		SFCTransTrigger(IN := b_StartCondition AND NOT GenDownCheck(FALSE , b_StartCondition)); 
	eBreakerOperationMode.Genfix:
		SFCTransTrigger(IN := b_StartCondition AND NOT GenDownCheck(FALSE , b_StartCondition) AND b_BESSReady AND b_BusbarACOK);
	eBreakerOperationMode.Gridfeedthrough, eBreakerOperationMode.ExtGrid: 
		SFCTransTrigger(IN := b_breakerACOK);
		get.e_state := eGenGridState.Waiting_For_AC;
		IF NOT GridOKdetect(FALSE) THEN
			get.e_state := eGenGridState.Gridcode_Release_Check;
			SFCTransTrigger.in := FALSE;
		END_IF
END_CASE

IF get.b_ModeTransActive THEN
	get.e_state := eGenGridState.Waiting_Mode_Reconnect;
END_IF

IF b_ForceOperate OR (b_breakerfb AND b_breakerACOK) THEN
	SFCTransTrigger.in := TRUE;
END_IF



//Trigger to start. Only if modeswitch is disabled.
SFCtip := SFCTransTrigger.Q AND NOT get.b_ModeTransActive AND NOT SFCtip AND NOT get.events.b_StartingInhibit;]]></ST>
      </Implementation>
    </Action>
    <Method Name="Warmup" Id="{dc24eab0-2e83-409c-9643-803d16816aff}" FolderPath="Nested Methods\">
      <Declaration><![CDATA[METHOD Warmup : BOOL
VAR_INPUT
	Skip		: BOOL;
END_VAR

VAR_INST
	t_time				: TIME;
	b_startfb			: BOOL;
	ton_StartTimeOut	: TON;
	tof_reset			: Tof := (PT:= T#20MS);
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[b_IOStartStop := TRUE;
Warmup := FALSE;

b_startFb := b_BreakerACok;
IF NOT b_breakerACOK THEN
	inputcontactor.open(TRUE);
	get.e_state := eGenGridState.Starting;
ELSE
	get.e_state := eGenGridState.Warmup;
END_IF

tof_reset(IN:= NOT ton_StartTimeOut.Q);
ton_StartTimeOut(IN := b_startfb AND tof_reset.Q, PT:= t_WarmupTime); 

IF ton_StartTimeOut.Q OR skip THEN
	get.b_gensetHot := TRUE;
	ton_StartTimeOut.IN := FALSE;
	Warmup := b_IOStartStop;
END_IF

]]></ST>
      </Implementation>
    </Method>
    <Method Name="ZeroCurrentDisconnect" Id="{a46e60cd-af5d-4a63-9b02-910556c76c6b}" FolderPath="Nested Methods\">
      <Declaration><![CDATA[METHOD ZeroCurrentDisconnect : BOOL
VAR_INPUT
END_VAR

VAR_INST
	ton_FlatZeroCurrentTimeOut 	: TON := (PT:= T#50MS);
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ton_FlatZeroCurrentTimeOut(
	IN := TO_INT(ar_BreakerCurrent[phases.L1]) = 0 OR TO_INT(ar_BreakerCurrent[phases.L2]) = 0 OR TO_INT(ar_BreakerCurrent[phases.L3]) = 0,
	Q => ZeroCurrentDisconnect);]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>