<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_SurgeProtection_IO" Id="{92d5ff81-dae2-481e-8e18-caf014ab3995}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SurgeProtection_IO
VAR
	b_read: BOOL;
END_VAR

VAR_OUTPUT
	GridSurgeProtection_OK: BOOL;
	SecondarySurgeProtection_OK: BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[GridSurgeProtection_OK := b_read[1];
SecondarySurgeProtection_OK := b_read[2];
]]></ST>
    </Implementation>
    <LineIds Name="FB_SurgeProtection_IO">
      <LineId Id="14" Count="0" />
      <LineId Id="9" Count="0" />
      <LineId Id="55" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>