{
  "controlTypeValues": {
    "TcHmi.Controls.Beckhoff.TcHmiDatagrid": {
      "attributes": {
        "HeaderBackgroundColor": {
          "color": "rgba(0, 99, 176, 1)"
        },
        "BackgroundColor": {
          "angle": 136.0,
          "stopPoints": [
            {
              "color": "rgba(71, 71, 71, 1)",
              "stop": "0%"
            },
            {
              "color": "rgba(40, 40, 40, 1)",
              "stop": "100%"
            }
          ]
        }
      },
      "themedResources": {}
    }
  },
  "controlClassValues": {
    "NavigationTabButton": {
      "attributes": {
        "BackgroundColor": {
          "angle": 90.0,
          "stopPoints": [
            {
              "color": "rgba(59, 59, 59, 1)",
              "stop": "0%"
            },
            {
              "color": "rgba(0, 0, 0, 1)",
              "stop": "100%"
            }
          ]
        }
      },
      "themedResources": {}
    }
  },
  "$schema": "./../../../ePU500/Packages/Beckhoff.TwinCAT.HMI.Framework.12.756.1/runtimes/native1.12-tchmi/Schema/ThemeDescription.Schema.json"
}