<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="ConcatMultiString" Id="{2c659215-8885-444f-8007-99ba71bd5a2c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION ConcatMultiString : STRING
VAR_INPUT
	s1: STRING;
	s2: STRING;
	s3: STRING;
	s4: STRING;
	s5: STRING;
	s6: STRING;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[ConcatMultiString := CONCAT(s1, CONCAT(s2, CONCAT(s3, CONCAT(s4, CONCAT(s5, s6)))));]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>