<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Janitza" Id="{39a3b041-a991-4c24-856c-d797ef0b9fe6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Janitza
VAR_IN_OUT
	get					: ST_PowerMonitor_get;
	b_ThirdOutputFieldAvailable	: BOOL;
	b_NeutralTransformerAvailable: BOOL;
	b_InputFieldsAvailable		: BOOL;
END_VAR
VAR
	MBRead: FB_MBReadRegs;
	t_MBTimeout				: 	TIME := T#500MS;
	w_MBStartAddress		:	WORD;
	//Set 1 is bigger, as this includes voltage measurements.
	DataBuffer				: 	ARRAY[0..62] OF REAL;
	//SecondDataBuffer		: 	ARRAY[0..62] OF REAL;
	UI_Iterator	:	UINT;
	//retrieve new data every 100ms
	GetDataTimer	:	TON := (PT := TIME#50MS);
	
	di_RotationState		: DINT;
	
	ton_DelaySFCTip			: TON := (PT := T#10MS);
	
	
END_VAR

VAR_INPUT
	ReadData: BOOL;
	b_TNmodeEnable		AT %Q* : BOOL;
	
END_VAR

VAR
	ast_InputPowerlockData	:	ARRAY[1..2] OF ST_MeasurementFieldData;
	ast_OutputPowerlockData	:	ARRAY[1..3] OF ST_MeasurementFieldData;

	StartTransmissionEdge : R_Trig;
	TransmissionDone	:	F_trig;
	
	ui_MBRetryCount	:	uint;
	
	b_busy: BOOL;
	b_CommError: BOOL;
	udi_errid: UDINT;
	udi_cbread: UDINT;
	
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Initialization
get.events.b_MBCommWarning := FALSE;
get.events.b_MBCommError := FALSE;

MBread(tTimeOut := t_MBTimeout);

//While ReadData is true, initiate data transfer every 100ms;
GetDataTimer(in:= ((NOT GetDataTimer.Q) AND ReadData));

//ReadJanitzaData();
ReadDataSFC();]]></ST>
    </Implementation>
    <Folder Name="SFC" Id="{7b546ac8-05b5-4879-b9ec-fda86df5f1f4}" />
    <Action Name="aCombineInputData" Id="{180e600d-b54b-4a85-85a4-80b021480939}" FolderPath="SFC\">
      <Implementation>
        <ST><![CDATA[IF b_InputFieldsAvailable THEN
	//Combine shared data from output fields into get struct
	get.InputField.ar_Current[Phases.L1] :=	get.InputField.powerlock[1].ar_Current[Phases.L1] + 
											get.InputField.Powerlock[2].ar_Current[Phases.L1];
	
	get.InputField.ar_Current[Phases.L2] :=	get.InputField.powerlock[1].ar_Current[Phases.L2] + 
											get.InputField.powerlock[2].ar_Current[Phases.L2];
	
	get.InputField.ar_Current[Phases.L3] :=	get.InputField.powerlock[1].ar_Current[Phases.L3] + 
											get.InputField.powerlock[2].ar_Current[Phases.L3];			
	
	get.InputField.ar_Current[Phases.N] :=	get.InputField.powerlock[1].ar_Current[Phases.N] + 
											get.InputField.powerlock[2].ar_Current[Phases.N];			
	
	get.InputField.ar_Current[Phases.AVG] :=	(get.InputField.ar_Current[Phases.L1] + 
											get.InputField.ar_Current[Phases.L2] +
											get.InputField.ar_Current[Phases.L3])/3;							
	
	Get.InputField.ar_ActivePower[Phases.L1]	:=	get.InputField.powerlock[1].ar_ActivePower[Phases.L1] + get.InputField.powerlock[2].ar_ActivePower[Phases.L1];
	Get.InputField.ar_ActivePower[Phases.L2]	:=	get.InputField.powerlock[1].ar_ActivePower[Phases.L2] + get.InputField.powerlock[2].ar_ActivePower[Phases.L2];
	Get.InputField.ar_ActivePower[Phases.L3]	:=	get.InputField.powerlock[1].ar_ActivePower[Phases.L3] + get.InputField.powerlock[2].ar_ActivePower[Phases.L3];
	Get.InputField.ar_ActivePower[Phases.AVG]	:=	get.InputField.powerlock[1].ar_ActivePower[Phases.AVG] + get.InputField.powerlock[2].ar_ActivePower[Phases.AVG];									
	Get.InputField.ar_ApparentPower[Phases.L1]	:=	get.InputField.powerlock[1].ar_ApparentPower[Phases.L1] + get.InputField.powerlock[2].ar_ApparentPower[Phases.L1];
	Get.InputField.ar_ApparentPower[Phases.L2]	:=	get.InputField.powerlock[1].ar_ApparentPower[Phases.L2] + get.InputField.powerlock[2].ar_ApparentPower[Phases.L2];	
	Get.InputField.ar_ApparentPower[Phases.L3]	:=	get.InputField.powerlock[1].ar_ApparentPower[Phases.L3] + get.InputField.powerlock[2].ar_ApparentPower[Phases.L3];
	Get.InputField.ar_ApparentPower[Phases.AVG]	:=	get.InputField.powerlock[1].ar_ApparentPower[Phases.AVG] + get.InputField.powerlock[2].ar_ApparentPower[Phases.AVG];												
	Get.InputField.ar_ReactivePower[Phases.L1]	:=	get.InputField.powerlock[1].ar_ReactivePower[Phases.L1] + get.InputField.powerlock[2].ar_ReactivePower[Phases.L1];
	Get.InputField.ar_ReactivePower[Phases.L2]	:=	get.InputField.powerlock[1].ar_ReactivePower[Phases.L2] + get.InputField.powerlock[2].ar_ReactivePower[Phases.L2];											
	Get.InputField.ar_ReactivePower[Phases.L3]	:=	get.InputField.powerlock[1].ar_ReactivePower[Phases.L3] + get.InputField.powerlock[2].ar_ReactivePower[Phases.L3];								
	Get.InputField.ar_ReactivePower[Phases.AVG]	:=	get.InputField.powerlock[1].ar_ReactivePower[Phases.AVG] + get.InputField.powerlock[2].ar_ReactivePower[Phases.AVG];	

	Get.InputField.r_EnergyConsumed		:=	get.InputField.powerlock[1].r_EnergyConsumed + 
											get.InputField.powerlock[2].r_EnergyConsumed;
	
	Get.InputField.r_EnergySupplied		:=	get.InputField.powerlock[1].r_EnergySupplied + 
											get.InputField.powerlock[2].r_EnergySupplied;
	
	get.InputField.ar_PowerFactor[Phases.L1] 	:=  PowerFactor(Get.InputField.ar_activePower[Phases.L1], Get.InputField.ar_ApparentPower[Phases.L1], Get.InputField.ar_ReactivePower[Phases.L1]); 										
	get.InputField.ar_PowerFactor[Phases.L2] 	:=  PowerFactor(Get.InputField.ar_activePower[Phases.L2], Get.InputField.ar_ApparentPower[Phases.L2], Get.InputField.ar_ReactivePower[Phases.L2]); 		
	get.InputField.ar_PowerFactor[Phases.L3] 	:=  PowerFactor(Get.InputField.ar_activePower[Phases.L3], Get.InputField.ar_ApparentPower[Phases.L3], Get.InputField.ar_ReactivePower[Phases.L3]); 									
	get.InputField.ar_THD[Phases.L1] 		:=		(ast_InputPowerLockData[1].ar_THD[Phases.L1] + ast_InputPowerLockData[2].ar_THD[Phases.L1])/2;		
	get.InputField.ar_THD[Phases.L2] 		:=		(ast_InputPowerLockData[1].ar_THD[Phases.L2] + ast_InputPowerLockData[2].ar_THD[Phases.L2])/2;	
	get.InputField.ar_THD[Phases.L3]		:=		(ast_InputPowerLockData[1].ar_THD[Phases.L3] + ast_InputPowerLockData[2].ar_THD[Phases.L3])/2;											
	get.InputField.ar_PowerFactor[Phases.AVG] :=	(get.InputField.ar_PowerFactor[Phases.L1] + get.InputField.ar_PowerFactor[Phases.L2] + get.InputField.ar_PowerFactor[Phases.L3])/3;		
	get.InputField.ar_THD[Phases.AVG] :=			(get.InputField.ar_THD[Phases.L1] + get.InputField.ar_THD[Phases.L2] + get.InputField.ar_THD[Phases.L3])/3;
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="aCombineOutputData" Id="{e60d4201-2e5a-4e45-91b9-0987642fe282}" FolderPath="SFC\">
      <Implementation>
        <ST><![CDATA[//Combine shared data from output fields into get struct
get.OutputField.ar_Current[Phases.L1] 	:=	get.OutputField.powerlock[1].ar_current[Phases.L1] + get.OutputField.powerlock[2].ar_current[Phases.L1] + get.OutputField.powerlock[3].ar_current[Phases.L1];
get.OutputField.ar_Current[Phases.L2] 	:=	get.OutputField.powerlock[1].ar_current[Phases.L2] + get.OutputField.powerlock[2].ar_current[Phases.L2] + get.OutputField.powerlock[3].ar_current[Phases.L2];
get.OutputField.ar_Current[Phases.L3] 	:=	get.OutputField.powerlock[1].ar_current[Phases.L3] + get.OutputField.powerlock[2].ar_current[Phases.L3] + get.OutputField.powerlock[3].ar_current[Phases.L3];			
get.OutputField.ar_Current[Phases.N] 	:=	get.OutputField.powerlock[1].ar_current[Phases.N] + get.OutputField.powerlock[2].ar_current[Phases.N] + get.OutputField.powerlock[3].ar_current[Phases.N];			
get.OutputField.ar_Current[Phases.AVG] :=	(get.OutputField.ar_Current[Phases.L1] + get.OutputField.ar_Current[Phases.L2] + get.OutputField.ar_Current[Phases.L3])/3;							

Get.OutputField.ar_ActivePower[Phases.L1]		:=	get.outputfield.powerlock[1].ar_ActivePower[Phases.L1] + 
													get.outputfield.powerlock[2].ar_ActivePower[Phases.L1] +
													get.outputfield.powerlock[3].ar_ActivePower[Phases.L1];
Get.OutputField.ar_ActivePower[Phases.L2]		:=	get.outputfield.powerlock[1].ar_ActivePower[Phases.L2] + 
													get.outputfield.powerlock[2].ar_ActivePower[Phases.L2] +
													get.outputfield.powerlock[3].ar_ActivePower[Phases.L2];				
Get.OutputField.ar_ActivePower[Phases.L3]		:=	get.outputfield.powerlock[1].ar_ActivePower[Phases.L3] + 
													get.outputfield.powerlock[2].ar_ActivePower[Phases.L3] + 
													get.outputfield.powerlock[3].ar_ActivePower[Phases.L3];												
Get.OutputField.ar_ActivePower[Phases.AVG]		:=	get.outputfield.powerlock[1].ar_ActivePower[Phases.AVG] + 
													get.outputfield.powerlock[2].ar_ActivePower[Phases.AVG] +
													get.outputfield.powerlock[3].ar_ActivePower[Phases.AVG];																				
Get.OutputField.ar_ApparentPower[Phases.L1]		:=	get.outputfield.powerlock[1].ar_ApparentPower[Phases.L1] + 
													get.outputfield.powerlock[2].ar_ApparentPower[Phases.L1] +
													get.outputfield.powerlock[3].ar_ApparentPower[Phases.L1];
Get.OutputField.ar_ApparentPower[Phases.L2]		:=	get.outputfield.powerlock[1].ar_ApparentPower[Phases.L2] + 
													get.outputfield.powerlock[2].ar_ApparentPower[Phases.L2] +
													get.outputfield.powerlock[3].ar_ApparentPower[Phases.L2];													
Get.OutputField.ar_ApparentPower[Phases.L3]		:=	get.outputfield.powerlock[1].ar_ApparentPower[Phases.L3] + 
													get.outputfield.powerlock[2].ar_ApparentPower[Phases.L3] +
													get.outputfield.powerlock[3].ar_ApparentPower[Phases.L3];													
Get.OutputField.ar_ApparentPower[Phases.AVG]	:=	get.outputfield.powerlock[1].ar_ApparentPower[Phases.AVG] + 
													get.outputfield.powerlock[2].ar_ApparentPower[Phases.AVG] +
													get.outputfield.powerlock[3].ar_ApparentPower[Phases.AVG];																																								
Get.OutputField.ar_ReactivePower[Phases.L1]		:=	get.outputfield.powerlock[1].ar_ReactivePower[Phases.L1] + 
													get.outputfield.powerlock[2].ar_ReactivePower[Phases.L1] +
													get.outputfield.powerlock[3].ar_ReactivePower[Phases.L1];		
Get.OutputField.ar_ReactivePower[Phases.L2]		:=	get.outputfield.powerlock[1].ar_ReactivePower[Phases.L2] + 
													get.outputfield.powerlock[2].ar_ReactivePower[Phases.L2] +
													get.outputfield.powerlock[3].ar_ReactivePower[Phases.L2];															
Get.OutputField.ar_ReactivePower[Phases.L3]		:=	get.outputfield.powerlock[1].ar_ReactivePower[Phases.L3] + 
													get.outputfield.powerlock[2].ar_ReactivePower[Phases.L3] +
													get.outputfield.powerlock[3].ar_ReactivePower[Phases.L3];															
Get.OutputField.ar_ReactivePower[Phases.AVG]	:=	get.outputfield.powerlock[1].ar_ReactivePower[Phases.AVG] + 
													get.outputfield.powerlock[2].ar_ReactivePower[Phases.AVG] +	
													get.outputfield.powerlock[3].ar_ReactivePower[Phases.AVG];																					
Get.OutputField.r_EnergyConsumed				:=	get.outputfield.powerlock[1].r_EnergyConsumed + 
													get.outputfield.powerlock[2].r_EnergyConsumed + 
													get.outputfield.powerlock[3].r_EnergyConsumed;
Get.OutputField.r_EnergySupplied				:=	get.outputfield.powerlock[1].r_EnergySupplied + 
													get.outputfield.powerlock[2].r_EnergySupplied + 
													get.outputfield.powerlock[3].r_EnergySupplied;
get.OutputField.ar_PowerFactor[Phases.L1] 		:=  PowerFactor(Get.OutputField.ar_activePower[Phases.L1], Get.OutputField.ar_ApparentPower[Phases.L1], Get.OutputField.ar_ReactivePower[Phases.L1]); 										
get.OutputField.ar_PowerFactor[Phases.L2] 		:=  PowerFactor(Get.OutputField.ar_activePower[Phases.L2], Get.OutputField.ar_ApparentPower[Phases.L2], Get.OutputField.ar_ReactivePower[Phases.L2]); 		
get.OutputField.ar_PowerFactor[Phases.L3] 		:=  PowerFactor(Get.OutputField.ar_activePower[Phases.L3], Get.OutputField.ar_ApparentPower[Phases.L3], Get.OutputField.ar_ReactivePower[Phases.L3]); 									

//if 3 output fields are available, calculate averages over 3 fields. Otherwise over 2
IF b_ThirdOutputFieldAvailable THEN
	get.OutputField.ar_THD[Phases.L1] 		:=	   (get.outputfield.powerlock[1].ar_THD[Phases.L1] + 
													get.outputfield.powerlock[2].ar_THD[Phases.L1] + 
													get.outputfield.powerlock[3].ar_THD[Phases.L1])/3;												
	get.OutputField.ar_THD[Phases.L2] 		:=     (get.outputfield.powerlock[1].ar_THD[Phases.L2] + 
													get.outputfield.powerlock[2].ar_THD[Phases.L2] + 
													get.outputfield.powerlock[3].ar_THD[Phases.L2])/3;		
	get.OutputField.ar_THD[Phases.L3]		 :=	   (get.outputfield.powerlock[1].ar_THD[Phases.L3] + 
													get.outputfield.powerlock[2].ar_THD[Phases.L3] + 
													get.outputfield.powerlock[3].ar_THD[Phases.L3])/3;														
ELSE
	get.OutputField.ar_THD[Phases.L1] 		:=	   (get.outputfield.powerlock[1].ar_THD[Phases.L1] + 
													get.outputfield.powerlock[2].ar_THD[Phases.L1])/2;											
	get.OutputField.ar_THD[Phases.L2] 		:=     (get.outputfield.powerlock[1].ar_THD[Phases.L2] + 
													get.outputfield.powerlock[2].ar_THD[Phases.L2])/2;	
	get.OutputField.ar_THD[Phases.L3]		 :=	   (get.outputfield.powerlock[1].ar_THD[Phases.L3] + 
													get.outputfield.powerlock[2].ar_THD[Phases.L3])/2;											
END_IF



get.OutputField.ar_PowerFactor[Phases.AVG] :=	(get.OutputField.ar_PowerFactor[Phases.L1] + 
												get.OutputField.ar_PowerFactor[Phases.L2] + 
												get.OutputField.ar_PowerFactor[Phases.L3])/3;		

get.OutputField.ar_THD[Phases.AVG] :=			(get.OutputField.ar_THD[Phases.L1] + 
												get.OutputField.ar_THD[Phases.L2] + 
												get.OutputField.ar_THD[Phases.L3])/3;
												
get.OutputField.r_VoltageUnbalance := 			LineUnbalance(
													r_L1 := get.OutputField.ar_LineVoltage[phases.L1],
													r_L2 := get.OutputField.ar_LineVoltage[phases.L2],
													r_L3 := get.OutputField.ar_LineVoltage[phases.L3]);
													
get.OutputField.r_CurrentUnbalance := 			LineUnbalance(
													r_L1 := get.OutputField.ar_Current[phases.L1], 
													r_L2 := get.OutputField.ar_Current[phases.L2], 
													r_L3 := get.OutputField.ar_Current[phases.L3]);

	]]></ST>
      </Implementation>
    </Action>
    <Action Name="aReadInputField1" Id="{09026925-47af-4f0d-b345-026e75e997e6}" FolderPath="SFC\">
      <Implementation>
        <ST><![CDATA[IF NOT b_InputFieldsAvailable THEN
	//skip this step if input fields are not in use
	ton_DelaySFCTip(IN:= TRUE);
	SFCTip := ton_DelaySFCTip.Q;
ELSE
	
//	IF b_ThirdOutputFieldAvailable THEN
//		//if third output field is available, Input field 1 is connected to module 2, so inputfield 1 is address 19600
//		w_MBStartAddress := 19600;
//	ELSE
//		//if no third output field is available, Input field 1 is connected to module 1, so inputfield 1 is address 19400
//		w_MBStartAddress := 19400;
//	END_IF

	MBRead(
	sIPAddr := PowerMeterConfig.IP_JANITZA,
	nTCPPort := PowerMeterConfig.MBPort_Janitza,
	nUnitID := 1,//16#FF;
	nMBAddr := 19600,//w_MBStartAddress,
	nQuantity := 50*2,
	cbLength := SIZEOF(DataBuffer),
	pDestAddr := ADR(DataBuffer),
	bExecute := NOT (b_busy OR TransmissionDone.Q),	//	<- werkt dit niet gewoon?
	bBusy => b_busy,
	bError => b_CommError,
	nErrId => udi_errid,
	cbRead => udi_cbread,
	);
	
	TransmissionDone(clk := b_busy);
	
	IF TransmissionDone.q THEN
		IF NOT b_CommError  THEN
			MapMeasuringField(firstfield := False, buffer := databuffer, data := get.InputField.Powerlock[1]);		
			ui_MBRetryCount := 0;
			sfctip := TRUE;
		ELSE
			ui_MBRetryCount := ui_MBRetryCount + 1;
			
			IF ui_MBRetryCount > 1 THEN
				get.events.b_MBCommWarning := TRUE;
			END_IF	
			
			//if comm fails 5 times in a row. try next input
			IF ui_MBRetryCount > 4 THEN
				get.Events.b_MBCommError := TRUE;
				ton_DelaySFCTip(IN:= TRUE);
				SFCTip := ton_DelaySFCTip.Q;
			END_IF
		END_IF
	END_IF
END_IF

IF MBRead.bError THEN
	MBRead.bError;
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="aReadInputField2" Id="{879d4ce2-fa80-469d-ae98-e3a65a92c6ac}" FolderPath="SFC\">
      <Implementation>
        <ST><![CDATA[IF NOT b_InputFieldsAvailable THEN
	//skip this step if input fields are not in use
	ton_DelaySFCTip(IN:= TRUE);
	SFCTip := ton_DelaySFCTip.Q;
ELSE
	
//	IF b_ThirdOutputFieldAvailable THEN
//		//if third output field is available, Input field is connected to bottom of module 2, so inputfield 2 is address 19700
//		w_MBStartAddress := 19700;
//	ELSE
//		//if no third output field is available, Input field is connected to top of module 1, so inputfield 2 is address 19500
//		w_MBStartAddress := 19600;
//	END_IF

	MBRead(
	sIPAddr := PowerMeterConfig.IP_JANITZA,
	nTCPPort := PowerMeterConfig.MBPort_Janitza,
	nUnitID := 1,//16#FF;
	nMBAddr := 19700,//w_MBStartAddress,
	nQuantity := 50*2,
	cbLength := SIZEOF(DataBuffer),
	pDestAddr := ADR(DataBuffer),
	bExecute := NOT (b_busy OR TransmissionDone.Q),	//	<- werkt dit niet gewoon?
	bBusy => b_busy,
	bError => b_CommError,
	nErrId => udi_errid,
	cbRead => udi_cbread,
	);
	
	TransmissionDone(clk := b_busy);
	
	IF TransmissionDone.q THEN
		IF NOT b_CommError THEN	
			MapMeasuringField(firstfield := False, buffer := databuffer, data := get.InputField.Powerlock[2]);
			ui_MBRetryCount := 0;
			sfctip := TRUE;
		ELSE
			ui_MBRetryCount := ui_MBRetryCount + 1;
			
			
			IF ui_MBRetryCount > 1 THEN
				get.events.b_MBCommWarning := TRUE;
			END_IF	
			
			//if comm fails 5 times in a row. try next input
			IF ui_MBRetryCount > 4 THEN
				get.Events.b_MBCommError := TRUE;
				ton_DelaySFCTip(IN:= TRUE);
				SFCTip := ton_DelaySFCTip.Q;
			END_IF
		END_IF
	END_IF
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="aReadInternalField" Id="{d526bcb8-a602-4936-a0ca-348cc77ced31}" FolderPath="SFC\">
      <Implementation>
        <ST><![CDATA[MBRead(
sIPAddr := PowerMeterConfig.IP_JANITZA,
nTCPPort := PowerMeterConfig.MBPort_Janitza,
nUnitID := 1,//16#FF;
nMBAddr := 19300,
nQuantity := 50*2,
cbLength := SIZEOF(DataBuffer),
pDestAddr := ADR(DataBuffer),
bExecute := NOT (b_busy OR TransmissionDone.Q),	//	<- werkt dit niet gewoon?
bBusy => b_busy,
bError => b_CommError,
nErrId => udi_errid,
cbRead => udi_cbread,
);

TransmissionDone(clk := b_busy);

IF TransmissionDone.q THEN
	IF NOT b_CommError  THEN
			MapMeasuringField(firstfield := False, buffer := databuffer, data := get.InternalSupply);
		ui_MBRetryCount := 0;
		sfctip := TRUE;
	ELSE
		ui_MBRetryCount := ui_MBRetryCount + 1;
				
		IF ui_MBRetryCount > 1 THEN
			get.events.b_MBCommWarning := TRUE;
		END_IF	
		
		//if comm fails 5 times in a row. try next input
		IF ui_MBRetryCount > 4 THEN
			get.Events.b_MBCommError := TRUE;
			ton_DelaySFCTip(IN:= TRUE);
			SFCTip := ton_DelaySFCTip.Q;
		END_IF
	END_IF
END_IF
]]></ST>
      </Implementation>
    </Action>
    <Action Name="aReadNeutralBess" Id="{b6f192c3-622c-4489-a181-9ac414869377}" FolderPath="SFC\">
      <Implementation>
        <ST><![CDATA[
IF NOT b_NeutraltransformerAvailable THEN
	//skip this step if third field isn't in use
	ton_DelaySFCTip(IN:= TRUE);
	SFCTip := ton_DelaySFCTip.Q;
ELSE
	MBRead(
	sIPAddr := PowerMeterConfig.IP_JANITZA,
	nTCPPort := PowerMeterConfig.MBPort_Janitza,
	nUnitID := 1,//16#FF;
	nMBAddr := 19500,
	nQuantity := 4*2,
	cbLength := SIZEOF(DataBuffer), //second databuffer replaced
	pDestAddr := ADR(DataBuffer),
	bExecute := NOT (b_busy OR TransmissionDone.Q),	//	<- werkt dit niet gewoon?
	bBusy => b_busy,
	bError => b_CommError,
	nErrId => udi_errid,
	cbRead => udi_cbread,
	);
	
	TransmissionDone(clk := b_busy);
	
	IF TransmissionDone.q THEN
		IF NOT b_CommError  THEN	
		
			//field specific data, keep separate at first. Then combine data into get struct in a later step.
			ChangeRealEndianess(IN := Databuffer[3], 1.0, get.BESS.ar_Current[Phases.N]);
			ui_MBRetryCount := 0;
			sfctip := TRUE;
		ELSE
			ui_MBRetryCount := ui_MBRetryCount + 1;

			IF ui_MBRetryCount > 1 THEN
				get.events.b_MBCommWarning := TRUE;
			END_IF	
			
			//if comm fails 5 times in a row. try next input
			IF ui_MBRetryCount > 4 THEN
				get.Events.b_MBCommError := TRUE;
				ton_DelaySFCTip(IN:= TRUE);
				SFCTip := ton_DelaySFCTip.Q;
			END_IF
		END_IF
	END_IF
END_IF
]]></ST>
      </Implementation>
    </Action>
    <Action Name="aReadOutputField1" Id="{2560e15b-336a-4bdd-a5e9-c733f2196bcb}" FolderPath="SFC\">
      <Implementation>
        <ST><![CDATA[get.events.b_ACdirectionDataInvalid := FALSE;

MBRead(
sIPAddr := PowerMeterConfig.IP_JANITZA,
nTCPPort := PowerMeterConfig.MBPort_Janitza,
nUnitID := 1,
nMBAddr := 19000,
nQuantity := 61*2,
cbLength := SIZEOF(DataBuffer),
pDestAddr := ADR(DataBuffer),
bExecute := NOT (b_busy OR TransmissionDone.Q),	//	<- werkt dit niet gewoon?
bBusy => b_busy,
bError => b_CommError,
nErrId => udi_errid,
cbRead => udi_cbread,
);

TransmissionDone(clk := b_busy);

IF TransmissionDone.q THEN
	IF NOT b_CommError THEN
		
		Mapvoltagefield(buffer := databuffer, data := get.OutputField);
		MapMeasuringField(firstfield := True, buffer := databuffer, data := get.OutputField.Powerlock[1]);
		ui_MBRetryCount := 0;
		sfctip := TRUE;
	ELSE
		ui_MBRetryCount := ui_MBRetryCount + 1;
		
		IF ui_MBRetryCount > 1 THEN
			get.events.b_MBCommWarning := TRUE;
		END_IF	
		
		//if comm fails 5 times in a row. try next input
		IF ui_MBRetryCount > 4 THEN
			get.Events.b_MBCommError := TRUE;
			ton_DelaySFCTip(IN:= TRUE);
			SFCTip := ton_DelaySFCTip.Q;
		END_IF
	END_IF
END_IF
]]></ST>
      </Implementation>
    </Action>
    <Action Name="aReadOutputField2" Id="{23a7dd3d-a6cf-41c7-9f6e-8f42bd580130}" FolderPath="SFC\">
      <Implementation>
        <ST><![CDATA[MBRead(
sIPAddr := PowerMeterConfig.IP_JANITZA,
nTCPPort := PowerMeterConfig.MBPort_Janitza,
nUnitID := 1,//16#FF,
nMBAddr := 19200,
nQuantity := 50*2,
cbLength := SIZEOF(DataBuffer),
pDestAddr := ADR(DataBuffer),
bExecute := NOT (b_busy OR TransmissionDone.Q),	//	<- werkt dit niet gewoon?
bBusy => b_busy,
bError => b_CommError,
nErrId => udi_errid,
cbRead => udi_cbread,
);

TransmissionDone(clk := b_busy);

IF TransmissionDone.q THEN
	IF NOT b_CommError THEN	
		MapMeasuringField(firstfield := False, buffer := databuffer, data := get.OutputField.Powerlock[2]);
		ui_MBRetryCount := 0;
		sfctip := TRUE;
	ELSE
		ui_MBRetryCount := ui_MBRetryCount + 1;
		
		IF ui_MBRetryCount > 1 THEN
			get.events.b_MBCommWarning := TRUE;
		END_IF	
		
		//if comm fails 5 times in a row. try next input
		IF ui_MBRetryCount > 4 THEN
			get.Events.b_MBCommError := TRUE;
			ton_DelaySFCTip(IN:= TRUE);
			SFCTip := ton_DelaySFCTip.Q;
		END_IF
	END_IF
END_IF
]]></ST>
      </Implementation>
    </Action>
    <Action Name="aReadOutputField3" Id="{a2de4e77-9600-45d8-8e1d-937b9ee1205f}" FolderPath="SFC\">
      <Implementation>
        <ST><![CDATA[IF NOT b_ThirdOutputFieldAvailable THEN
	//skip this step if third field isn't in use
	ton_DelaySFCTip(IN:= TRUE);
	SFCTip := ton_DelaySFCTip.Q;
ELSE
	MBRead(
	sIPAddr := PowerMeterConfig.IP_JANITZA,
	nTCPPort := PowerMeterConfig.MBPort_Janitza,
	nUnitID := 1,//16#FF;
	nMBAddr := 19400,
	nQuantity := 50*2,
	cbLength := SIZEOF(DataBuffer), //second databuffer replaced
	pDestAddr := ADR(DataBuffer),
	bExecute := NOT (b_busy OR TransmissionDone.Q),	//	<- werkt dit niet gewoon?
	bBusy => b_busy,
	bError => b_CommError,
	nErrId => udi_errid,
	cbRead => udi_cbread,
	);
	
	TransmissionDone(clk := b_busy);
	
	IF TransmissionDone.q THEN
		IF NOT b_CommError  THEN
			MapMeasuringField(firstfield := False, buffer := databuffer, data := get.OutputField.Powerlock[3]);	
			ui_MBRetryCount := 0;
			sfctip := TRUE;
		ELSE
			ui_MBRetryCount := ui_MBRetryCount + 1;

			IF ui_MBRetryCount > 1 THEN
				get.events.b_MBCommWarning := TRUE;
			END_IF	
			
			//if comm fails 5 times in a row. try next input
			IF ui_MBRetryCount > 4 THEN
				get.Events.b_MBCommError := TRUE;
				ton_DelaySFCTip(IN:= TRUE);
				SFCTip := ton_DelaySFCTip.Q;
			END_IF
		END_IF
	END_IF
END_IF
]]></ST>
      </Implementation>
    </Action>
    <Method Name="ChangeRealEndianess" Id="{a4dd5f34-7ca9-4bcb-89f8-7d009941ad52}">
      <Declaration><![CDATA[METHOD ChangeRealEndianess
VAR_INPUT
	IN				: REAL;
	scale			: REAL;
END_VAR

VAR_IN_OUT
	variable 		: REAL;
END_VAR

VAR_INST
	tempreal		: REAL;
	tempdword		: DWORD;
	testword		: WORD;	
END_VAR



]]></Declaration>
      <Implementation>
        <ST><![CDATA[//tempdword := PDWORD_TO_DWORD(ADR(InputReal));
//memcpy(ADR(TestWord), ADR(tempdword), 2);
//tempdword := ROL(tempdword, 16);

tempdword := PDWORD_TO_DWORD(ADR(IN));
tempdword := ROL(tempdword, 16);
tempreal := PREAL_TO_REAL(ADR(tempdword));

IF NOT IsNaN(tempreal) THEN
	variable := tempreal * scale;
END_IF

]]></ST>
      </Implementation>
    </Method>
    <Method Name="MapMeasuringField" Id="{51e6d1d3-fcc4-4c41-b2bf-860fdc197c1d}" FolderPath="SFC\">
      <Declaration><![CDATA[METHOD MapMeasuringField
VAR_INPUT
	FirstField		: BOOL;
END_VAR
VAR_IN_OUT
	buffer 		: ARRAY[*] OF REAL;
	data 		: ST_MeasurementFieldData;
END_VAR

VAR_INST
	iterStartIndex 	: WORD;
	iterator	: WORD;
	tempreal	: REAL;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[iterStartIndex := SEL(firstfield, 0, 6);

FOR iterator := 0 TO 20 DO
	tempreal := Buffer[iterator + iterstartindex];
	CASE iterator OF
		0: ChangeRealEndianess(tempreal, 1, data.ar_Current[Phases.L1]);
		1: ChangeRealEndianess(tempreal, 1, data.ar_Current[Phases.L2]);
		2: ChangeRealEndianess(tempreal, 1, data.ar_Current[Phases.L3]);
		3: ChangeRealEndianess(tempreal, 1, data.ar_Current[Phases.N]);
		4: ChangeRealEndianess(tempreal, 0.001, data.ar_ActivePower[phases.L1]);
		5: ChangeRealEndianess(tempreal, 0.001, data.ar_ActivePower[phases.L2]);
		6: ChangeRealEndianess(tempreal, 0.001, data.ar_ActivePower[phases.L3]);
		7: ChangeRealEndianess(tempreal, 0.001, data.ar_ActivePower[phases.AVG]);
		8: ChangeRealEndianess(tempreal, 0.001, data.ar_ApparentPower[phases.L1]);
		9: ChangeRealEndianess(tempreal, 0.001, data.ar_ApparentPower[phases.L2]);
		10: ChangeRealEndianess(tempreal, 0.001, data.ar_ApparentPower[phases.L3]);
		11: ChangeRealEndianess(tempreal, 0.001, data.ar_ApparentPower[phases.AVG]);
		12: ChangeRealEndianess(tempreal, 0.001, data.ar_ReactivePower[phases.L1]);
		13: ChangeRealEndianess(tempreal, 0.001, data.ar_ReactivePower[phases.L2]);
		14: ChangeRealEndianess(tempreal, 0.001, data.ar_ReactivePower[phases.L3]);
		15:	ChangeRealEndianess(tempreal, 0.001, data.ar_ReactivePower[phases.AVG]);
		16: ChangeRealEndianess(tempreal, 1, data.ar_powerfactor[phases.L1]);
		17: ChangeRealEndianess(tempreal, 1, data.ar_powerfactor[phases.L2]);
		18: ChangeRealEndianess(tempreal, 1, data.ar_powerfactor[phases.L3]);
		
	END_CASE
END_FOR 

IF firstfield THEN
	ChangeRealEndianess(buffer[34], 0.001, data.r_EnergySupplied);
	ChangeRealEndianess(buffer[38], 0.001, data.r_EnergyConsumed);
	ChangeRealEndianess(buffer[58], 1, data.ar_THD[Phases.L1]);
	ChangeRealEndianess(buffer[59], 1, data.ar_THD[Phases.L2]);
	ChangeRealEndianess(buffer[60], 1, data.ar_THD[Phases.L3]);
ELSE
	ChangeRealEndianess(buffer[26], 0.001, data.r_EnergySupplied);
	ChangeRealEndianess(buffer[30], 0.001, data.r_EnergyConsumed);
	ChangeRealEndianess(buffer[47], 1, data.ar_THD[Phases.L1]);
	ChangeRealEndianess(buffer[48], 1, data.ar_THD[Phases.L2]);
	ChangeRealEndianess(buffer[49], 1, data.ar_THD[Phases.L3]);
END_IF




data.ar_Current[Phases.AVG] := (data.ar_Current[Phases.L1] + data.ar_Current[Phases.L2] + data.ar_Current[Phases.L3])/3;
data.ar_powerfactor[phases.AVG] := (data.ar_powerfactor[phases.L1] + data.ar_powerfactor[phases.L2] + data.ar_powerfactor[phases.L3])/3;
data.ar_THD[phases.AVG] := (data.ar_THD[phases.L1] + data.ar_THD[phases.L2] + data.ar_THD[phases.L3])/3;
data.r_CurrentUnbalance := LineUnbalance(r_L1 := data.ar_Current[Phases.L1], r_L2 := data.ar_Current[Phases.L1], r_L3 :=  data.ar_Current[Phases.L3]);				
]]></ST>
      </Implementation>
    </Method>
    <Method Name="MapVoltageField" Id="{2cec6e0b-54c9-45f5-90b9-49b8eef31073}" FolderPath="SFC\">
      <Declaration><![CDATA[METHOD MapVoltageField

VAR_IN_OUT
	buffer 			: 	ARRAY[*] OF REAL;
	data			: ST_measurementVoltageData;
END_VAR

VAR
	i_rotation : INT;
END_VAR

VAR
	iterator	: WORD;
	tempreal	: REAL;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[FOR iterator := 0 TO 7 DO
	tempreal := Buffer[iterator];
	CASE iterator OF
		0: ChangeRealEndianess(tempreal,1, data.ar_PhaseVoltage[Phases.L1]);
		1: ChangeRealEndianess(tempreal,1, data.ar_PhaseVoltage[Phases.L2]);
		2: ChangeRealEndianess(tempreal,1, data.ar_PhaseVoltage[Phases.L3]);
		3: ChangeRealEndianess(tempreal,1, data.ar_LineVoltage[Phases.L1]);
		4: ChangeRealEndianess(tempreal,1, data.ar_LineVoltage[Phases.L2]);
		5: ChangeRealEndianess(tempreal,1, data.ar_LineVoltage[Phases.L3]);
	END_CASE
END_FOR 

MEMCPY(ADR(i_rotation), ADR(Buffer[26])+2, 2);
CASE i_rotation OF
	-1 	:	data.e_ACrotationStatus := eACRotationState.Left;
	1	:	data.e_ACrotationStatus := eACRotationState.Right;
	0	:	data.e_ACrotationStatus := eACRotationState.None;
	ELSE
		get.events.b_ACdirectionDataInvalid := TRUE;
END_CASE

ChangeRealEndianess(Buffer[19], 1, data.ar_Frequency[0]);

IF data.ar_LineVoltage[Phases.AVG] < 360 THEN
	data.e_ACrotationStatus := eACRotationState.None;
END_IF

data.ar_PhaseVoltage[0] := (data.ar_PhaseVoltage[Phases.L1] + data.ar_PhaseVoltage[Phases.L2] + data.ar_PhaseVoltage[Phases.L3]) / 3;
data.ar_LineVoltage[0] := (data.ar_LineVoltage[Phases.L1] + data.ar_LineVoltage[Phases.L2] + data.ar_LineVoltage[Phases.L3]) / 3;
data.r_VoltageUnbalance := LineUnbalance(r_L1 := data.ar_LineVoltage[Phases.L1], r_L2 := data.ar_LineVoltage[Phases.L2], r_L3 :=  data.ar_LineVoltage[Phases.L3]);				
				

]]></ST>
      </Implementation>
    </Method>
    <Action Name="ReadDataSFC" Id="{d47c650b-b078-4699-aabe-71eb457c26b2}" FolderPath="SFC\">
      <Implementation>
        <SFC>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="SFCImplementationObject">
                <o n="Root" t="SFCSegment">
                  <o n="ElementList" t="SFCElementList">
                    <l2 n="InnerList">
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Init_ReadData"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">3L</v>
                            <v n="IdParent">2L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">4L</v>
                            <v n="IdParent">2L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">5L</v>
                            <v n="IdParent">2L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">6L</v>
                            <v n="IdParent">2L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"TRUE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">7L</v>
                            <v n="IdParent">2L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">8L</v>
                            <v n="IdParent">2L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">9L</v>
                            <v n="IdParent">2L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">10L</v>
                            <v n="IdParent">2L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">11L</v>
                            <v n="IdParent">2L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">12L</v>
                            <v n="IdParent">2L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">13L</v>
                            <v n="IdParent">2L</v>
                          </o>
                        </l2>
                        <v n="Id">2L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"Init_ReadData__to__OutputField1"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"GetDataTimer.Q"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">15L</v>
                            <v n="IdParent">14L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">16L</v>
                            <v n="IdParent">14L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">17L</v>
                            <v n="IdParent">14L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">18L</v>
                            <v n="IdParent">14L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">19L</v>
                            <v n="IdParent">14L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">20L</v>
                            <v n="IdParent">14L</v>
                          </o>
                        </l2>
                        <v n="Id">14L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"OutputField1"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">26L</v>
                            <v n="IdParent">25L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">27L</v>
                            <v n="IdParent">25L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">28L</v>
                            <v n="IdParent">25L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">29L</v>
                            <v n="IdParent">25L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">30L</v>
                            <v n="IdParent">25L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">31L</v>
                            <v n="IdParent">25L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">32L</v>
                            <v n="IdParent">25L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">33L</v>
                            <v n="IdParent">25L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"aReadOutputField1"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">34L</v>
                            <v n="IdParent">25L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">35L</v>
                            <v n="IdParent">25L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"SFCTipReset"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">36L</v>
                            <v n="IdParent">25L</v>
                          </o>
                        </l2>
                        <v n="Id">25L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"OutputField1__to__OutputField2"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"False"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">38L</v>
                            <v n="IdParent">37L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">39L</v>
                            <v n="IdParent">37L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">40L</v>
                            <v n="IdParent">37L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">41L</v>
                            <v n="IdParent">37L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">42L</v>
                            <v n="IdParent">37L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">43L</v>
                            <v n="IdParent">37L</v>
                          </o>
                        </l2>
                        <v n="Id">37L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"OutputField2"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">45L</v>
                            <v n="IdParent">44L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">46L</v>
                            <v n="IdParent">44L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">47L</v>
                            <v n="IdParent">44L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">48L</v>
                            <v n="IdParent">44L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">49L</v>
                            <v n="IdParent">44L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">50L</v>
                            <v n="IdParent">44L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">51L</v>
                            <v n="IdParent">44L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">52L</v>
                            <v n="IdParent">44L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"aReadOutputField2"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">53L</v>
                            <v n="IdParent">44L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">54L</v>
                            <v n="IdParent">44L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"SFCTipReset"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">55L</v>
                            <v n="IdParent">44L</v>
                          </o>
                        </l2>
                        <v n="Id">44L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"OutputField2__to__OutputField3"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"False"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">57L</v>
                            <v n="IdParent">56L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">58L</v>
                            <v n="IdParent">56L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">59L</v>
                            <v n="IdParent">56L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">60L</v>
                            <v n="IdParent">56L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">61L</v>
                            <v n="IdParent">56L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">62L</v>
                            <v n="IdParent">56L</v>
                          </o>
                        </l2>
                        <v n="Id">56L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"OutputField3"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">64L</v>
                            <v n="IdParent">63L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">65L</v>
                            <v n="IdParent">63L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">66L</v>
                            <v n="IdParent">63L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">67L</v>
                            <v n="IdParent">63L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">68L</v>
                            <v n="IdParent">63L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">69L</v>
                            <v n="IdParent">63L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">70L</v>
                            <v n="IdParent">63L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">71L</v>
                            <v n="IdParent">63L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"aReadOutputField3"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">72L</v>
                            <v n="IdParent">63L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">73L</v>
                            <v n="IdParent">63L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"SFCTipReset"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">74L</v>
                            <v n="IdParent">63L</v>
                          </o>
                        </l2>
                        <v n="Id">63L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"OutputField3__to__NeutralField"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"False"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">297L</v>
                            <v n="IdParent">296L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">298L</v>
                            <v n="IdParent">296L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">299L</v>
                            <v n="IdParent">296L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">300L</v>
                            <v n="IdParent">296L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">301L</v>
                            <v n="IdParent">296L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">302L</v>
                            <v n="IdParent">296L</v>
                          </o>
                        </l2>
                        <v n="Id">296L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"NeutralField"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">345L</v>
                            <v n="IdParent">344L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">346L</v>
                            <v n="IdParent">344L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">347L</v>
                            <v n="IdParent">344L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">348L</v>
                            <v n="IdParent">344L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">349L</v>
                            <v n="IdParent">344L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">350L</v>
                            <v n="IdParent">344L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">351L</v>
                            <v n="IdParent">344L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">352L</v>
                            <v n="IdParent">344L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"aReadNeutralBess"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">353L</v>
                            <v n="IdParent">344L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">354L</v>
                            <v n="IdParent">344L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"SFCtipReset"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">355L</v>
                            <v n="IdParent">344L</v>
                          </o>
                        </l2>
                        <v n="Id">344L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"NeutralField__to__CombineOutputData"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"false"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">357L</v>
                            <v n="IdParent">356L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">358L</v>
                            <v n="IdParent">356L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">359L</v>
                            <v n="IdParent">356L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">360L</v>
                            <v n="IdParent">356L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">361L</v>
                            <v n="IdParent">356L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">362L</v>
                            <v n="IdParent">356L</v>
                          </o>
                        </l2>
                        <v n="Id">356L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"CombineOutputData"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">285L</v>
                            <v n="IdParent">284L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">286L</v>
                            <v n="IdParent">284L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">287L</v>
                            <v n="IdParent">284L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">288L</v>
                            <v n="IdParent">284L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">289L</v>
                            <v n="IdParent">284L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">290L</v>
                            <v n="IdParent">284L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">291L</v>
                            <v n="IdParent">284L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">292L</v>
                            <v n="IdParent">284L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"aCombineOutputData"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">293L</v>
                            <v n="IdParent">284L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">294L</v>
                            <v n="IdParent">284L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">295L</v>
                            <v n="IdParent">284L</v>
                          </o>
                        </l2>
                        <v n="Id">284L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"CombineOutputData__to__InputField1"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"True"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">247L</v>
                            <v n="IdParent">246L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">248L</v>
                            <v n="IdParent">246L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">249L</v>
                            <v n="IdParent">246L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">250L</v>
                            <v n="IdParent">246L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">251L</v>
                            <v n="IdParent">246L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">252L</v>
                            <v n="IdParent">246L</v>
                          </o>
                        </l2>
                        <v n="Id">246L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"InputField1"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">254L</v>
                            <v n="IdParent">253L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">255L</v>
                            <v n="IdParent">253L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">256L</v>
                            <v n="IdParent">253L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">257L</v>
                            <v n="IdParent">253L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">258L</v>
                            <v n="IdParent">253L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">259L</v>
                            <v n="IdParent">253L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">260L</v>
                            <v n="IdParent">253L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">261L</v>
                            <v n="IdParent">253L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"aReadInputField1"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">262L</v>
                            <v n="IdParent">253L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">263L</v>
                            <v n="IdParent">253L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"SFCTipReset"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">264L</v>
                            <v n="IdParent">253L</v>
                          </o>
                        </l2>
                        <v n="Id">253L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"InputField1__to__Delay"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"False"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">266L</v>
                            <v n="IdParent">265L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">267L</v>
                            <v n="IdParent">265L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">268L</v>
                            <v n="IdParent">265L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">269L</v>
                            <v n="IdParent">265L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">270L</v>
                            <v n="IdParent">265L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">271L</v>
                            <v n="IdParent">265L</v>
                          </o>
                        </l2>
                        <v n="Id">265L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Delay"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">333L</v>
                            <v n="IdParent">332L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">334L</v>
                            <v n="IdParent">332L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">335L</v>
                            <v n="IdParent">332L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">336L</v>
                            <v n="IdParent">332L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">337L</v>
                            <v n="IdParent">332L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">338L</v>
                            <v n="IdParent">332L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"T#10ms"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">339L</v>
                            <v n="IdParent">332L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">340L</v>
                            <v n="IdParent">332L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">341L</v>
                            <v n="IdParent">332L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">342L</v>
                            <v n="IdParent">332L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">343L</v>
                            <v n="IdParent">332L</v>
                          </o>
                        </l2>
                        <v n="Id">332L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"Delay__to__InputField2"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"true"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">326L</v>
                            <v n="IdParent">325L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">327L</v>
                            <v n="IdParent">325L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">328L</v>
                            <v n="IdParent">325L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">329L</v>
                            <v n="IdParent">325L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">330L</v>
                            <v n="IdParent">325L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">331L</v>
                            <v n="IdParent">325L</v>
                          </o>
                        </l2>
                        <v n="Id">325L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"InputField2"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">146L</v>
                            <v n="IdParent">145L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">147L</v>
                            <v n="IdParent">145L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">148L</v>
                            <v n="IdParent">145L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">149L</v>
                            <v n="IdParent">145L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">150L</v>
                            <v n="IdParent">145L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">151L</v>
                            <v n="IdParent">145L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">152L</v>
                            <v n="IdParent">145L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">153L</v>
                            <v n="IdParent">145L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"aReadInputField2"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">154L</v>
                            <v n="IdParent">145L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">155L</v>
                            <v n="IdParent">145L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"SFCTipReset"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">156L</v>
                            <v n="IdParent">145L</v>
                          </o>
                        </l2>
                        <v n="Id">145L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"InputField2__to__CombineInputData"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"False"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">316L</v>
                            <v n="IdParent">315L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">317L</v>
                            <v n="IdParent">315L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">318L</v>
                            <v n="IdParent">315L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">319L</v>
                            <v n="IdParent">315L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">320L</v>
                            <v n="IdParent">315L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">321L</v>
                            <v n="IdParent">315L</v>
                          </o>
                        </l2>
                        <v n="Id">315L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"CombineInputData"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">304L</v>
                            <v n="IdParent">303L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">305L</v>
                            <v n="IdParent">303L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">306L</v>
                            <v n="IdParent">303L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">307L</v>
                            <v n="IdParent">303L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">308L</v>
                            <v n="IdParent">303L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">309L</v>
                            <v n="IdParent">303L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">310L</v>
                            <v n="IdParent">303L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">311L</v>
                            <v n="IdParent">303L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"aCombineInputData"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">312L</v>
                            <v n="IdParent">303L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">313L</v>
                            <v n="IdParent">303L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">314L</v>
                            <v n="IdParent">303L</v>
                          </o>
                        </l2>
                        <v n="Id">303L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"CombineInputData__to__InternalField"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"True"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">190L</v>
                            <v n="IdParent">189L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">191L</v>
                            <v n="IdParent">189L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">192L</v>
                            <v n="IdParent">189L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">193L</v>
                            <v n="IdParent">189L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">194L</v>
                            <v n="IdParent">189L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">195L</v>
                            <v n="IdParent">189L</v>
                          </o>
                        </l2>
                        <v n="Id">189L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCStep">
                        <n n="EmbeddedMainAction" />
                        <n n="EmbeddedEntryAction" />
                        <n n="EmbeddedExitAction" />
                        <l2 n="EmbeddedMainActionProperties" />
                        <l2 n="EmbeddedEntryActionProperties" />
                        <l2 n="EmbeddedExitActionProperties" />
                        <o n="ElementList" t="SFCElementList">
                          <l2 n="InnerList" />
                        </o>
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"InternalField"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">197L</v>
                            <v n="IdParent">196L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">198L</v>
                            <v n="IdParent">196L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">199L</v>
                            <v n="IdParent">196L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">200L</v>
                            <v n="IdParent">196L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">201L</v>
                            <v n="IdParent">196L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">202L</v>
                            <v n="IdParent">196L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">203L</v>
                            <v n="IdParent">196L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">204L</v>
                            <v n="IdParent">196L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"aReadInternalField"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">205L</v>
                            <v n="IdParent">196L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">206L</v>
                            <v n="IdParent">196L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"SFCTipReset"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">207L</v>
                            <v n="IdParent">196L</v>
                          </o>
                        </l2>
                        <v n="Id">196L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCTransition">
                        <v n="VariableName">"InternalField__to__Init_ReadData"</v>
                        <n n="EmbeddedTransition" />
                        <l2 n="EmbeddedTransitionProperties" />
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"False"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">158L</v>
                            <v n="IdParent">157L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">159L</v>
                            <v n="IdParent">157L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">160L</v>
                            <v n="IdParent">157L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">161L</v>
                            <v n="IdParent">157L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">162L</v>
                            <v n="IdParent">157L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                            <o n="Value" t="EnumValue">
                              <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                              <n n="BaseType" />
                              <v n="Value">"0"</v>
                              <v n="DefaultValue">"0"</v>
                            </o>
                            <v n="Id">163L</v>
                            <v n="IdParent">157L</v>
                          </o>
                        </l2>
                        <v n="Id">157L</v>
                        <v n="IdParent">1L</v>
                      </o>
                      <o t="SFCJump">
                        <l2 n="Attributes" cet="SFCAttribute">
                          <o>
                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">"Init_ReadData"</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">22L</v>
                            <v n="IdParent">21L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                            <o n="Value" t="StringValue">
                              <v n="Value">""</v>
                              <v n="DefaultValue">""</v>
                            </o>
                            <v n="Id">23L</v>
                            <v n="IdParent">21L</v>
                          </o>
                          <o>
                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                            <o n="Value" t="BoolValue">
                              <v n="Value">"FALSE"</v>
                              <v n="DefaultValue">"FALSE"</v>
                            </o>
                            <v n="Id">24L</v>
                            <v n="IdParent">21L</v>
                          </o>
                        </l2>
                        <v n="Id">21L</v>
                        <v n="IdParent">1L</v>
                      </o>
                    </l2>
                  </o>
                  <l2 n="Attributes" cet="SFCAttribute">
                    <o>
                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                      <o n="Value" t="StringValue">
                        <v n="Value">""</v>
                        <v n="DefaultValue">""</v>
                      </o>
                      <v n="Id">322L</v>
                      <v n="IdParent">1L</v>
                    </o>
                    <o>
                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                      <o n="Value" t="StringValue">
                        <v n="Value">""</v>
                        <v n="DefaultValue">""</v>
                      </o>
                      <v n="Id">323L</v>
                      <v n="IdParent">1L</v>
                    </o>
                    <o>
                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                      <o n="Value" t="BoolValue">
                        <v n="Value">"FALSE"</v>
                        <v n="DefaultValue">"FALSE"</v>
                      </o>
                      <v n="Id">324L</v>
                      <v n="IdParent">1L</v>
                    </o>
                  </l2>
                  <v n="Id">1L</v>
                  <v n="IdParent">-1L</v>
                </o>
                <d2 n="Categories" ckt="Guid" cvt="SFCAttributeCategory">
                  <v>1c5c6e05-2bb7-4258-bcee-fd16a540c63c</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Identifier">"Specific"</v>
                    <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                    <v n="Description">"Element type specific properties"</v>
                  </o>
                  <v>20f0fc67-978d-438b-979f-eef294f34ee4</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Identifier">"Actions"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Action definitions"</v>
                  </o>
                  <v>6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Identifier">"Common"</v>
                    <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                    <v n="Description">"Common properties"</v>
                  </o>
                  <v>d336ba06-8a67-4e6b-9697-50f83ba6bdde</v>
                  <o>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                    <v n="Identifier">"Times"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Time definitions"</v>
                  </o>
                </d2>
                <d2 n="Attributes" ckt="Guid" cvt="SFCAttributeDescription">
                  <v>01580b27-6378-448b-8ecb-0e4b795b58d6</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">true</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                    <v n="Identifier">"Exclude"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Exclude this element from build"</v>
                  </o>
                  <v>23bdaa98-72ec-41f7-817b-9dede5697086</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                    <v n="Identifier">"Parallel"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Sets the branch to parallel mode"</v>
                  </o>
                  <v>38391c6d-6d4a-42f8-8ee7-9f45e5adafa8</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                    <v n="Identifier">"Name"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Name of the element"</v>
                  </o>
                  <v>62e1754b-7629-4e63-9cec-10ae0c536f1f</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                    <v n="Identifier">"Duplication"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Copies the implementation of step actions or transitions with the element. Otherwise, copies the reference to an existing implementation."</v>
                  </o>
                  <v>6844a48e-46c2-4cc8-a185-a478f3b99cc0</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                    <v n="Identifier">"InitStep"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Sets the step as the initial step"</v>
                  </o>
                  <v>700a583f-b4d4-43e4-8c14-629c7cd3bec8</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                    <v n="Identifier">"MainAction"</v>
                    <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Description">"Name of the action to be called if the step is active"</v>
                  </o>
                  <v>7d894980-aeea-405c-a0f6-e2b26429c58f</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">true</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                    <v n="Identifier">"Comment"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Comment of the element"</v>
                  </o>
                  <v>8294df19-5962-4dee-a874-1051dabb0e3e</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                    <v n="Identifier">"Monitoring"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Indicates transition monitoring setting."</v>
                  </o>
                  <v>a2621e18-7de3-4ea6-ae6d-89e9e0b7befd</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                    <v n="Identifier">"ExitAction"</v>
                    <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Description">"Name of the action to be called if the step is deactivated"</v>
                  </o>
                  <v>a6b08bd8-b696-47e3-9cbf-7408b61c9ff8</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                    <v n="Identifier">"EntryAction"</v>
                    <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                    <v n="Description">"Name of the action to be called if the step is activated"</v>
                  </o>
                  <v>b693554c-1b01-4a8d-afde-9e3a46f7465d</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                    <v n="Identifier">"MaxTime"</v>
                    <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                    <v n="Description">"Defines the maximal active time for the step"</v>
                  </o>
                  <v>bc882c11-1e91-4dd8-a6b8-2075724ed18b</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                    <v n="Identifier">"Symbol"</v>
                    <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                    <v n="Description">"Symbol configuration setting of the element"</v>
                  </o>
                  <v>cacf1a68-236e-47c2-b7b1-1cf9199718cb</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">true</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                    <v n="Identifier">"MinTime"</v>
                    <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                    <v n="Description">"Defines the minimal active time for the step"</v>
                  </o>
                  <v>e174fc0d-80b0-4a9e-a530-ca239c249a50</v>
                  <o>
                    <v n="ReadOnly">false</v>
                    <v n="Hidden">false</v>
                    <v n="EditorVisibility">false</v>
                    <v n="MultiLineEdit">false</v>
                    <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                    <v n="Id">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                    <v n="Identifier">"Qualifier"</v>
                    <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                    <v n="Description">"Qualifier of the action association"</v>
                  </o>
                </d2>
                <d2 n="EnumTemplates" ckt="Guid" cvt="EnumValueTemplate">
                  <v>6ecff51c-9b8f-4338-aab0-67c2b31b07e9</v>
                  <o>
                    <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                    <l n="Values" t="ArrayList" cet="EnumEntry">
                      <o>
                        <v n="Identifier">"None"</v>
                        <v n="Value">0L</v>
                        <v n="Key">"None"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Variable"</v>
                        <v n="Value">1L</v>
                        <v n="Key">"Variable"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Call"</v>
                        <v n="Value">2L</v>
                        <v n="Key">"Call"</v>
                      </o>
                    </l>
                    <v n="BaseType">"INT"</v>
                  </o>
                  <v>79a4fdd5-c859-4de4-aa8d-c03372c880c2</v>
                  <o>
                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                    <l n="Values" t="ArrayList" cet="EnumEntry">
                      <o>
                        <v n="Identifier">"Unspecified"</v>
                        <v n="Value">0L</v>
                        <v n="Key">"Unspecified"</v>
                      </o>
                      <o>
                        <v n="Identifier">"None"</v>
                        <v n="Value">1L</v>
                        <v n="Key">"None"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Read"</v>
                        <v n="Value">2L</v>
                        <v n="Key">"Read"</v>
                      </o>
                      <o>
                        <v n="Identifier">"Write"</v>
                        <v n="Value">3L</v>
                        <v n="Key">"Write"</v>
                      </o>
                      <o>
                        <v n="Identifier">"ReadWrite"</v>
                        <v n="Value">4L</v>
                        <v n="Key">"ReadWrite"</v>
                      </o>
                    </l>
                    <v n="BaseType">"INT"</v>
                  </o>
                </d2>
              </o>
            </Data>
            <TypeList>
              <Type n="ArrayList">System.Collections.ArrayList</Type>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="BoolValue">{89e1c7bb-c9f8-4be3-b8a7-019cdbb9f7e8}</Type>
              <Type n="EnumEntry">{4185e6da-1717-44c9-b705-102861764479}</Type>
              <Type n="EnumValue">{4dd7572b-4b9d-4d35-963e-6a34a4aaa5c1}</Type>
              <Type n="EnumValueTemplate">{d6bfe4f0-d62f-4b5f-9f95-2bbeb1950e28}</Type>
              <Type n="Guid">System.Guid</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="SFCAttribute">{21f3f16e-04fa-4637-b6b7-d84e4192e99f}</Type>
              <Type n="SFCAttributeCategory">{679adacf-f2a4-4167-a3f7-d21cfc5d451f}</Type>
              <Type n="SFCAttributeDescription">{d851789d-af2c-4990-9d48-a7bdc9181773}</Type>
              <Type n="SFCElementList">{587d6556-cfe6-4e76-9cc9-fc0daf0c8c29}</Type>
              <Type n="SFCImplementationObject">{74f81948-1328-492c-b6c1-a9ea72048b28}</Type>
              <Type n="SFCJump">{7e39ac27-154f-419a-a255-6a6cf37d5ed0}</Type>
              <Type n="SFCSegment">{f1db7f6f-4774-46a6-ad9b-a94414f875fc}</Type>
              <Type n="SFCStep">{86ee92a2-d863-4136-be27-82b36d84211c}</Type>
              <Type n="SFCTransition">{4ecb29e8-a90a-4646-84ac-2ff54215ab29}</Type>
              <Type n="String">System.String</Type>
              <Type n="StringValue">{778c8bac-3fa0-41e1-99d3-2b628d12d3e5}</Type>
            </TypeList>
          </XmlArchive>
        </SFC>
      </Implementation>
      <ObjectProperties>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="SFCProperty">
              <n n="SFCErrorAnalyzation" />
              <n n="SFCErrorAnalyzationTable" />
              <v n="Title">"IecSfc"</v>
              <v n="Company">"System"</v>
              <v n="Version">"3.4.2.0"</v>
              <v n="Namespace">""</v>
              <d2 n="Flags" ckt="Flags" cvt="SFCPropertyFlagData">
                <v>EnableLimit</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Init</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Reset</v>
                <o>
                  <v n="Use">true</v>
                  <v n="Declare">true</v>
                </o>
                <v>QuitError</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Pause</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Error</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Trans</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>ErrorStep</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>ErrorPOU</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>CurrentStep</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>Tip</v>
                <o>
                  <v n="Use">true</v>
                  <v n="Declare">true</v>
                </o>
                <v>TipMode</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>SFCErrorAnalyzation</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
                <v>SFCErrorAnalyzationTable</v>
                <o>
                  <v n="Use">false</v>
                  <v n="Declare">true</v>
                </o>
              </d2>
              <v n="CalcActiveTransOnly">false</v>
              <v n="UseDefaults">false</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="Flags">{27d8150b-ef58-4fff-8da1-1f7dd5f9ea51}</Type>
            <Type n="SFCProperty">{58548d2c-f1b1-453d-9195-66c94e2a3ae0}</Type>
            <Type n="SFCPropertyFlagData">{24565a38-6368-4874-ab9a-0ef7ec269521}</Type>
            <Type n="String">System.String</Type>
          </TypeList>
        </XmlArchive>
      </ObjectProperties>
    </Action>
    <Action Name="SFCTipReset" Id="{097b2a57-11df-4388-96f3-9b159a6b302d}" FolderPath="SFC\">
      <Implementation>
        <ST><![CDATA[ton_DelaySFCTip(IN:= FALSE);
SFCTip := ton_DelaySFCTip.Q;]]></ST>
      </Implementation>
    </Action>
    <LineIds Name="FB_Janitza">
      <LineId Id="1652" Count="0" />
      <LineId Id="1551" Count="0" />
      <LineId Id="1650" Count="1" />
      <LineId Id="1602" Count="0" />
      <LineId Id="1548" Count="0" />
      <LineId Id="1547" Count="0" />
      <LineId Id="1546" Count="0" />
      <LineId Id="1441" Count="0" />
      <LineId Id="1381" Count="0" />
      <LineId Id="1549" Count="0" />
    </LineIds>
    <LineIds Name="FB_Janitza.aCombineInputData">
      <LineId Id="142" Count="44" />
      <LineId Id="101" Count="0" />
    </LineIds>
    <LineIds Name="FB_Janitza.aCombineOutputData">
      <LineId Id="204" Count="92" />
      <LineId Id="192" Count="0" />
    </LineIds>
    <LineIds Name="FB_Janitza.aReadInputField1">
      <LineId Id="190" Count="54" />
      <LineId Id="175" Count="0" />
    </LineIds>
    <LineIds Name="FB_Janitza.aReadInputField2">
      <LineId Id="105" Count="51" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_Janitza.aReadInternalField">
      <LineId Id="391" Count="36" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_Janitza.aReadNeutralBess">
      <LineId Id="90" Count="0" />
      <LineId Id="2" Count="0" />
      <LineId Id="66" Count="0" />
      <LineId Id="96" Count="0" />
      <LineId Id="64" Count="1" />
      <LineId Id="3" Count="0" />
      <LineId Id="67" Count="0" />
      <LineId Id="5" Count="10" />
      <LineId Id="17" Count="5" />
      <LineId Id="94" Count="0" />
      <LineId Id="23" Count="0" />
      <LineId Id="100" Count="0" />
      <LineId Id="46" Count="3" />
      <LineId Id="51" Count="8" />
      <LineId Id="97" Count="0" />
      <LineId Id="60" Count="2" />
      <LineId Id="1" Count="0" />
      <LineId Id="89" Count="0" />
    </LineIds>
    <LineIds Name="FB_Janitza.aReadOutputField1">
      <LineId Id="16090" Count="40" />
      <LineId Id="25" Count="0" />
    </LineIds>
    <LineIds Name="FB_Janitza.aReadOutputField2">
      <LineId Id="121" Count="36" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_Janitza.aReadOutputField3">
      <LineId Id="100" Count="42" />
      <LineId Id="89" Count="0" />
    </LineIds>
    <LineIds Name="FB_Janitza.ChangeRealEndianess">
      <LineId Id="229" Count="0" />
      <LineId Id="242" Count="1" />
      <LineId Id="317" Count="0" />
      <LineId Id="297" Count="0" />
      <LineId Id="296" Count="0" />
      <LineId Id="283" Count="0" />
      <LineId Id="315" Count="0" />
      <LineId Id="277" Count="1" />
      <LineId Id="275" Count="0" />
      <LineId Id="261" Count="0" />
      <LineId Id="259" Count="0" />
    </LineIds>
    <LineIds Name="FB_Janitza.MapMeasuringField">
      <LineId Id="158" Count="48" />
      <LineId Id="48" Count="0" />
    </LineIds>
    <LineIds Name="FB_Janitza.MapVoltageField">
      <LineId Id="79" Count="0" />
      <LineId Id="89" Count="0" />
      <LineId Id="86" Count="0" />
      <LineId Id="92" Count="0" />
      <LineId Id="96" Count="1" />
      <LineId Id="95" Count="0" />
      <LineId Id="99" Count="1" />
      <LineId Id="88" Count="0" />
      <LineId Id="83" Count="0" />
      <LineId Id="152" Count="0" />
      <LineId Id="184" Count="6" />
      <LineId Id="149" Count="0" />
      <LineId Id="168" Count="0" />
      <LineId Id="167" Count="0" />
      <LineId Id="169" Count="0" />
      <LineId Id="150" Count="1" />
      <LineId Id="139" Count="0" />
      <LineId Id="65" Count="0" />
      <LineId Id="138" Count="0" />
      <LineId Id="137" Count="0" />
      <LineId Id="66" Count="0" />
      <LineId Id="53" Count="0" />
      <LineId Id="52" Count="0" />
      <LineId Id="48" Count="0" />
    </LineIds>
    <LineIds Name="FB_Janitza.SFCTipReset">
      <LineId Id="2" Count="0" />
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>