<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_DCSwitchgear" Id="{dd571d5c-e744-4b94-9f6f-9bb8e17dc6de}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_DCSwitchgear
VAR_INPUT
END_VAR
VAR_OUTPUT
	get		: ST_DCSwitchgear_get;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_DCSwitchgear">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>