{
  "controlTypeValues": {
    "TcHmi.Controls.Beckhoff.TcHmiButton": {
      "attributes": {
        "BackgroundColor": {
          "angle": 90.0,
          "stopPoints": [
            {
              "color": "rgba(239, 241, 243, 1)",
              "stop": "0%"
            },
            {
              "color": "rgba(236, 236, 236, 1)",
              "stop": "100%"
            }
          ]
        },
        "BorderColor": {
          "color": "None"
        },
        "TextFontStyle": "Normal",
        "TextFontWeight": "Auto",
        "TextFontSize": 13.0,
        "TextFontFamily": "Arial"
      },
      "themedResources": {}
    },
    "TcHmi.Controls.Beckhoff.TcHmiDatagrid": {
      "attributes": {
        "BackgroundColor": {
          "color": "rgba(255, 255, 255, 1)"
        }
      },
      "themedResources": {}
    }
  },
  "controlClassValues": {
    "NavigationTabButton": {
      "attributes": {
        "BackgroundColor": {
          "angle": 90.0,
          "stopPoints": [
            {
              "color": "rgba(224, 224, 224, 1)",
              "stop": "0.37%"
            },
            {
              "color": "rgba(243, 243, 243, 1)",
              "stop": "100%"
            }
          ]
        }
      },
      "themedResources": {}
    }
  },
  "$schema": "./../../../ePU500/Packages/Beckhoff.TwinCAT.HMI.Framework.12.756.1/runtimes/native1.12-tchmi/Schema/ThemeDescription.Schema.json"
}